from django.urls import path
from grandchallenge.pathology import views

app_name = "pathology"
urlpatterns = [
    path(
        "patient_item/", views.PatientItemTable.as_view(), name="patient-items"
    ),
    path(
        "patient_item/<uuid:pk>/",
        views.PatientItemRecord.as_view(),
        name="patient-item",
    ),
    path(
        "patient_item/create/",
        views.PatientItemCreateView.as_view(),
        name="patient-item-create",
    ),
    path(
        "patient_item/remove/<uuid:pk>/",
        views.PatientItemRemoveView.as_view(),
        name="patient-item-remove",
    ),
    path(
        "patient_item/update/<uuid:pk>/",
        views.PatientItemUpdateView.as_view(),
        name="patient-item-update",
    ),
    path(
        "patient_item/display/",
        views.PatientItemDisplayView.as_view(),
        name="patient-item-display",
    ),
    path("study_item/", views.StudyItemTable.as_view(), name="study-items"),
    path(
        "study_item/<uuid:pk>/",
        views.StudyItemRecord.as_view(),
        name="study-item",
    ),
    path(
        "study_item/create/",
        views.StudyItemCreateView.as_view(),
        name="study-item-create",
    ),
    path(
        "study_item/remove/<uuid:pk>/",
        views.StudyItemRemoveView.as_view(),
        name="study-item-remove",
    ),
    path(
        "study_item/update/<uuid:pk>/",
        views.StudyItemUpdateView.as_view(),
        name="study-item-update",
    ),
    path(
        "study_item/display/",
        views.StudyItemDisplayView.as_view(),
        name="study-item-display",
    ),
    path(
        "worklist_item/",
        views.WorklistItemTable.as_view(),
        name="worklist-items",
    ),
    path(
        "worklist_item/<uuid:pk>/",
        views.WorklistItemRecord.as_view(),
        name="worklist-item",
    ),
    path(
        "worklist_item/create/",
        views.WorklistItemCreateView.as_view(),
        name="worklist-item-create",
    ),
    path(
        "worklist_item/remove/<uuid:pk>/",
        views.WorklistItemRemoveView.as_view(),
        name="worklist-item-remove",
    ),
    path(
        "worklist_item/update/<uuid:pk>/",
        views.WorklistItemUpdateView.as_view(),
        name="worklist-item-update",
    ),
    path(
        "worklist_item/display/",
        views.WorklistItemDisplayView.as_view(),
        name="worklist-item-display",
    ),
]
