# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicmodels', '0006_auto_20180319_1804'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='page',
            table=None,
        ),
    ]
