# Generated by Django 3.0.6 on 2020-06-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy", options={"ordering": ("pk",)},
        ),
    ]
