# Generated by Django 3.2.13 on 2022-05-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0002_auto_20200611_1053"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalpolicy",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical policy",
                "verbose_name_plural": "historical policys",
            },
        ),
        migrations.AlterField(
            model_name="historicalpolicy",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
