# Generated by Django 5.2.16 on 2026-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("policies", "0004_delete_historicalpolicy"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="policy",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="policies_policy_unique_slug"
            ),
        ),
    ]
