# Generated by Django 3.1.9 on 2021-05-12 14:37

from django.db import migrations, models

import grandchallenge.core.storage


class Migration(migrations.Migration):
    dependencies = [("organizations", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
            ),
        )
    ]
