# Generated by Django 4.2.16 on 2024-11-28 16:56

from django.db import migrations, models

import grandchallenge.components.schemas
import grandchallenge.components.utils
import grandchallenge.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_organization_exempt_from_base_costs"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="algorithm_maximum_settable_memory_gb",
            field=models.PositiveSmallIntegerField(
                default=32,
                help_text="Maximum amount of memory that members will be allowed to assign to algorithm inference jobs.",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="algorithm_selectable_gpu_type_choices",
            field=models.JSONField(
                default=grandchallenge.components.schemas.get_default_gpu_type_choices,
                help_text='The GPU type choices that members will be able to select for their algorithm inference jobs. Options are ["", "A100", "A10G", "V100", "K80", "T4"].',
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema",
                            "items": {
                                "enum": [
                                    "",
                                    "A100",
                                    "A10G",
                                    "V100",
                                    "K80",
                                    "T4",
                                ],
                                "type": "string",
                            },
                            "title": "The Selectable GPU Types Schema",
                            "type": "array",
                            "uniqueItems": True,
                        }
                    )
                ],
            ),
        ),
    ]
