# Generated by Django 4.2.21 on 2025-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0009_organizationuserobjectpermission_organizatio_user_id_a3cd10_idx",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="algorithm_maximum_settable_memory_gb",
            field=models.PositiveSmallIntegerField(
                default=32,
                help_text="Maximum amount of memory (DRAM) that members will be allowed to assign to algorithm inference jobs.",
            ),
        ),
    ]
