# Generated by Django 4.2.26 on 2025-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0010_alter_organization_algorithm_maximum_settable_memory_gb",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="logo_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
    ]
