# Generated by Django 2.2.3 on 2019-08-01 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("workstations", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="session", options={"ordering": ["-created"]}
        ),
        migrations.AlterModelOptions(
            name="workstationimage", options={"ordering": ["-created"]}
        ),
    ]
