# Generated by Django 2.2.4 on 2019-08-09 08:15

from django.db import migrations


def delete_workstation_groups(apps, schema_editor):
    Workstation = apps.get_model("workstations", "Workstation")

    for ws in Workstation.objects.all():
        ws.editors_group.delete(keep_parents=True)
        ws.users_group.delete(keep_parents=True)

        ws.editors_group = None
        ws.users_group = None

        ws.save()


def create_workstation_groups(apps, schema_editor):
    from grandchallenge.workstations.models import Workstation

    for ws in Workstation.objects.all():
        ws.create_groups()
        ws.save()
        ws.assign_permissions()

        for wsi in ws.workstationimage_set.all():
            wsi.assign_permissions()


class Migration(migrations.Migration):

    dependencies = [("workstations", "0002_auto_20190809_0839")]

    operations = [
        migrations.RunPython(
            create_workstation_groups, delete_workstation_groups
        )
    ]
