# Generated by Django 3.1.6 on 2021-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0002_session_auth_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsession",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Started"),
                    (2, "Running"),
                    (3, "Failed"),
                    (4, "Stopped"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Started"),
                    (2, "Running"),
                    (3, "Failed"),
                    (4, "Stopped"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
