# Generated by Django 2.2.4 on 2019-08-14 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("workstations", "0003_group_data_migration")]

    operations = [
        migrations.AlterModelOptions(
            name="session", options={"ordering": ("created", "creator")}
        ),
        migrations.AlterModelOptions(
            name="workstation", options={"ordering": ("created", "title")}
        ),
        migrations.AlterModelOptions(
            name="workstationimage",
            options={"ordering": ("created", "creator")},
        ),
        migrations.AlterField(
            model_name="workstation",
            name="editors_group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editors_of_workstation",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="workstation",
            name="users_group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_of_workstation",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="workstationimage",
            name="initial_path",
            field=models.CharField(
                blank=True,
                default="Applications/CIRRUSCoreWeb/DIAG/CIRRUSCore/Modules/www/index.html",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This path is invalid, it must not start with a /",
                        regex="^(?:[^/][^\\s]*)\\Z",
                    )
                ],
            ),
        ),
    ]
