# Generated by Django 2.2.6 on 2019-10-15 10:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstation_configs", "0001_initial"),
        ("workstations", "0004_auto_20190814_1402"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstation",
            name="config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workstation_configs.WorkstationConfig",
            ),
        ),
        migrations.AlterField(
            model_name="workstationimage",
            name="initial_path",
            field=models.CharField(
                default="cirrus",
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This path is invalid, it must not start with a /",
                        regex="^(?:[^/][^\\s]*)\\Z",
                    )
                ],
            ),
        ),
    ]
