# Generated by Django 3.1.13 on 2021-10-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0006_workstationimage_user_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workstationimage", name="staged_image_uuid",
        ),
    ]
