# Generated by Django 3.2.13 on 2022-05-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workstations", "0007_remove_workstationimage_staged_image_uuid"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalsession",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical session",
                "verbose_name_plural": "historical sessions",
            },
        ),
        migrations.AlterField(
            model_name="historicalsession",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
