# Generated by Django 3.2.13 on 2022-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0008_auto_20220517_0740"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationimage",
            name="latest_shimmed_version",
            field=models.CharField(default="", editable=False, max_length=8),
        ),
    ]
