# Generated by Django 3.2.13 on 2022-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workstations", "0009_alter_workstation_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationimage",
            name="latest_shimmed_version",
            field=models.CharField(default="", editable=False, max_length=8),
        ),
    ]
