# Generated by Django 3.0.6 on 2020-06-05 08:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workstations", "0009_auto_20200507_0758"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="ping_times",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True, default=None, null=True
            ),
        ),
    ]
