# Generated by Django 3.2.14 on 2022-07-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workstations", "0011_auto_20220707_1129"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workstationimage",
            name="requires_cpu_cores",
        ),
        migrations.RemoveField(
            model_name="workstationimage",
            name="requires_gpu_memory_gb",
        ),
        migrations.AlterField(
            model_name="workstationimage",
            name="ready",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Is this image ready to be used?",
                null=True,
            ),
        ),
    ]
