# Generated by Django 3.2.14 on 2022-07-25 10:32

import uuid

import django.db.models.deletion
from django.db import migrations, models

import grandchallenge.core.storage
import grandchallenge.workstations.models


class Migration(migrations.Migration):
    dependencies = [
        ("workstations", "0012_auto_20220713_2004"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        storage=grandchallenge.core.storage.ProtectedS3Storage(),
                        upload_to=grandchallenge.workstations.models.feedback_screenshot_filepath,
                    ),
                ),
                ("user_comment", models.TextField()),
                ("context", models.TextField(blank=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workstations.session",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
