# Generated by Django 3.2.14 on 2022-08-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workstations", "0013_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="context",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
