# Generated by Django 4.1.10 on 2023-08-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workstations", "0018_remove_workstationimage_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationimage",
            name="storage_cost_per_year_usd_millicents",
            field=models.PositiveIntegerField(
                default=None,
                editable=False,
                help_text="The storage cost per year for this image in USD Cents, excluding Tax",
                null=True,
            ),
        ),
    ]
