# Generated by Django 4.1.13 on 2023-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0020_workstationimage_size_in_registry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationimage",
            name="desired_gpu_type",
            field=models.CharField(
                choices=[
                    ("", "No GPU"),
                    ("A100", "NVIDIA A100 Tensor Core GPU"),
                    ("A10G", "NVIDIA A10G Tensor Core GPU"),
                    ("V100", "NVIDIA V100 Tensor Core GPU"),
                    ("K80", "NVIDIA K80 GPU"),
                    ("T4", "NVIDIA T4 Tensor Core GPU"),
                ],
                default="T4",
                help_text="If this image requires a GPU, what GPU type would it like to use?",
                max_length=4,
            ),
        ),
    ]
