# Generated by Django 4.1.13 on 2023-11-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workstations", "0020_workstationimage_size_in_registry_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationimage",
            name="desired_gpu_type",
            field=models.CharField(
                choices=[
                    ("A100", "A100"),
                    ("A10G", "A10G"),
                    ("V100", "V100"),
                    ("K80", "K80"),
                    ("T4", "T4"),
                ],
                default="T4",
                help_text="If this image requires a GPU, what GPU type would it like to use?",
                max_length=4,
            ),
        ),
    ]
