# Generated by Django 4.2.16 on 2024-10-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0022_remove_workstationimage_is_on_sagemaker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workstationimage",
            name="desired_gpu_type",
        ),
        migrations.RemoveField(
            model_name="workstationimage",
            name="requires_gpu",
        ),
        migrations.RemoveField(
            model_name="workstationimage",
            name="requires_memory_gb",
        ),
    ]
