# Generated by Django 4.2.20 on 2025-04-17 11:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0061_alter_question_overlay_segments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "workstations",
            "0023_remove_workstationimage_desired_gpu_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("duration", models.DurationField()),
                (
                    "interactive_algorithms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The interactive algorithms for which hardware has been initialized during the session.",
                        validators=[
                            grandchallenge.core.validators.JSONValidator(
                                schema={
                                    "$schema": "http://json-schema.org/draft-07/schema",
                                    "items": {
                                        "enum": ["uls23-baseline"],
                                        "type": "string",
                                    },
                                    "type": "array",
                                    "uniqueItems": True,
                                }
                            )
                        ],
                    ),
                ),
                (
                    "credits_consumed",
                    models.PositiveIntegerField(editable=False, null=True),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SessionCostReaderStudy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reader_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reader_studies.readerstudy",
                    ),
                ),
                (
                    "session_cost",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workstations.sessioncost",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sessioncost",
            name="reader_studies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reader studies accessed during session",
                related_name="session_costs",
                through="workstations.SessionCostReaderStudy",
                to="reader_studies.readerstudy",
            ),
        ),
        migrations.AddField(
            model_name="sessioncost",
            name="session",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_cost",
                to="workstations.session",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessioncostreaderstudy",
            constraint=models.UniqueConstraint(
                fields=("session_cost", "reader_study"),
                name="unique_session_cost_reader_study",
            ),
        ),
    ]
