# Generated by Django 4.2.20 on 2025-04-17 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "workstations",
            "0023_remove_workstationimage_desired_gpu_type_and_more",
        ),
    ]

    operations = []
