# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0025_workstationimage_is_archived"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="feedbackuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="workstation_user_id_f2985d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessiongroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="workstation_group_i_f49e3b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sessionuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="workstation_user_id_68a398_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workstationgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="workstation_group_i_ec13f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workstationimagegroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="workstation_group_i_92ae85_idx",
            ),
        ),
    ]
