# Generated by Django 4.2.21 on 2025-05-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstations",
            "0027_feedbackgroupobjectpermission_workstation_group_i_ac4715_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessioncostreaderstudy",
            name="reader_study",
        ),
        migrations.RemoveField(
            model_name="sessioncostreaderstudy",
            name="session_cost",
        ),
        migrations.DeleteModel(
            name="SessionCost",
        ),
        migrations.DeleteModel(
            name="SessionCostReaderStudy",
        ),
    ]
