# Generated by Django 4.2.21 on 2025-06-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstations",
            "0028_remove_sessioncostreaderstudy_reader_study_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalSession",
        ),
    ]
