# Generated by Django 4.2.26 on 2025-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0029_delete_historicalsession"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstation",
            name="logo_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="workstation",
            name="logo_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
    ]
