# Generated by Django 5.2.9 on 2025-12-09 15:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "uploads",
            "0009_useruploadgroupobjectpermission_uploads_use_group_i_53998e_idx",
        ),
        ("workstations", "0033_alter_workstation_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationimage",
            name="api_method",
            field=models.CharField(
                choices=[("exec", "Exec"), ("invoke", "Invoke")],
                default="exec",
                editable=False,
                max_length=6,
            ),
        ),
        migrations.AddConstraint(
            model_name="workstationimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("api_method__in", ["exec", "invoke"])),
                name="workstations_workstationimage_api_method_in_choices",
            ),
        ),
    ]
