# Generated by Django 5.2.11 on 2026-02-19 09:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstations",
            "0035_remove_workstationimage_storage_cost_per_year_usd_millicents",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="host_address",
            field=models.GenericIPAddressField(
                editable=False,
                help_text="The IP address of the host this session is running on",
                null=True,
                protocol="IPv4",
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="http_port",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="The mapped port for http traffic on the host",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(32768),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="websocket_port",
            field=models.PositiveIntegerField(
                editable=False,
                help_text="The mapped port for websocket traffic on the host",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(32768),
                    django.core.validators.MaxValueValidator(65535),
                ],
            ),
        ),
    ]
