# Generated by Django 5.2.11 on 2026-02-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstations",
            "0036_session_host_address_session_http_port_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workstationimage",
            name="http_port",
        ),
        migrations.RemoveField(
            model_name="workstationimage",
            name="websocket_port",
        ),
    ]
