# Generated by Django 5.2.11 on 2026-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0037_alter_workstationimage_http_port_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="task_arn",
            field=models.CharField(default="", editable=False, max_length=128),
        ),
        migrations.AlterField(
            model_name="session",
            name="logs",
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
