# Generated by Django 5.2.11 on 2026-02-26 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0038_session_task_arn_alter_session_logs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="logs",
        ),
        migrations.RemoveField(
            model_name="workstationimage",
            name="http_port",
        ),
        migrations.RemoveField(
            model_name="workstationimage",
            name="websocket_port",
        ),
    ]
