# Generated by Django 5.2.15 on 2026-06-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0039_remove_session_logs_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="auth_token",
        ),
        migrations.AddField(
            model_name="session",
            name="claimed_at",
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
