# Generated by Django 5.2.15 on 2026-06-18 09:05

from django.db import migrations
from django.db.models import F


def set_existing_claimed_at(apps, schema_editor):
    Session = apps.get_model("workstations", "Session")  # noqa: N806
    Session.objects.filter(claimed_at=None).update(claimed_at=F("created"))


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0040_remove_session_auth_token_session_claimed_at"),
    ]

    operations = [
        migrations.RunPython(set_existing_claimed_at, elidable=True),
    ]
