# Generated by Django 5.2.15 on 2026-06-18 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0041_auto_20260618_0905"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="session",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("creator__isnull", True),
                    ("claimed_at__isnull", False),
                    _connector="OR",
                ),
                name="creator_requires_claimed_at",
            ),
        ),
    ]
