# Generated by Django 5.2.15 on 2026-06-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0042_session_creator_requires_claimed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Started"),
                    (2, "Running"),
                    (3, "Failed"),
                    (4, "Stopped"),
                    (5, "Expired"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="user_finished",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
