# Generated by Django 5.2.15 on 2026-06-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstations",
            "0043_alter_session_status_alter_session_user_finished",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="user_finished",
        ),
    ]
