# Generated by Django 5.2.16 on 2026-08-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "workstation_configs",
            "0033_lookuptable_workstation_configs_lookuptable_unique_slug_and_more",
        ),
        ("workstations", "0044_remove_session_user_finished"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="workstation",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="workstations_workstation_unique_slug"
            ),
        ),
    ]
