# Generated by Django 3.1.9 on 2021-05-18 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("actstream", "0003_add_follow_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.ForeignKey(
                        help_text="which actions is associated with this notification?",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="actstream.action",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="which user does this notification correspond to?",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
