# Generated by Django 3.1.6 on 2021-03-31 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receive_notification_emails",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to receive email updates about notifications",
                    ),
                ),
                (
                    "email_last_sent_at",
                    models.DateTimeField(
                        default=None, null=True, editable=False
                    ),
                ),
                (
                    "has_notifications",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "notifications_last_read_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
