# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0005_followgroupobjectpermission_followuserobjectpermission_notificationgroupobjectpermission_notificatio",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="followuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="notificatio_user_id_094079_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="notificatio_user_id_78188c_idx",
            ),
        ),
    ]
