# Generated by Django 4.2.16 on 2024-11-19 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "notifications",
            "0005_followgroupobjectpermission_followuserobjectpermission_notificationgroupobjectpermission_notificatio",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ("-created",)},
        ),
    ]
