# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0006_followuserobjectpermission_notificatio_user_id_094079_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="followgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="notificatio_group_i_cc45cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="notificatio_group_i_be2186_idx",
            ),
        ),
    ]
