# Generated by Django 4.2.26 on 2025-11-13 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_migrate_forum_follows_and_notifications"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("GENERIC", "Generic"),
                    ("FORUM-POST", "Forum post"),
                    ("FORUM-REPLY", "Forum post reply"),
                    ("ACCESS-REQUEST", "Access request"),
                    ("REQUEST-UPDATE", "Request update"),
                    ("NEW-ADMIN", "New admin"),
                    ("EVALUATION-STATUS", "Evaluation status update"),
                    ("MISSING-METHOD", "Missing method"),
                    ("JOB-STATUS", "Job status update"),
                    ("IMAGE-IMPORT", "Image import status update"),
                    ("DICOM-IMAGE-IMPORT", "DICOM image import status update"),
                    ("FILE-COPY", "Validation failed while copying file"),
                    (
                        "CIV-VALIDATION",
                        "Component Interface Value validation failed",
                    ),
                ],
                default="GENERIC",
                help_text="Of what type is this notification?",
                max_length=20,
            ),
        ),
    ]
