x-postgres-env: &postgres-env
    POSTGRES_PASSWORD: secretpassword
    POSTGRES_USER: grandchallenge
    POSTGRES_DB: grandchallenge

x-s3-env: &s3-env
    AWS_ACCESS_KEY_ID: s3admin
    AWS_SECRET_ACCESS_KEY: s3admin
    AWS_S3_ENDPOINT_URL: http://s3.localhost:8333

x-django-env: &django-env
    DEBUG: "true"
    COMPRESS_OFFLINE: "false"
    PYTHONDONTWRITEBYTECODE: 1
    SITE_SERVER_PORT: 8000
    DEFAULT_SCHEME: "http"
    SECURE_SSL_REDIRECT: "false"
    CSRF_COOKIE_SECURE: "false"
    SESSION_COOKIE_SECURE: "false"
    REMAP_SIGTERM: "SIGQUIT"
    AWS_S3_URL_PROTOCOL: "http:"
    PROTECTED_S3_CUSTOM_DOMAIN: "gc.localhost:8000/media"
    COMPONENTS_REGISTRY_INSECURE: "true"
    COMPONENTS_DEFAULT_BACKEND: "tests.components_tests.resources.backends.IOCopyExecutor"
    CSP_REPORT_ONLY: "true"
    LAMBDA_TASKS_LOCAL_WORKERS: 2

services:
    postgres:
        image: postgres:16
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            <<: [*postgres-env]
        tmpfs:
            - /var/lib/postgresql/data/
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "grandchallenge"]
            interval: 10s
            timeout: 5s
            retries: 5
        restart: always

    s3.localhost:
        image: chrislusf/seaweedfs
        ports:
            - "127.0.0.1:8333:8333"
        environment:
            <<: [*s3-env]
        command: "mini"
        restart: always

    gc.localhost:
        image: public.ecr.aws/diag-nijmegen/grand-challenge/web-test:latest
        ports:
            - "127.0.0.1:8000:8000"
        environment:
            <<: [*postgres-env, *s3-env, *django-env]
        # Use werkzeug debugger in dev, this should never be used in production!
        # https://django-extensions.readthedocs.io/en/latest/runserver_plus.html
        command: >-
            python manage.py runserver_plus 0.0.0.0:8000
        restart: always
        depends_on:
            postgres:
                condition: service_healthy
            s3.localhost:
                condition: service_started
            redis:
                condition: service_started
            registry:
                condition: service_started
        volumes:
            # Bind the app directory for live reloading in development
            - type: bind
              source: ./app
              target: /app/

    redis:
        image: redis:6
        ports:
            - "127.0.0.1:6379:6379"
        command: redis-server --appendonly yes
        restart: always

    celery_worker:
        image: public.ecr.aws/diag-nijmegen/grand-challenge/web-test:latest
        environment:
            <<: [*postgres-env, *s3-env, *django-env]
        restart: always
        command: watchfiles --filter python "celery --app config worker --loglevel info --concurrency 1 --pool prefork --queues acks-late-2xlarge,acks-late-2xlarge-delay,acks-late-micro-short,acks-late-micro-short-delay" /app
        scale: 1
        hostname: "celery-worker-evaluation"
        depends_on:
            postgres:
                condition: service_healthy
            s3.localhost:
                condition: service_started
            redis:
                condition: service_started
            registry:
                condition: service_started
        volumes:
            # Bind the app directory for live reloading in development
            - type: bind
              source: ./app
              target: /app/
            # The pytest_cache is only needed for testing
            - type: volume
              source: pytest-cache
              target: /tmp/.pytest_cache

    celery_beat:
        image: public.ecr.aws/diag-nijmegen/grand-challenge/web-test:latest
        environment:
            <<: [*postgres-env, *s3-env, *django-env]
        restart: always
        command: >-
            bash -c "
            rm -f /tmp/celerybeat.pid
            && celery --app config beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=\"/tmp/celerybeat.pid\"
            "
        depends_on:
            postgres:
                condition: service_healthy
            redis:
                condition: service_started

    registry:
        image: registry:2
        ports:
            - "127.0.0.1:5000:5000"
        environment:
            REGISTRY_STORAGE_DELETE_ENABLED: "true"

networks:
    default:
        name: "grand-challengeorg_default"

volumes:
    pytest-cache:
