# Generated by Django 2.1.7 on 2019-02-21 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import grandchallenge.eyra_evaluators.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='', help_text='Description of this Evaluator in markdown.')),
                ('container', models.FileField(blank=True, upload_to=grandchallenge.eyra_evaluators.models.get_container_file_name)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
