# Generated by Django 3.2.13 on 2022-06-02 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={"ordering": ["pk"]},
        ),
    ]
