# Generated by Django 4.2.11 on 2024-04-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_rawemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawemail",
            name="errored",
            field=models.BooleanField(default=False),
        ),
    ]
