# Generated by Django 5.2.14 on 2026-06-01 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0004_rawemail_errored"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("QUEUED", "Queued"),
                    ("SUCCEEDED", "Succeeded"),
                    ("FAILED", "Failed"),
                ],
                default="INITIALIZED",
                max_length=11,
            ),
        ),
        migrations.AddConstraint(
            model_name="rawemail",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["INITIALIZED", "QUEUED", "SUCCEEDED", "FAILED"],
                    )
                ),
                name="emails_rawemail_status_in_choices",
            ),
        ),
    ]
