# Generated by Django 5.2.14 on 2026-06-01 07:30

from django.db import migrations


def set_status(apps, _schema_editor):
    RawEmail = apps.get_model("emails", "RawEmail")  # noqa: N806

    RawEmail.objects.filter(sent_at__isnull=False).update(status="SUCCEEDED")
    RawEmail.objects.filter(errored=True).update(status="FAILED")

    Email = apps.get_model("emails", "Email")  # noqa: N806

    Email.objects.filter(sent=True).update(status="SUCCEEDED")


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0005_rawemail_status_and_more"),
    ]

    operations = [
        migrations.RunPython(set_status, elidable=True),
    ]
