# Generated by Django 5.2.14 on 2026-06-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0006_auto_20260601_0730"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawemail",
            name="errored",
        ),
        migrations.RemoveField(
            model_name="rawemail",
            name="sent_at",
        ),
        migrations.AddIndex(
            model_name="rawemail",
            index=models.Index(
                fields=["status"], name="emails_rawe_status_18799c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rawemail",
            index=models.Index(
                fields=["-created"], name="emails_rawe_created_0fb3c2_idx"
            ),
        ),
    ]
