# Generated by Django 2.1.8 on 2019-05-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("annotations", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="booleanclassificationannotation",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="coordinatelistannotation",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="etdrsgridannotation",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="integerclassificationannotation",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="landmarkannotationset",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="measurementannotation",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="polygonannotationset",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="singlelandmarkannotation",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
        migrations.AlterModelOptions(
            name="singlepolygonannotation",
            options={"get_latest_by": "created", "ordering": ["-created"]},
        ),
    ]
