# Generated by Django 2.1.4 on 2018-12-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_auto_20181210_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanclassificationannotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Image'),
        ),
        migrations.AlterField(
            model_name='coordinatelistannotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Image'),
        ),
        migrations.AlterField(
            model_name='etdrsgridannotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Image'),
        ),
        migrations.AlterField(
            model_name='integerclassificationannotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Image'),
        ),
        migrations.AlterField(
            model_name='measurementannotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Image'),
        ),
        migrations.AlterField(
            model_name='polygonannotationset',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Image'),
        ),
        migrations.AlterField(
            model_name='singlelandmarkannotation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Image'),
        ),
    ]
