# Generated by Django 2.1.8 on 2019-06-03 12:08

import django.contrib.postgres.fields
from django.db import migrations, models

import grandchallenge.annotations.models


class Migration(migrations.Migration):

    dependencies = [("annotations", "0002_auto_20190510_1046")]

    operations = [
        migrations.AddField(
            model_name="singlepolygonannotation",
            name="x_axis_orientation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=grandchallenge.annotations.models.x_axis_orientation_default,
                size=3,
            ),
        ),
        migrations.AddField(
            model_name="singlepolygonannotation",
            name="y_axis_orientation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                default=grandchallenge.annotations.models.y_axis_orientation_default,
                size=3,
            ),
        ),
        migrations.AddField(
            model_name="singlepolygonannotation",
            name="z",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
