# Generated by Django 2.1.8 on 2019-06-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("annotations", "0002_auto_20190510_1046")]

    operations = [
        migrations.AddField(
            model_name="singlepolygonannotation",
            name="slice_index",
            field=models.PositiveIntegerField(blank=True, null=True),
        )
    ]
