# Generated by Django 2.2.3 on 2019-07-30 12:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("annotations", "0005_imagetextannotation")]

    operations = [
        migrations.AlterField(
            model_name="etdrsgridannotation",
            name="optic_disk",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                blank=True,
                default=list,
                size=2,
            ),
        )
    ]
