# Generated by Django 3.0.2 on 2020-03-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0006_auto_20190730_1234"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="singlepolygonannotation", name="x_axis_orientation",
        ),
        migrations.RemoveField(
            model_name="singlepolygonannotation", name="y_axis_orientation",
        ),
        migrations.AddField(
            model_name="singlepolygonannotation",
            name="interpolated",
            field=models.BooleanField(default=False),
        ),
    ]
