# Generated by Django 3.0.8 on 2020-08-05 16:03

import uuid

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0025_remove_rawimageuploadsession_algorithm_result"),
        ("annotations", "0007_auto_20200317_1054"),
    ]

    operations = [
        migrations.AddField(
            model_name="retinaimagepathologyannotation",
            name="rf_present",
            field=models.BooleanField(
                default=False,
                help_text="Are retinal pathologies present in this image?",
            ),
        ),
        migrations.AlterField(
            model_name="retinaimagepathologyannotation",
            name="amd_present",
            field=models.BooleanField(
                default=False,
                help_text="Is Age-related Macular Degeneration present in this image?",
            ),
        ),
        migrations.AlterField(
            model_name="retinaimagepathologyannotation",
            name="cysts_present",
            field=models.BooleanField(
                default=False, help_text="Are cysts present in this image?"
            ),
        ),
        migrations.AlterField(
            model_name="retinaimagepathologyannotation",
            name="dr_present",
            field=models.BooleanField(
                default=False,
                help_text="Is Diabetic Retinopathy present in this image?",
            ),
        ),
        migrations.CreateModel(
            name="OctRetinaImagePathologyAnnotation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "macular",
                    models.BooleanField(
                        default=False,
                        help_text="Are pathologies present in macular OCT?",
                    ),
                ),
                (
                    "myopia",
                    models.BooleanField(
                        default=False,
                        help_text="Are myopia related pathologies present?",
                    ),
                ),
                (
                    "optic_disc",
                    models.BooleanField(
                        default=False,
                        help_text="Are pathologies present in optic disc OCT?",
                    ),
                ),
                (
                    "other",
                    models.BooleanField(
                        default=False,
                        help_text="Are other pathologies present in this image?",
                    ),
                ),
                (
                    "layers",
                    models.BooleanField(
                        default=False,
                        help_text="Are retinal layers annotated?",
                    ),
                ),
                (
                    "grader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.Image",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "get_latest_by": "created",
                "abstract": False,
            },
        ),
    ]
