# Generated by Django 3.0.9 on 2020-09-11 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("annotations", "0008_auto_20200805_1603"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="retinaimagepathologyannotation", name="amd_present",
        ),
        migrations.RemoveField(
            model_name="retinaimagepathologyannotation", name="cysts_present",
        ),
        migrations.RemoveField(
            model_name="retinaimagepathologyannotation", name="dr_present",
        ),
    ]
