# Generated by Django 2.2.2 on 2019-09-03 13:03

import comic.eyra_data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_data', '0007_auto_20190621_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datafile',
            name='format',
        ),
        migrations.AlterField(
            model_name='datafile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment of creation'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Creator of this DataFile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='file',
            field=models.FileField(blank=True, help_text='This files contents (the bits)', null=True, upload_to=comic.eyra_data.models.get_data_file_name),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Moment of last modification'),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='name',
            field=models.CharField(help_text='Name of this file', max_length=50),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='sha',
            field=models.CharField(blank=True, help_text='Reserved for SHA checksum (currently not used)', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='The size of this file in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='datafile',
            name='type',
            field=models.ForeignKey(help_text='The type of this file', on_delete=django.db.models.deletion.CASCADE, to='eyra_data.DataType'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='banner_image_alttext',
            field=models.CharField(blank=True, help_text='alt attribute for image in DataSet details header', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='banner_image_url',
            field=models.CharField(default='https://www.staging.eyrabenchmark.net/static/media/logo.3fc4ddae.png', help_text='(wide) image used as a banner in DataSet detail page', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='card_image_alttext',
            field=models.CharField(blank=True, help_text='alt attribute for image in DataSet card component', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='card_image_url',
            field=models.CharField(default='https://www.staging.eyrabenchmark.net/static/media/logo.3fc4ddae.png', help_text='Image used in the DataSet card component', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment of creation'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Creator of this DataSet', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Moment of last modification'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(help_text='The name of this dataset', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='participant_data_files',
            field=models.ManyToManyField(blank=True, help_text='Other DataFiles downloadable by a participant.', related_name='data_sets', to='eyra_data.DataFile'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='private_ground_truth_data_file',
            field=models.ForeignKey(blank=True, help_text="DataFile used as 'ground_truth' input in private evaluation container", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eyra_data.DataFile'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='private_test_data_file',
            field=models.ForeignKey(blank=True, help_text="DataFile used as 'test_data' input in private submission container", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eyra_data.DataFile'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='public_ground_truth_data_file',
            field=models.ForeignKey(blank=True, help_text="DataFile used as 'ground_truth' input in public evaluation container", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eyra_data.DataFile'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='public_test_data_file',
            field=models.ForeignKey(blank=True, help_text="DataFile used as 'test_data' input in public submission container", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='eyra_data.DataFile'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='related_datasets',
            field=models.ManyToManyField(blank=True, help_text='Other DataSets related to this one', related_name='related_data_sets', to='eyra_data.DataSet'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment of creation'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Moment of last modification'),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(help_text='Name of this type', max_length=40),
        ),
    ]
