# Generated by Django 4.2.21 on 2025-05-19 16:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "reader_studies",
            "0066_displaysetuserobjectpermission_reader_stud_user_id_eb81eb_idx_and_more",
        ),
        (
            "workstations",
            "0027_feedbackgroupobjectpermission_workstation_group_i_ac4715_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionUtilization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("duration", models.DurationField()),
                (
                    "interactive_algorithms",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="The interactive algorithms for which hardware has been initialized during the session.",
                        validators=[
                            grandchallenge.core.validators.JSONValidator(
                                schema={
                                    "$schema": "http://json-schema.org/draft-07/schema",
                                    "items": {
                                        "enum": ["uls23-baseline"],
                                        "type": "string",
                                    },
                                    "type": "array",
                                    "uniqueItems": True,
                                }
                            )
                        ],
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SessionUtilizationReaderStudy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reader_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reader_studies.readerstudy",
                    ),
                ),
                (
                    "session_utilization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utilization.sessionutilization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="sessionutilization",
            name="reader_studies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reader studies accessed during session",
                related_name="session_utilizations",
                through="utilization.SessionUtilizationReaderStudy",
                to="reader_studies.readerstudy",
            ),
        ),
        migrations.AddField(
            model_name="sessionutilization",
            name="session",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_utilization",
                to="workstations.session",
            ),
        ),
        migrations.AddConstraint(
            model_name="sessionutilizationreaderstudy",
            constraint=models.UniqueConstraint(
                fields=("session_utilization", "reader_study"),
                name="unique_session_utilization_reader_study",
            ),
        ),
    ]
