# Generated by Django 4.2.21 on 2025-06-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("utilization", "0003_auto_20250520_1012"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evaluationutilization",
            index=models.Index(
                fields=["-created"], name="utilization_created_c88254_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationutilization",
            index=models.Index(
                fields=["phase", "external_evaluation", "duration"],
                name="utilization_phase_i_f7c042_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobutilization",
            index=models.Index(
                fields=["-created"], name="utilization_created_3920ce_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobutilization",
            index=models.Index(
                fields=["creator", "algorithm"],
                name="utilization_creator_692c7c_idx",
            ),
        ),
    ]
