# Generated by Django 4.2.21 on 2025-06-10 11:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0053_challengeuserobjectpermission_challenges__user_id_7f9623_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evaluation", "0089_evaluation_use_warm_pool"),
        ("algorithms", "0077_job_use_warm_pool"),
        (
            "archives",
            "0022_archiveitemuserobjectpermission_archives_ar_user_id_13fbd3_idx_and_more",
        ),
        (
            "utilization",
            "0004_evaluationutilization_utilization_created_c88254_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="JobWarmPoolUtilization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("duration", models.DurationField(null=True)),
                (
                    "compute_cost_euro_millicents",
                    models.PositiveIntegerField(null=True),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="algorithms.algorithm",
                    ),
                ),
                (
                    "algorithm_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="algorithms.algorithmimage",
                    ),
                ),
                (
                    "archive",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="archives.archive",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.challenge",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_warm_pool_utilization",
                        to="algorithms.job",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="evaluation.phase",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_related_name": "job_warm_pool_utilizations",
                "indexes": [
                    models.Index(
                        fields=["-created"],
                        name="utilization_created_b7ca7b_idx",
                    )
                ],
            },
        ),
    ]
