# Generated by Django 5.2.13 on 2026-04-10 16:26

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0094_remove_endpoint_algorithm_interface_and_more"),
        ("reader_studies", "0076_readerstudyalgorithm_and_more"),
        ("utilization", "0005_jobwarmpoolutilization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EndpointUtilization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("duration", models.DurationField(null=True)),
                (
                    "compute_cost_euro_millicents",
                    models.PositiveIntegerField(null=True),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="algorithms.algorithm",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "endpoint",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="endpoint_utilization",
                        to="algorithms.endpoint",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EndpointUtilizationReaderStudy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "endpoint_utilization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utilization.endpointutilization",
                    ),
                ),
                (
                    "reader_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reader_studies.readerstudy",
                    ),
                ),
            ],
            options={
                "unique_together": {("endpoint_utilization", "reader_study")},
            },
        ),
        migrations.AddField(
            model_name="endpointutilization",
            name="reader_studies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Reader studies that used this endpoint",
                related_name="endpoint_utilizations",
                through="utilization.EndpointUtilizationReaderStudy",
                to="reader_studies.readerstudy",
            ),
        ),
        migrations.AddIndex(
            model_name="endpointutilization",
            index=models.Index(
                fields=["created"], name="utilization_created_7f12c0_idx"
            ),
        ),
    ]
