# Generated by Django 5.2.14 on 2026-06-02 10:51

import django.db.models.expressions
import django.db.models.functions.datetime
import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "utilization",
            "0006_endpointutilization_endpointutilizationreaderstudy_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="endpointutilization",
            name="credits_consumed",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        compute_cost_euro_millicents__isnull=True,
                        then=models.Value(0),
                    ),
                    default=django.db.models.functions.math.Ceil(
                        django.db.models.expressions.CombinedExpression(
                            models.F("compute_cost_euro_millicents"),
                            "/",
                            models.Value(1000.0),
                        )
                    ),
                    output_field=models.IntegerField(),
                ),
                output_field=models.IntegerField(),
            ),
        ),
        migrations.AddField(
            model_name="sessionutilization",
            name="credits_consumed",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.functions.math.Ceil(
                    django.db.models.expressions.CombinedExpression(
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.datetime.Extract(
                                models.F("duration"), lookup_name="epoch"
                            ),
                            "/",
                            models.Value(3600.0),
                        ),
                        "*",
                        models.Case(
                            models.When(
                                interactive_algorithms=models.Value("[]"),
                                then=models.Value(500),
                            ),
                            default=models.Value(1000),
                            output_field=models.IntegerField(),
                        ),
                    )
                ),
                output_field=models.IntegerField(),
            ),
        ),
    ]
