# Generated by Django 5.2.13 on 2026-05-08 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0012_migrate_invoice_expires_on"),
        (
            "utilization",
            "0007_endpointutilization_credits_consumed_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationutilization",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="jobutilization",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoices.invoice",
            ),
        ),
        migrations.AddField(
            model_name="jobwarmpoolutilization",
            name="invoice",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="invoices.invoice",
            ),
        ),
    ]
