# Generated by Django 4.2.23 on 2025-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum_attachments", "0002_auto_20181103_1404"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
