# Generated by Django 2.1.3 on 2018-12-10 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='octobsregistration',
            name='obs_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obs_image', to='cases.Image'),
        ),
        migrations.AddField(
            model_name='octobsregistration',
            name='oct_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oct_image', to='cases.Image'),
        ),
        migrations.AlterUniqueTogether(
            name='octobsregistration',
            unique_together={('obs_image', 'oct_series')},
        ),
    ]
