# Generated by Django 4.2.9 on 2024-01-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OctObsRegistration",
        ),
    ]
