# Generated by Django 2.1.4 on 2018-12-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20181210_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='octobsregistration',
            name='obs_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obs_image', to='cases.Image'),
        ),
        migrations.AlterField(
            model_name='octobsregistration',
            name='oct_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oct_image', to='cases.Image'),
        ),
    ]
