# Generated by Django 2.2.3 on 2019-07-22 10:58

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import grandchallenge.core.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0011_auto_20190314_1453"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaderStudy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "hanging_list",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True,
                        default=list,
                        validators=[
                            grandchallenge.core.validators.JSONSchemaValidator(
                                schema={
                                    "$schema": "http://json-schema.org/draft-06/schema#",
                                    "definitions": {},
                                    "items": {
                                        "$id": "#/items",
                                        "additionalProperties": False,
                                        "properties": {
                                            "main": {
                                                "$id": "#/items/properties/main",
                                                "default": "",
                                                "examples": ["im1.mhd"],
                                                "pattern": "^(.*)$",
                                                "title": "The Main Schema",
                                                "type": "string",
                                            },
                                            "secondary": {
                                                "$id": "#/items/properties/secondary",
                                                "default": "",
                                                "examples": ["im2.mhd"],
                                                "pattern": "^(.*)$",
                                                "title": "The Secondary Schema",
                                                "type": "string",
                                            },
                                        },
                                        "required": ["main"],
                                        "title": "The Items Schema",
                                        "type": "object",
                                    },
                                    "title": "The Hanging List Schema",
                                    "type": "array",
                                }
                            )
                        ],
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="readerstudies", to="cases.Image"
                    ),
                ),
                (
                    "readers",
                    models.ManyToManyField(
                        related_name="readerstudies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "reader studies",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("question_text", models.TextField()),
                (
                    "answer_type",
                    models.CharField(
                        choices=[
                            ("B", "Bool"),
                            ("S", "String"),
                            ("F", "Float"),
                        ],
                        max_length=1,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "reader_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="reader_studies.ReaderStudy",
                    ),
                ),
            ],
            options={"ordering": ("order", "created")},
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("answer", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="answers", to="cases.Image"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reader_studies.Question",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
