# Generated by Django 2.2.4 on 2019-09-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reader_studies", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="question",
            name="help_text",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="required",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="readerstudy",
            name="shuffle_hanging_list",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("STXT", "Single line text"),
                    ("MTXT", "Multi line text"),
                    ("BOOL", "Bool"),
                    ("HEAD", "Heading"),
                    ("2DBB", "2D bounding box"),
                    ("DIST", "Distance measurement"),
                ],
                default="STXT",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
