# Generated by Django 2.2.4 on 2019-09-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("reader_studies", "0002_auto_20190901_1725")]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("STXT", "Single line text"),
                    ("MTXT", "Multi line text"),
                    ("BOOL", "Bool"),
                    ("HEAD", "Heading"),
                    ("2DBB", "2D bounding box"),
                    ("DIST", "Distance measurement"),
                    ("MDIS", "Multiple distance measurements"),
                ],
                default="STXT",
                max_length=4,
            ),
        )
    ]
