# Generated by Django 3.1.1 on 2020-12-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0001_initial"),
        ("reader_studies", "0002_auto_20201214_0939"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="The organizations associated with this reader study",
                related_name="readerstudies",
                to="organizations.Organization",
            ),
        )
    ]
