# Generated by Django 2.2.9 on 2020-01-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0005_readerstudy_workstation_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="is_ground_truth",
            field=models.BooleanField(default=False),
        ),
    ]
