# Generated by Django 2.2.9 on 2020-01-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0006_answer_is_ground_truth"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="scoring_function",
            field=models.CharField(
                choices=[("ACC", "Accuracy score")],
                default="ACC",
                max_length=3,
            ),
        ),
    ]
