# Generated by Django 3.0.2 on 2020-03-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0009_auto_20200319_0752"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="help_text_markdown",
            field=models.TextField(blank=True),
        ),
    ]
