# Generated by Django 3.0.2 on 2020-03-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0011_auto_20200323_1152"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="is_educational",
            field=models.BooleanField(
                default=False,
                help_text="If checked, readers get the option to verify their answers against the uploaded ground truth. This also means that the uploaded ground truth will be readily available to the readers.",
            ),
        ),
    ]
