# Generated by Django 3.1.11 on 2021-07-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0004_publication_citation"),
        ("reader_studies", "0011_auto_20210601_0802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readerstudy",
            name="publications",
            field=models.ManyToManyField(
                blank=True,
                help_text='The publications associated with this reader study. If your publication is missing click <a href="https://gc.localhost/publications/create/">here</a> to add it and then refresh this page.',
                to="publications.Publication",
            ),
        ),
    ]
