# Generated by Django 3.1.13 on 2021-09-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0005_componentinterface_schema"),
        ("reader_studies", "0012_auto_20210825_1346"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="civs",
            field=models.ManyToManyField(
                related_name="answers", to="components.ComponentInterfaceValue"
            ),
        ),
        migrations.AddField(
            model_name="readerstudy",
            name="civs",
            field=models.ManyToManyField(
                related_name="readerstudies",
                to="components.ComponentInterfaceValue",
            ),
        ),
    ]
