# Generated by Django 3.2.9 on 2021-12-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("reader_studies", "0012_auto_20210825_1346")]

    operations = [
        migrations.AlterModelOptions(
            name="answer", options={"ordering": ("created",)}
        ),
        migrations.AlterField(
            model_name="answer",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
