# Generated by Django 3.0.2 on 2020-03-27 14:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import grandchallenge.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0013_auto_20200327_0836"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="case_text",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=dict,
                validators=[
                    grandchallenge.core.validators.JSONSchemaValidator(
                        schema={
                            "additionalProperties": {"type": "string"},
                            "properties": {},
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
    ]
