# Generated by Django 3.2.10 on 2021-12-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0013_auto_20211206_0925"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="require_user_review",
            field=models.BooleanField(
                default=True,
                help_text="If ticked, new users need to be approved by an editor before they can participate in the reader study. If not ticked, new users are allowed access immediately.",
            ),
        ),
    ]
