# Generated by Django 3.2.10 on 2022-01-17 13:05
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0008_alter_componentinterfacevalue_file"),
        ("reader_studies", "0014_readerstudy_roll_over_answers_for_n_cases"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplaySet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "reader_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="display_sets",
                        to="reader_studies.readerstudy",
                    ),
                ),
                (
                    "values",
                    models.ManyToManyField(
                        blank=True,
                        related_name="displays_sets",
                        to="components.ComponentInterfaceValue",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
