# Generated by Django 3.2.10 on 2022-01-21 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0014_displayset"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="display_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="answers",
                to="reader_studies.displayset",
            ),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="display_set",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="reader_studies.displayset",
            ),
        ),
    ]
