# Generated by Django 3.0.2 on 2020-04-02 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reader_studies", "0014_readerstudy_case_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="Should this reader study be visible to all users on the overview page? This does not grant all users permission to read this study. Users will still need to be added to the study's readers group in order to do that.",
            ),
        ),
        migrations.CreateModel(
            name="ReaderStudyPermissionRequest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("changed", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PEND", "Pending"),
                            ("ACPT", "Accepted"),
                            ("RJCT", "Rejected"),
                        ],
                        default="PEND",
                        max_length=4,
                    ),
                ),
                (
                    "rejection_text",
                    models.TextField(
                        blank=True,
                        help_text="The text that will be sent to the user with the reason for their rejection.",
                    ),
                ),
                (
                    "reader_study",
                    models.ForeignKey(
                        help_text="To which reader study has the user requested access?",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reader_studies.ReaderStudy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="which user requested to participate?",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("reader_study", "user")},
            },
        ),
    ]
