# Generated by Django 3.2.10 on 2022-01-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0015_auto_20220121_1031"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayset",
            name="display_ports",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="displayset",
            name="order",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
