# Generated by Django 3.2.10 on 2022-01-31 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0016_auto_20220131_0945"),
    ]

    operations = [
        migrations.RemoveField(model_name="displayset", name="order",),
    ]
