# Generated by Django 3.0.2 on 2020-04-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0016_assign_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="allow_case_navigation",
            field=models.BooleanField(
                default=False,
                help_text="If true, readers are allowed to navigate back and forth between cases in this reader study.",
            ),
        ),
        migrations.AlterField(
            model_name="readerstudy",
            name="allow_answer_modification",
            field=models.BooleanField(
                default=False,
                help_text="If true, readers are allowed to modify their answers for a case by navigating back to previous cases. 'allow_case_browsing' must be checked with this as well.",
            ),
        ),
    ]
