# Generated by Django 3.2.10 on 2022-02-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0017_remove_displayset_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="image_port_mapping",
            field=models.JSONField(null=True),
        ),
    ]
