# Generated by Django 3.0.5 on 2020-04-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0018_auto_20200611_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalanswer",
            name="explanation",
            field=models.TextField(blank=True),
        ),
    ]
