# Generated by Django 3.2.10 on 2022-02-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0018_readerstudy_image_port_mapping"),
    ]

    operations = [
        migrations.RemoveField(model_name="displayset", name="display_ports",),
    ]
