# Generated by Django 3.0.8 on 2020-07-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0019_auto_20200414_0728"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="historicalanswer",
            name="explanation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
