# Generated by Django 3.2.10 on 2022-02-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0019_remove_displayset_display_ports"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="use_display_sets",
            field=models.BooleanField(default=False),
        ),
    ]
