# Generated by Django 3.2.12 on 2022-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0021_readerstudy_view_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readerstudy",
            name="use_display_sets",
            field=models.BooleanField(default=True),
        ),
    ]
