# Generated by Django 3.2.12 on 2022-04-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader_studies', '0022_alter_readerstudy_use_display_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_time',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='historicalanswer',
            name='answer_time',
            field=models.FloatField(default=None, null=True),
        ),
    ]
