# Generated by Django 3.2.13 on 2022-04-14 15:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reader_studies", "0022_alter_readerstudy_use_display_sets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readerstudy",
            name="use_display_sets",
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="answer",
            unique_together={
                ("creator", "display_set", "question", "is_ground_truth")
            },
        ),
    ]
