# Generated by Django 3.1.1 on 2020-10-20 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0022_auto_20201001_0758"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="readerstudy",
            options={
                "ordering": ("created",),
                "permissions": [("read_readerstudy", "Can read reader study")],
                "verbose_name_plural": "reader studies",
            },
        ),
    ]
