# Generated by Django 3.2.13 on 2022-05-18 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0009_alter_componentinterface_kind"),
        ("reader_studies", "0028_auto_20220517_0740"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="interface",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="components.componentinterface",
            ),
        ),
    ]
