# Generated by Django 3.2.13 on 2022-06-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0031_alter_question_interface"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readerstudy",
            name="allow_answer_modification",
            field=models.BooleanField(
                default=False,
                help_text="If true, readers are allowed to modify their answers for a case by navigating back to previous cases. 'Allow case navigation' must be checked as well to enable this setting.",
            ),
        ),
    ]
