# Generated by Django 3.2.18 on 2023-02-22 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0037_auto_20230104_1221"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerWidget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("ACCEPT_REJECT", "Accept/Reject Findings Widget")
                        ],
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcceptRejectFindingsWidget",
            fields=[
                (
                    "answerwidget_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="reader_studies.answerwidget",
                    ),
                ),
            ],
            bases=("reader_studies.answerwidget",),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_widget",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="reader_studies.answerwidget",
            ),
        ),
    ]
