# Generated by Django 3.2.18 on 2023-02-24 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0037_auto_20230104_1221"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionWidget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("ACCEPT_REJECT", "Accept/Reject Findings")],
                        max_length=13,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="widget",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="reader_studies.questionwidget",
            ),
        ),
    ]
