# Generated by Django 3.2.18 on 2023-03-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0038_questionwidget"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="widget",
            field=models.CharField(
                blank=True,
                choices=[("ACCEPT_REJECT", "Accept/Reject Findings")],
                max_length=13,
            ),
        ),
        migrations.DeleteModel(
            name="QuestionWidget",
        ),
    ]
