# Generated by Django 3.2.18 on 2023-03-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0039_auto_20230302_1427"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_max_value",
            field=models.SmallIntegerField(
                blank=True,
                default=None,
                help_text="Maximum value for answers of type Number. Can only be set in combination with the 'Number input' widget.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_min_value",
            field=models.SmallIntegerField(
                blank=True,
                default=None,
                help_text="Minimum value for answers of type Number. Can only be set in combination with the 'Number input' widget.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_step_size",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                default=None,
                help_text="Step size for answers of type Number. Defaults to 1, allowing only integer values. Can only be set in combination with the 'Number input' widget.",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="widget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCEPT_REJECT", "Accept/Reject Findings"),
                    ("NUMBER_INPUT", "Number input"),
                ],
                max_length=13,
            ),
        ),
    ]
