# Generated by Django 4.1.9 on 2023-06-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reader_studies",
            "0041_alter_answer_answer_alter_historicalanswer_answer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="widget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCEPT_REJECT", "Accept/Reject Findings"),
                    ("NUMBER_INPUT", "Number input"),
                    ("TEXT_INPUT", "Text Input"),
                    ("TEXT_AREA", "Text Area"),
                    ("SLCT_M", "Select Multiple"),
                    ("CHCKB_SLCT_M", "Checkbox Select Multiple"),
                ],
                max_length=13,
            ),
        ),
    ]
