# Generated by Django 4.1.9 on 2023-06-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0042_alter_question_widget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayset",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
