# Generated by Django 4.1.9 on 2023-06-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0043_alter_displayset_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="widget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCEPT_REJECT", "Accept/Reject Findings"),
                    ("NUMBER_INPUT", "Number input"),
                    ("TEXT_INPUT", "Text Input"),
                    ("TEXT_AREA", "Text Area"),
                    ("SELECT_MULTIPLE", "Select Multiple"),
                    ("CHECKBOX_SELECT_MULTIPLE", "Checkbox Select Multiple"),
                    ("SELECT", "Select"),
                    ("RADIO_SELECT", "Radio Select"),
                ],
                max_length=24,
            ),
        ),
    ]
