# Generated by Django 4.1.10 on 2023-08-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanging_protocols', '0010_alter_hangingprotocol_json'),
        ('reader_studies', '0046_alter_question_overlay_segments'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalProtocolsReaderStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hanging_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanging_protocols.hangingprotocol')),
                ('reader_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reader_studies.readerstudy')),
            ],
        ),
        migrations.AddField(
            model_name='readerstudy',
            name='optional_hanging_protocols',
            field=models.ManyToManyField(blank=True, help_text='Optional alternative hanging protocols for this reader study', related_name='optional_of_reader_study', through='reader_studies.OptionalProtocolsReaderStudy', to='hanging_protocols.hangingprotocol'),
        ),
    ]
