# Generated by Django 4.2.9 on 2024-01-18 16:17

import django.core.validators
from django.db import migrations

import grandchallenge.core.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "reader_studies",
            "0049_alter_readerstudy_roll_over_answers_for_n_cases",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="default_annotation_color",
            field=grandchallenge.core.fields.HexColorField(
                blank=True,
                default="",
                help_text="Default color for displaying and creating annotations for this question",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="This is an invalid color code. It must be an HTML hexadecimal color code e.g. #000000",
                        regex="^#[a-fA-F0-9]{6}$",
                    ),
                    django.core.validators.RegexValidator(
                        message="This is an invalid color code. It must be an HTML hexadecimal color code e.g. #000000",
                        regex="^#[a-fA-F0-9]{6}$",
                    ),
                ],
            ),
        ),
    ]
