# Generated by Django 4.2.9 on 2024-01-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0050_question_default_annotation_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("STXT", "Single line text"),
                    ("MTXT", "Multi line text"),
                    ("BOOL", "Bool"),
                    ("NUMB", "Number"),
                    ("HEAD", "Heading"),
                    ("2DBB", "2D bounding box"),
                    ("M2DB", "Multiple 2D bounding boxes"),
                    ("DIST", "Distance measurement"),
                    ("MDIS", "Multiple distance measurements"),
                    ("POIN", "Point"),
                    ("MPOI", "Multiple points"),
                    ("POLY", "Polygon"),
                    ("MPOL", "Multiple polygons"),
                    ("CHOI", "Choice"),
                    ("MCHO", "Multiple choice"),
                    ("MCHD", "Multiple choice dropdown"),
                    ("MASK", "Mask"),
                    ("LINE", "Line"),
                    ("MLIN", "Multiple lines"),
                    ("ANGL", "Angle"),
                    ("MANG", "Multiple angles"),
                    ("ELLI", "Ellipse"),
                    ("MELL", "Multiple ellipses"),
                    ("3ANG", "Three-point angle"),
                    ("M3AN", "Multiple three-point angles"),
                ],
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="widget",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACCEPT_REJECT", "Accept/Reject Findings"),
                    ("NUMBER_INPUT", "Number Input"),
                    ("NUMBER_RANGE", "Number Range"),
                    ("TEXT_INPUT", "Text Input"),
                    ("TEXT_AREA", "Text Area"),
                    ("SELECT_MULTIPLE", "Select Multiple"),
                    ("CHECKBOX_SELECT_MULTIPLE", "Checkbox Select Multiple"),
                    ("SELECT", "Select"),
                    ("RADIO_SELECT", "Radio Select"),
                ],
                max_length=24,
            ),
        ),
    ]
