# Generated by Django 4.2.9 on 2024-01-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reader_studies",
            "0051_alter_answer_answer_alter_historicalanswer_answer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Text"),
                    ("BOOL", "Bool"),
                    ("NUMB", "Number"),
                    ("HEAD", "Heading"),
                    ("2DBB", "2D bounding box"),
                    ("M2DB", "Multiple 2D bounding boxes"),
                    ("DIST", "Distance measurement"),
                    ("MDIS", "Multiple distance measurements"),
                    ("POIN", "Point"),
                    ("MPOI", "Multiple points"),
                    ("POLY", "Polygon"),
                    ("MPOL", "Multiple polygons"),
                    ("CHOI", "Choice"),
                    ("MCHO", "Multiple choice"),
                    ("MASK", "Mask"),
                    ("LINE", "Line"),
                    ("MLIN", "Multiple lines"),
                    ("ANGL", "Angle"),
                    ("MANG", "Multiple angles"),
                    ("ELLI", "Ellipse"),
                    ("MELL", "Multiple ellipses"),
                    ("3ANG", "Three-point angle"),
                    ("M3AN", "Multiple three-point angles"),
                ],
                max_length=4,
            ),
        ),
    ]
