# Generated by Django 4.2.9 on 2024-01-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0052_alter_question_answer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="instant_verification",
            field=models.BooleanField(
                default=False,
                help_text="In an educational reader study, enabling this setting will allow the user to go through the reader study faster. The 'Save and continue' button will be replaced by a 'Verify and continue' button which will show the answer verification pop up and allow the user to save and go to the next case upon dismissal.",
            ),
        ),
    ]
