# Generated by Django 4.2.9 on 2024-02-26 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0053_readerstudy_instant_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="empty_answer_confirmation",
            field=models.BooleanField(
                default=False,
                help_text="Require an explicit confirmation when saving an empty answer to this question.",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="empty_answer_confirmation_label",
            field=models.TextField(
                blank=True,
                help_text="Label to show when confirming an empty answer.",
            ),
        ),
    ]
