# Generated by Django 4.2.11 on 2024-04-23 09:15

import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0054_question_empty_answer_confirmation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayset",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=511,
                populate_from=["title", "order", "reader_study__slug"],
            ),
        ),
        migrations.AddField(
            model_name="displayset",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
