# Generated by Django 4.2.11 on 2024-04-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0054_question_empty_answer_confirmation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="displayset",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="displayset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("title", ""), _negated=True),
                fields=("title", "reader_study"),
                name="unique_title",
            ),
        ),
    ]
