# Generated by Django 4.2.11 on 2024-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0055_displayset_title_displayset_unique_title"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="displayset",
            name="unique_title",
        ),
        migrations.AddConstraint(
            model_name="displayset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("title", ""), _negated=True),
                fields=("title", "reader_study"),
                name="unique_display_set_title",
            ),
        ),
    ]
