# Generated by Django 4.2.15 on 2024-09-10 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0022_remove_workstationimage_is_on_sagemaker"),
        ("reader_studies", "0056_remove_displayset_unique_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="interactive_algorithm",
            field=models.CharField(
                blank=True,
                choices=[("uls23-baseline", "ULS23 Baseline")],
                help_text="Which interactive algorithm should be used for this question?",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="WorkstationSessionReaderStudy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reader_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reader_studies.readerstudy",
                    ),
                ),
                (
                    "workstation_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workstations.session",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="readerstudy",
            name="workstation_sessions",
            field=models.ManyToManyField(
                blank=True,
                editable=False,
                related_name="reader_studies",
                through="reader_studies.WorkstationSessionReaderStudy",
                to="workstations.session",
            ),
        ),
    ]
