# Generated by Django 4.2.15 on 2024-09-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0057_question_interactive_algorithm_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ("order", "created"),
                "permissions": [
                    (
                        "add_interactive_algorithm_to_question",
                        "Can add interactive algorithm to question",
                    )
                ],
            },
        ),
    ]
