# Generated by Django 4.2.17 on 2025-01-08 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "workstations",
            "0023_remove_workstationimage_desired_gpu_type_and_more",
        ),
        ("hanging_protocols", "0012_alter_hangingprotocol_json"),
        ("reader_studies", "0059_alter_question_overlay_segments"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="optionalhangingprotocolreaderstudy",
            unique_together={("reader_study", "hanging_protocol")},
        ),
        migrations.AlterUniqueTogether(
            name="workstationsessionreaderstudy",
            unique_together={("reader_study", "workstation_session")},
        ),
    ]
