# Generated by Django 4.2.20 on 2025-04-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0061_alter_question_overlay_segments"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="leaderboard_accessible_to_readers",
            field=models.BooleanField(
                default=False,
                help_text="If checked, readers can see the leaderboard. Usernames and avatars will be hidden to protect other readers' privacy.",
            ),
        ),
    ]
