# Generated by Django 4.2.20 on 2025-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0063_init_view_leaderboard_perm"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="max_credits",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="The maximum number of credits that may be consumed for this reader study",
            ),
        ),
    ]
