# Generated by Django 4.2.20 on 2025-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader_studies", "0063_init_view_leaderboard_perm"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="max_credits",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="The maximum number of credits that may be consumed for this reader study. Leave blank to allow unlimited usage.",
                null=True,
            ),
        ),
    ]
