# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0064_readerstudy_max_credits"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answergroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="reader_stud_group_i_d88df4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="answeruserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="reader_stud_user_id_111263_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="displaysetgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="reader_stud_group_i_da44c2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questiongroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="reader_stud_group_i_0813c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="readerstudygroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="reader_stud_group_i_8cdc21_idx",
            ),
        ),
    ]
