# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reader_studies",
            "0065_answergroupobjectpermission_reader_stud_group_i_d88df4_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="displaysetuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="reader_stud_user_id_eb81eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="questionuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="reader_stud_user_id_06271d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="readerstudyuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="reader_stud_user_id_6caeec_idx",
            ),
        ),
    ]
