# Generated by Django 4.2.21 on 2025-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reader_studies",
            "0066_displaysetuserobjectpermission_reader_stud_user_id_eb81eb_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="displayset",
            constraint=models.UniqueConstraint(
                fields=("order", "reader_study"),
                name="unique_display_set_order",
            ),
        ),
    ]
