# Generated by Django 4.2.21 on 2025-06-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "reader_studies",
            "0066_displaysetuserobjectpermission_reader_stud_user_id_eb81eb_idx_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalAnswer",
        ),
    ]
