# Generated by Django 4.2.23 on 2025-07-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0067_delete_historicalanswer"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="enable_autosaving",
            field=models.BooleanField(
                default=False,
                help_text="If true, answers to questions are saved in the background while a user reads a case. 'Allow Answer Modification' must be enabled as well for this to work. Please note that this feature does not work for questions that a marked as 'required' because storing answers for those questions needs to be done explicitly by pressing the Save-button.",
            ),
        ),
    ]
