# Generated by Django 4.2.23 on 2025-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0068_readerstudy_enable_autosaving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readerstudy",
            name="enable_autosaving",
            field=models.BooleanField(
                default=False,
                help_text="If true, answers to questions are saved in the background while a user reads a case. 'Allow Answer Modification' must be enabled as well for this to work.",
            ),
        ),
    ]
