# Generated by Django 4.2.23 on 2025-08-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0069_alter_readerstudy_enable_autosaving"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="end_of_study_text_markdown",
            field=models.TextField(
                blank=True,
                help_text="Text to show when a user has completed the reader study",
            ),
        ),
    ]
