# Generated by Django 4.2.26 on 2025-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0070_readerstudy_end_of_study_text_markdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="readerstudy",
            name="logo_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="readerstudy",
            name="logo_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="readerstudy",
            name="social_image_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="readerstudy",
            name="social_image_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
    ]
