# Generated by Django 4.2.23 on 2025-09-10 09:16

from django.db import migrations, models

import grandchallenge.reader_studies.models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0070_readerstudy_end_of_study_text_markdown"),
    ]

    operations = [
        migrations.AlterField(
            model_name="displayset",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                validators=[
                    grandchallenge.reader_studies.models.CleanedHtmlValidator(
                        no_tags=True
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="empty_answer_confirmation_label",
            field=models.TextField(
                blank=True,
                help_text="Label to show when confirming an empty answer.",
                validators=[
                    grandchallenge.reader_studies.models.CleanedHtmlValidator(
                        no_tags=True
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="help_text",
            field=models.TextField(
                blank=True,
                validators=[
                    grandchallenge.reader_studies.models.CleanedHtmlValidator(
                        no_tags=False
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question_text",
            field=models.TextField(
                validators=[
                    grandchallenge.reader_studies.models.CleanedHtmlValidator(
                        no_tags=True
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="readerstudy",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    grandchallenge.reader_studies.models.CleanedHtmlValidator(
                        no_tags=True
                    )
                ],
                verbose_name="title",
            ),
        ),
    ]
