# Generated by Django 4.2.23 on 2025-09-09 11:53

from django.db import migrations, models

import grandchallenge.reader_studies.models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0071_alter_displayset_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readerstudy",
            name="title",
            field=models.CharField(
                max_length=255,
                validators=[
                    grandchallenge.reader_studies.models.CleanedHtmlValidator(
                        no_tags=True
                    )
                ],
                verbose_name="title",
            ),
        ),
    ]
