# Generated by Django 5.2.12 on 2026-03-31 15:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0092_endpoint_endpointgroupobjectpermission_and_more"),
        ("reader_studies", "0074_alter_answer_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaderStudyAlgorithmImplementation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "algorithm_choice",
                    models.CharField(
                        choices=[("uls23-baseline", "ULS23 Baseline")],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reader_study_algorithm_implementations",
                        to="algorithms.algorithm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionReaderStudyAlgorithmImplementation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reader_studies.question",
                    ),
                ),
                (
                    "algorithm_implementation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reader_studies.readerstudyalgorithmimplementation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="question",
            name="algorithms",
            field=models.ManyToManyField(
                related_name="questions",
                through="reader_studies.QuestionReaderStudyAlgorithmImplementation",
                to="reader_studies.readerstudyalgorithmimplementation",
            ),
        ),
        migrations.AddConstraint(
            model_name="readerstudyalgorithmimplementation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("algorithm_choice__in", ["uls23-baseline"])
                ),
                name="algorithm_choice_valid",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questionreaderstudyalgorithmimplementation",
            unique_together={("question", "algorithm_implementation")},
        ),
    ]
