# Generated by Django 5.2.12 on 2026-04-03 15:10

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0093_remove_endpoint_endpoint_status_valid_and_more"),
        ("reader_studies", "0075_readerstudyalgorithmimplementation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReaderStudyAlgorithm",
            fields=[
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="description"
                    ),
                ),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        populate_from="title",
                        verbose_name="slug",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReaderStudyAlgorithmAlgorithmInterface",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="readerstudyalgorithmimplementation",
            name="algorithm_choice_valid",
        ),
        migrations.RemoveField(
            model_name="readerstudyalgorithmimplementation",
            name="algorithm_choice",
        ),
        migrations.AddField(
            model_name="readerstudyalgorithmimplementation",
            name="reader_study_algorithm",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reader_study_algorithm_implementations",
                to="reader_studies.readerstudyalgorithm",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="readerstudyalgorithmalgorithminterface",
            name="algorithm_interface",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="algorithms.algorithminterface",
            ),
        ),
        migrations.AddField(
            model_name="readerstudyalgorithmalgorithminterface",
            name="reader_study_algorithm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="reader_studies.readerstudyalgorithm",
            ),
        ),
        migrations.AddField(
            model_name="readerstudyalgorithm",
            name="interfaces",
            field=models.ManyToManyField(
                related_name="reader_study_algorithms",
                through="reader_studies.ReaderStudyAlgorithmAlgorithmInterface",
                to="algorithms.algorithminterface",
            ),
        ),
    ]
