# Generated by Django 5.2.15 on 2026-07-02 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0029_alter_image_segments"),
        ("reader_studies", "0079_alter_answer_answer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(
                fields=["display_set", "is_ground_truth"],
                name="reader_stud_display_fe8146_idx",
            ),
        ),
    ]
