# Generated by Django 3.2.13 on 2022-05-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("documentation", "0002_trigram_extension"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicaldocpage",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical doc page",
                "verbose_name_plural": "historical doc pages",
            },
        ),
        migrations.AlterField(
            model_name="historicaldocpage",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
