# Generated by Django 4.2.17 on 2025-01-21 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("documentation", "0003_auto_20220517_0740"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaldocpage",
            name="slug",
        ),
    ]
