# Generated by Django 4.2.21 on 2025-06-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0004_remove_historicaldocpage_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="docpage",
            name="content_plain",
            field=models.TextField(default="", editable=False),
        ),
        migrations.AddField(
            model_name="historicaldocpage",
            name="content_plain",
            field=models.TextField(default="", editable=False),
        ),
    ]
