# Generated by Django 4.2.21 on 2025-06-11 14:19

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0004_remove_historicaldocpage_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="docpage",
            name="content_plain",
            field=models.TextField(default="", editable=False),
        ),
        migrations.AddField(
            model_name="docpage",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                default="", editable=False
            ),
        ),
        migrations.AddField(
            model_name="historicaldocpage",
            name="content_plain",
            field=models.TextField(default="", editable=False),
        ),
        migrations.AddIndex(
            model_name="docpage",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="documentati_search__51d215_gin"
            ),
        ),
    ]
