# Generated by Django 4.2.21 on 2025-06-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0004_remove_historicaldocpage_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalDocPage",
        ),
    ]
