# Generated by Django 4.2.21 on 2025-06-10 16:30
from bs4 import BeautifulSoup
from django.contrib.postgres.search import SearchVector
from django.db import migrations

from grandchallenge.core.templatetags.bleach import md2html


def markdown_to_plain_text(md):
    if not md:
        return ""
    return BeautifulSoup(
        md2html(md, create_permalink_for_headers=False),
        "html.parser",
    ).get_text()


def generate_content_plain_and_search_vector(apps, schema_editor):
    DocPage = apps.get_model("documentation", "DocPage")  # noqa: N806

    for doc in DocPage.objects.all():
        doc.content_plain = markdown_to_plain_text(doc.content)
        doc.save()
        DocPage.objects.filter(pk=doc.pk).update(
            search_vector=SearchVector("title", "content_plain")
        )


class Migration(migrations.Migration):

    dependencies = [
        (
            "documentation",
            "0006_docpage_content_plain_docpage_search_vector_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            generate_content_plain_and_search_vector, elidable=True
        ),
    ]
