# Generated by Django 4.2.21 on 2025-06-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documentation", "0007_auto_20250610_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="docpage",
            name="is_faq",
            field=models.BooleanField(default=False),
        ),
    ]
