# Generated by Django 3.1.13 on 2021-10-06 07:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("uploads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=128)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Initialized"),
                            (2, "Completed"),
                            (3, "Aborted"),
                        ],
                        default=0,
                    ),
                ),
                ("s3_upload_id", models.CharField(blank=True, max_length=128)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
