# Generated by Django 3.1.13 on 2021-10-08 13:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("uploads", "0002_userupload")]

    operations = [migrations.DeleteModel(name="PublicMedia")]
