# Generated by Django 2.2.9 on 2020-01-22 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0004_publicmedia"),
    ]

    operations = [
        migrations.DeleteModel(name="UploadModel",),
    ]
