# Generated by Django 4.2.13 on 2024-05-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "uploads",
            "0005_useruploadgroupobjectpermission_useruploaduserobjectpermission",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userupload",
            name="mimetype",
            field=models.CharField(
                default="application/octet-stream",
                editable=False,
                max_length=255,
            ),
        ),
    ]
