# Generated by Django 4.2.16 on 2024-10-02 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0006_userupload_mimetype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SummernoteAttachment",
        ),
    ]
