# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("uploads", "0007_delete_summernoteattachment"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="useruploaduserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="uploads_use_user_id_866a16_idx",
            ),
        ),
    ]
