# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 13:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comicmodels', '0003_comicsite_use_registration_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrationrequest',
            old_name='project',
            new_name='challenge',
        ),
        migrations.AlterUniqueTogether(
            name='registrationrequest',
            unique_together=set([('challenge', 'user')]),
        ),
    ]
