# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('comicmodels', '0005_auto_20180319_1345'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.AlterUniqueTogether(
                name='page',
                unique_together=set([]),
            ),
            migrations.RemoveField(
                model_name='page',
                name='challenge',
            ),
            migrations.DeleteModel(
                name='Page',
            ),
        ])
    ]
