# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicmodels', '0007_auto_20180320_1041'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.RemoveField(
                model_name='uploadmodel',
                name='challenge',
            ),
            migrations.RemoveField(
                model_name='uploadmodel',
                name='user',
            ),
            migrations.DeleteModel(
                name='UploadModel',
            ),
        ])
    ]
