# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comicmodels', '0008_auto_20180320_1053'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=[
            migrations.RemoveField(
                model_name='comicsite',
                name='admins_group',
            ),
            migrations.RemoveField(
                model_name='comicsite',
                name='creator',
            ),
            migrations.RemoveField(
                model_name='comicsite',
                name='participants_group',
            ),
            migrations.DeleteModel(
                name='ComicSite',
            ),
        ])
    ]
