# Generated by Django 2.1.4 on 2019-01-15 14:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [
        # Non-elidable operation moved to post_migrate signal
    ]
