# Generated by Django 4.1.10 on 2023-07-27 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "challenges",
            "0029_alter_challenge_educational_alter_challenge_hidden",
        ),
        ("components", "0015_alter_componentinterface_overlay_segments"),
        ("workstations", "0018_remove_workstationimage_ready"),
        (
            "evaluation",
            "0040_combinedleaderboard_combinedleaderboardphase_and_more",
        ),
        ("cases", "0013_alter_image_segments"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("serving", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="download",
            name="challenge_request",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="challenges.challengerequest",
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="component_interface_value",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="components.componentinterfacevalue",
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="feedback",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workstations.feedback",
            ),
        ),
        migrations.AlterField(
            model_name="download",
            name="count",
            field=models.BigIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name="download",
            name="creator",
            field=models.ForeignKey(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="download",
            name="image",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cases.image",
            ),
        ),
        migrations.AlterField(
            model_name="download",
            name="submission",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluation.submission",
            ),
        ),
    ]
