# Generated by Django 4.2.13 on 2024-05-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("serving", "0002_download_challenge_request_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="download",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="download",
            name="count",
        ),
    ]
