# Generated by Django 4.2.19 on 2025-02-20 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "evaluation",
            "0071_alter_combinedleaderboardphase_unique_together_and_more",
        ),
        ("serving", "0004_download_algorithm_image_download_algorithm_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="download",
            name="submission_supplementary",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="supplementary_file_downloads",
                to="evaluation.submission",
            ),
        ),
    ]
