# Generated by Django 2.1.2 on 2018-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0009_auto_20170928_2327"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forum",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Forum image"
            ),
        ),
    ]
