# Generated by Django 4.2.23 on 2025-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0011_auto_20190627_2132"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="forum",
            name="last_post",
        ),
        migrations.RemoveField(
            model_name="forum",
            name="parent",
        ),
    ]
