# Generated by Django 2.1.3 on 2018-11-30 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retina_images', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Unnamed Archive', max_length=255)),
                ('images', models.ManyToManyField(to='retina_images.RetinaImage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
