# Generated by Django 2.1.3 on 2018-12-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("archives", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="images",
            field=models.ManyToManyField(to="cases.Image"),
        )
    ]
