# Generated by Django 3.0.2 on 2020-03-21 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="archive", old_name="name", new_name="title",
        ),
    ]
