# Generated by Django 2.1.4 on 2018-12-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_archive_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='images',
            field=models.ManyToManyField(to='cases.Image'),
        ),
    ]
