# Generated by Django 3.0.2 on 2020-03-22 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("archives", "0004_auto_20200322_0921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="editors_group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="editors_of_archive",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="uploaders_group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploaders_of_archive",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="archive",
            name="users_group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_of_archive",
                to="auth.Group",
            ),
        ),
    ]
