# Generated by Django 3.1.1 on 2021-02-01 09:34

from django.db import migrations, models

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0005_archive_social_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="social_image",
            field=models.ImageField(
                blank=True,
                help_text="An image for this archive which is displayed when you post the link to this archive on social media. Should be square with a resolution of 640x640 px or higher.",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_social_image_path,
            ),
        ),
    ]
