# Generated by Django 3.1.8 on 2021-05-04 08:07
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0003_auto_20210323_1452"),
        ("archives", "0005_archive_social_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="archives.archive",
                    ),
                ),
                (
                    "values",
                    models.ManyToManyField(
                        blank=True,
                        related_name="archive_items",
                        to="components.ComponentInterfaceValue",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
