# Generated by Django 3.1.1 on 2020-11-19 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0031_auto_20201117_0746"),
        ("archives", "0006_archivepermissionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="algorithms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Algorithms that will be executed on all images in this archive",
                to="algorithms.Algorithm",
            ),
        ),
    ]
