# Generated by Django 3.2.10 on 2022-02-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("archives", "0009_auto_20210601_0802")]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="access_request_handling",
            field=models.CharField(
                choices=[
                    ("MANUAL_REVIEW", "Manually review all requests"),
                    (
                        "ACCEPT_VERIFIED_USERS",
                        "Automatically accept requests from verified users only",
                    ),
                    (
                        "ACCEPT_ALL",
                        "Automatically accept requests from all users",
                    ),
                ],
                default="MANUAL_REVIEW",
                help_text="How would you like to handle access requests?",
                max_length=25,
            ),
        )
    ]
