# Generated by Django 4.1.10 on 2023-08-16 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanging_protocols', '0010_alter_hangingprotocol_json'),
        ('archives', '0015_archivegroupobjectpermission_archiveitemgroupobjectpermission_archiveitemuserobjectpermission_archiv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='hanging_protocol',
        ),
        migrations.AddField(
            model_name='archive',
            name='default_hanging_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_hanging_protocol_of_archive', to='hanging_protocols.hangingprotocol'),
        ),
        migrations.AddField(
            model_name='archive',
            name='optional_hanging_protocols',
            field=models.ManyToManyField(blank=True, help_text='Optional alternative hanging protocols for this archive', related_name='optional_hanging_protocols_of_archive', to='hanging_protocols.hangingprotocol'),
        ),
    ]
