# Generated by Django 4.1.10 on 2023-08-28 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hanging_protocols", "0010_alter_hangingprotocol_json"),
        (
            "archives",
            "0015_archivegroupobjectpermission_archiveitemgroupobjectpermission_archiveitemuserobjectpermission_archiv",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="OptionalHangingProtocolArchive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archive",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="archives.archive",
                    ),
                ),
                (
                    "hanging_protocol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hanging_protocols.hangingprotocol",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="archive",
            name="optional_hanging_protocols",
            field=models.ManyToManyField(
                blank=True,
                help_text="Optional alternative hanging protocols for this archive",
                related_name="optional_for_archive",
                through="archives.OptionalHangingProtocolArchive",
                to="hanging_protocols.hangingprotocol",
            ),
        ),
    ]
