# Generated by Django 4.2.11 on 2024-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0017_archive_item_delete_permission_granting"),
    ]

    operations = [
        migrations.AddField(
            model_name="archiveitem",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddConstraint(
            model_name="archiveitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("title", ""), _negated=True),
                fields=("title", "archive"),
                name="unique_archive_item_title",
            ),
        ),
    ]
