# Generated by Django 4.2.17 on 2025-01-08 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hanging_protocols", "0012_alter_hangingprotocol_json"),
        ("archives", "0018_archiveitem_title_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="optionalhangingprotocolarchive",
            unique_together={("archive", "hanging_protocol")},
        ),
    ]
