# Generated by Django 4.2.16 on 2024-11-19 13:33

from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0018_archiveitem_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="archive",
            name="view_content",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-06/schema#",
                            "additionalProperties": False,
                            "definitions": {},
                            "properties": {
                                "denary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "duodenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "main": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "nonary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "novemdenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "octodenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "octonary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "quaternary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "quattuordenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "quinary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "quindenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "secondary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "senary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "septenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "septendenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "sexdenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "tertiary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "tredenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "undenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "vigintenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                            },
                            "title": "The Display Port Mapping Schema",
                            "type": "object",
                        }
                    ),
                    grandchallenge.core.validators.ViewContentValidator(),
                ],
            ),
        ),
    ]
