# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archives", "0020_remove_archive_algorithms"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="archivegroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="archives_ar_group_i_5375aa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="archiveitemgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="archives_ar_group_i_7b33a3_idx",
            ),
        ),
    ]
