# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "archives",
            "0021_archivegroupobjectpermission_archives_ar_group_i_5375aa_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="archiveitemuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="archives_ar_user_id_13fbd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="archiveuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="archives_ar_user_id_1ca26e_idx",
            ),
        ),
    ]
