# Generated by Django 4.2.26 on 2025-11-13 09:08

import pictures.models
from django.db import migrations, models
from pictures.migrations import AlterPictureField

import grandchallenge.core.storage


def add_social_image_dimensions(apps, schema_editor):
    for obj in apps.get_model("archives.archive").objects.all().iterator():
        if obj.social_image:
            obj.social_image_width = obj.social_image.width
            obj.social_image_height = obj.social_image.height
        obj.save(update_fields=["social_image_width", "social_image_height"])


def remove_social_image_dimensions(apps, schema_editor):
    apps.get_model("archives.archive").objects.all().update(
        social_image_width=None,
        social_image_height=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "archives",
            "0022_archiveitemuserobjectpermission_archives_ar_user_id_13fbd3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="archive",
            name="social_image_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="archive",
            name="social_image_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.RunPython(
            add_social_image_dimensions,
            remove_social_image_dimensions,
            elidable=True,
        ),
        AlterPictureField(
            model_name="archive",
            name="logo",
            field=pictures.models.PictureField(
                aspect_ratios=["1/1"],
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
            ),
        ),
        AlterPictureField(
            model_name="archive",
            name="social_image",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="social_image_height",
                help_text="An image for this archive which is displayed when you post the link to this archive on social media. Should have a resolution of 640x320 px (1280x640 px for best display).",
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_social_image_path,
                width_field="social_image_width",
            ),
        ),
    ]
