# Generated by Django 5.2.16 on 2026-08-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anatomy", "0002_alter_bodyregion_region_and_more"),
        ("archives", "0025_alter_archive_logo_alter_archive_social_image"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hanging_protocols", "0016_alter_hangingprotocol_json"),
        ("modalities", "0002_alter_imagingmodality_modality"),
        ("organizations", "0013_alter_organization_logo"),
        ("publications", "0005_alter_publication_identifier"),
        (
            "workstation_configs",
            "0033_lookuptable_workstation_configs_lookuptable_unique_slug_and_more",
        ),
        ("workstations", "0044_remove_session_user_finished"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="archive",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="archives_archive_unique_slug"
            ),
        ),
    ]
