# Generated by Django 4.2.23 on 2025-08-08 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("otp_totp", "0003_add_timestamps"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TOTPDevice",
        ),
    ]
