# Generated by Django 2.1.7 on 2019-02-21 12:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eyra_benchmarks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=32, null=True, unique=True)),
                ('description_html', models.TextField(blank=True)),
                ('algorithm_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_submission_algorithm', to='eyra_submissions.Job')),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eyra_benchmarks.Benchmark')),
                ('evaluation_job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_evaluation_algorithm', to='eyra_submissions.Job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
