# Generated by Django 4.2.16 on 2024-11-19 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knox", "0008_remove_authtoken_salt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="authtoken",
            old_name="digest",
            new_name="key",
        ),
    ]
