# Generated by Django 3.0.2 on 2020-03-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("overview_pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="overviewpage",
            name="published",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="overviewpage",
            index=models.Index(
                fields=["published"], name="overview_pa_publish_d1ac48_idx"
            ),
        ),
    ]
