# Generated by Django 3.0.10 on 2020-09-18 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication", old_name="doi", new_name="identifier",
        ),
        migrations.RenameField(
            model_name="publication", old_name="citeproc_json", new_name="csl",
        ),
    ]
