# Generated by Django 3.2.13 on 2022-05-04 08:40

from django.db import migrations

import grandchallenge.publications.models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0004_publication_citation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="identifier",
            field=grandchallenge.publications.models.IdentifierField(
                unique=True
            ),
        ),
    ]
