# Generated by Django 1.9.2 on 2016-02-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_conversation", "0002_post_anonymous_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
    ]
