# Generated by Django 2.2.10 on 2020-04-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_conversation", "0011_remove_post_poster_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
    ]
