# Generated by Django 4.2.23 on 2025-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0012_remove_forum_last_post_remove_forum_parent"),
        ("forum_polls", "0004_remove_topicpolloption_poll_and_more"),
        ("forum_attachments", "0003_delete_attachment"),
        (
            "forum_tracking",
            "0003_alter_topicreadtrack_unique_together_and_more",
        ),
        ("forum_conversation", "0013_auto_20201220_1745"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="first_post",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="forum",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="last_post",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="poster",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="subscribers",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
