# Generated by Django 3.1.9 on 2021-05-12 15:02

from django.db import migrations, models

import grandchallenge.core.storage


class Migration(migrations.Migration):
    dependencies = [("blogs", "0002_auto_20200908_0942")]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="logo",
            field=models.ImageField(
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
            ),
        )
    ]
