# Generated by Django 3.1.13 on 2021-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_auto_20210614_0734"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="publish_location",
            field=models.CharField(
                choices=[
                    ("gc", "Grand Challenge"),
                    ("air", "AI for Radiology"),
                ],
                default="gc",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="publish_location",
            field=models.CharField(
                choices=[
                    ("gc", "Grand Challenge"),
                    ("air", "AI for Radiology"),
                ],
                default="gc",
                max_length=3,
            ),
        ),
    ]
