# Generated by Django 3.1.13 on 2021-08-24 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_projectairfiles"),
        ("blogs", "0004_auto_20210614_0734"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="companies",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="products.Company"
            ),
        ),
    ]
