# Generated by Django 3.1.13 on 2021-08-24 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0004_auto_20210614_0734"),
    ]

    operations = []
