# Generated by Django 3.1.13 on 2021-10-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0005_post_companies"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="highlight",
            field=models.BooleanField(
                default=False,
                help_text="If selected, this blog post will appear in first position in the news carousel on the home page.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="highlight",
            field=models.BooleanField(
                default=False,
                help_text="If selected, this blog post will appear in first position in the news carousel on the home page.",
            ),
        ),
    ]
