# Generated by Django 3.2.13 on 2022-05-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0006_auto_20211004_1109"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalpost",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical post",
                "verbose_name_plural": "historical posts",
            },
        ),
        migrations.AlterField(
            model_name="historicalpost",
            name="history_date",
            field=models.DateTimeField(db_index=True),
        ),
    ]
