# Generated by Django 3.2.13 on 2022-06-02 06:40

from django.db import migrations, models

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_auto_20220517_0740"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="logo",
            field=models.ImageField(
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
            ),
        ),
    ]
