# Generated by Django 4.2.9 on 2024-02-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0009_postgroupobjectpermission_postuserobjectpermission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="companies",
        ),
    ]
