# Generated by Django 4.2.17 on 2025-01-21 12:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0010_remove_post_companies"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpost",
            name="slug",
        ),
    ]
