# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0011_remove_historicalpost_slug"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="postuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="blogs_postu_user_id_70c456_idx",
            ),
        ),
    ]
