# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "blogs",
            "0012_postuserobjectpermission_blogs_postu_user_id_70c456_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="postgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="blogs_postg_group_i_4b4b92_idx",
            ),
        ),
    ]
