# Generated by Django 4.2.26 on 2025-11-13 09:08

import pictures.models
from django.db import migrations, models
from pictures.migrations import AlterPictureField

import grandchallenge.core.storage


def add_logo_dimensions(apps, schema_editor):
    for obj in apps.get_model("blogs.post").objects.all().iterator():
        obj.logo_width = obj.logo.width
        obj.logo_height = obj.logo.height
        obj.save(update_fields=["logo_width", "logo_height"])


def remove_logo_dimensions(apps, schema_editor):
    apps.get_model("blogs.post").objects.all().update(
        logo_width=None,
        logo_height=None,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0014_delete_historicalpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="logo_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="logo_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.RunPython(
            add_logo_dimensions,
            remove_logo_dimensions,
            elidable=True,
        ),
        AlterPictureField(
            model_name="post",
            name="logo",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="logo_height",
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
                width_field="logo_width",
            ),
        ),
    ]
