# Generated by Django 3.1.1 on 2020-12-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="The organizations associated with this challenge",
                related_name="challenges",
                to="organizations.Organization",
            ),
        ),
        migrations.AddField(
            model_name="externalchallenge",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="The organizations associated with this challenge",
                related_name="externalchallenges",
                to="organizations.Organization",
            ),
        ),
    ]
