# Generated by Django 2.0.5 on 2018-06-12 11:38

from django.db import migrations, models

import grandchallenge.challenges.models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0004_auto_20180612_1059")]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="banner",
            field=models.ImageField(
                blank=True,
                upload_to=grandchallenge.challenges.models.get_banner_path,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="logo",
            field=models.ImageField(
                blank=True,
                upload_to=grandchallenge.challenges.models.get_logo_path,
            ),
        ),
    ]
