# Generated by Django 3.1.9 on 2021-05-12 14:37

import stdimage.models
from django.db import migrations

import grandchallenge.core.storage


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0004_auto_20210423_1049"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="banner",
            field=stdimage.models.JPEGField(
                blank=True,
                help_text="Image that gets displayed at the top of each page. Recommended resolution 2200x440 px.",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_banner_path,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="logo",
            field=stdimage.models.JPEGField(
                blank=True,
                help_text="A logo for this challenge. Should be square with a resolution of 640x640 px or higher.",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="social_image",
            field=stdimage.models.JPEGField(
                blank=True,
                help_text="An image for this challenge which is displayed when you post the link on social media. Should have a resolution of 640x320 px (1280x640 px for best display).",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_social_image_path,
            ),
        ),
        migrations.AlterField(
            model_name="externalchallenge",
            name="logo",
            field=stdimage.models.JPEGField(
                blank=True,
                help_text="A logo for this challenge. Should be square with a resolution of 640x640 px or higher.",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
            ),
        ),
        migrations.AlterField(
            model_name="externalchallenge",
            name="social_image",
            field=stdimage.models.JPEGField(
                blank=True,
                help_text="An image for this challenge which is displayed when you post the link on social media. Should have a resolution of 640x320 px (1280x640 px for best display).",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_social_image_path,
            ),
        ),
    ]
