# Generated by Django 3.1.11 on 2021-07-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publications", "0004_publication_citation"),
        ("challenges", "0006_auto_20210601_0802"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="publications",
            field=models.ManyToManyField(
                blank=True,
                help_text='The publications associated with this challenge. If your publication is missing click <a href="https://gc.localhost/publications/create/">here</a> to add it and then refresh this page.',
                to="publications.Publication",
            ),
        ),
        migrations.AlterField(
            model_name="externalchallenge",
            name="publications",
            field=models.ManyToManyField(
                blank=True,
                help_text='The publications associated with this challenge. If your publication is missing click <a href="https://gc.localhost/publications/create/">here</a> to add it and then refresh this page.',
                to="publications.Publication",
            ),
        ),
    ]
