# Generated by Django 3.2.10 on 2022-02-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0010_remove_challenge_use_evaluation"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="access_request_handling",
            field=models.CharField(
                choices=[
                    ("MANUAL_REVIEW", "Manually review all requests"),
                    (
                        "ACCEPT_VERIFIED_USERS",
                        "Automatically accept requests from verified users only",
                    ),
                    (
                        "ACCEPT_ALL",
                        "Automatically accept requests from all users",
                    ),
                ],
                default="MANUAL_REVIEW",
                help_text="How would you like to handle access requests?",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="require_participant_review",
            field=models.BooleanField(
                default=False,
                help_text="If ticked, new participants need to be approved by project admins before they can access restricted pages. If not ticked, new users are allowed access immediately",
                null=True,
            ),
        ),
    ]
