# Generated by Django 2.0.9 on 2018-10-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0010_auto_20180830_1336")]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="publication_citation_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="The number of citations for the publication",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="publication_google_scholar_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="The ID of the article in google scholar. For instance, setting this to 5362332738201102290, which the ID for LeCun et al. in Nature 2015, and corresponds to the urlhttps://scholar.google.com/scholar?cluster=5362332738201102290",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="externalchallenge",
            name="publication_citation_count",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="The number of citations for the publication",
            ),
        ),
        migrations.AddField(
            model_name="externalchallenge",
            name="publication_google_scholar_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="The ID of the article in google scholar. For instance, setting this to 5362332738201102290, which the ID for LeCun et al. in Nature 2015, and corresponds to the urlhttps://scholar.google.com/scholar?cluster=5362332738201102290",
                null=True,
            ),
        ),
    ]
