# Generated by Django 2.0.9 on 2018-10-19 14:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0011_auto_20181011_1239")]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="filter_classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                default=list,
                editable=False,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="externalchallenge",
            name="filter_classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=32),
                default=list,
                editable=False,
                size=None,
            ),
        ),
    ]
