# Generated by Django 2.0.9 on 2018-10-19 16:42

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("challenges", "0012_auto_20181019_1446")]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="filter_classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.citext.CICharField(
                    max_length=32
                ),
                default=list,
                editable=False,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="externalchallenge",
            name="filter_classes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.citext.CICharField(
                    max_length=32
                ),
                default=list,
                editable=False,
                size=None,
            ),
        ),
    ]
