# Generated by Django 3.2.12 on 2022-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0013_challengerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengerequest",
            name="data_license",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challengerequest",
            name="data_license_extra",
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="challengerequest",
            name="long_term_commitment",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challengerequest",
            name="long_term_commitment_extra",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
