# Generated by Django 3.2.12 on 2022-04-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0014_auto_20220329_1344"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengerequest",
            name="comments",
            field=models.TextField(
                blank=True,
                help_text="If you have any comments, remarks or questions, please leave them here.",
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="inference_time_limit_in_minutes",
            field=models.IntegerField(
                blank=True,
                help_text="Average run time per algorithm job in minutes.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="phase_1_number_of_submissions_per_team",
            field=models.IntegerField(
                blank=True,
                help_text="How many submissions do you expect per team in this phase?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="phase_2_number_of_submissions_per_team",
            field=models.IntegerField(
                blank=True,
                help_text="How many submissions do you expect per team in this phase?",
                null=True,
            ),
        ),
    ]
