# Generated by Django 2.1.4 on 2018-12-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0015_remove_challenge_allow_unfiltered_page_html")
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="skin",
            field=models.CharField(
                blank=True,
                default="",
                help_text="css file to include throughout this project. relative to project data folder",
                max_length=225,
            ),
        )
    ]
