# Generated by Django 2.1.4 on 2018-12-14 12:56

from django.db import migrations, models

import grandchallenge.challenges.models


class Migration(migrations.Migration):

    dependencies = [("challenges", "0016_auto_20181212_1059")]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Image that gets displayed at the top of each page. Recommended resolution 2200x440 px.",
                upload_to=grandchallenge.challenges.models.get_banner_path,
            ),
        )
    ]
