# Generated by Django 3.2.13 on 2022-04-28 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0016_auto_20220415_1157"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengerequest",
            name="structured_challenge_submission_doi",
            field=models.CharField(
                blank=True,
                help_text="The DOI, e.g., 10.5281/zenodo.6362337, or the arXiv id, e.g., 2006.12449 of your challenge submission PDF.",
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^10\\.\\d{4,9}/[-._;()/:a-z0-9]+$|^\\d{4}\\.\\d{4,5}$"
                    )
                ],
            ),
        ),
    ]
