# Generated by Django 3.2.13 on 2022-05-03 11:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "challenges",
            "0017_challengerequest_structured_challenge_submission_doi",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="require_participant_review",
        ),
    ]
