# Generated by Django 3.2.13 on 2022-05-04 08:40

from django.db import migrations

import grandchallenge.publications.models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0018_remove_challenge_require_participant_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengerequest",
            name="structured_challenge_submission_doi",
            field=grandchallenge.publications.models.IdentifierField(
                blank=True
            ),
        ),
    ]
