# Generated by Django 3.2.13 on 2022-05-05 12:38

from django.db import migrations

import grandchallenge.publications.fields


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0018_remove_challenge_require_participant_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengerequest",
            name="structured_challenge_submission_doi",
            field=grandchallenge.publications.fields.IdentifierField(
                blank=True,
                help_text="The DOI, e.g., 10.5281/zenodo.6362337, or the arXiv id, e.g., 2006.12449 of your challenge submission PDF.",
            ),
        ),
    ]
