# Generated by Django 2.2.9 on 2020-01-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0020_auto_20200109_1119"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="skin",
            field=models.TextField(
                blank=True, default="", help_text="CSS for this challenge.",
            ),
        ),
    ]
