# Generated by Django 2.2.9 on 2020-01-21 16:39

from django.db import migrations, models

import grandchallenge.challenges.models
import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0021_auto_20200116_1337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Image that gets displayed at the top of each page. Recommended resolution 2200x440 px.",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.challenges.models.get_banner_path,
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="A logo for this challenge. Should be square with a resolution of 640x640 px or higher.",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.challenges.models.get_logo_path,
            ),
        ),
        migrations.AlterField(
            model_name="externalchallenge",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="A logo for this challenge. Should be square with a resolution of 640x640 px or higher.",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.challenges.models.get_logo_path,
            ),
        ),
    ]
