# Generated by Django 2.2.9 on 2020-01-21 16:24

from django.db import migrations, models

import grandchallenge.challenges.models
import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0022_auto_20200121_1554"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Image that gets displayed at the top of each page. Recommended resolution 2200x440 px.",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.challenges.models.get_banner_path,
            ),
        ),
    ]
