# Generated by Django 3.0.2 on 2020-01-23 11:02

import re

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations

import grandchallenge.challenges.models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0022_auto_20200121_1639"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="short_name",
            field=django.contrib.postgres.fields.citext.CICharField(
                help_text="short name used in url, specific css, files etc. No spaces allowed",
                max_length=50,
                unique=True,
                validators=[
                    grandchallenge.challenges.models.validate_nounderscores,
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    ),
                    grandchallenge.challenges.models.validate_short_name,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="externalchallenge",
            name="short_name",
            field=django.contrib.postgres.fields.citext.CICharField(
                help_text="short name used in url, specific css, files etc. No spaces allowed",
                max_length=50,
                unique=True,
                validators=[
                    grandchallenge.challenges.models.validate_nounderscores,
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    ),
                    grandchallenge.challenges.models.validate_short_name,
                ],
            ),
        ),
    ]
