# Generated by Django 3.2.15 on 2022-12-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0022_challengegroupobjectpermission_challengeuserobjectpermission",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challengerequest",
            name="challenge_type_extra",
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
