# Generated by Django 3.2.15 on 2022-12-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "challenges",
            "0022_challengegroupobjectpermission_challengeuserobjectpermission",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengerequest",
            name="challenge_type",
        ),
        migrations.AddField(
            model_name="challengerequest",
            name="challenge_fee_agreement",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="algorithm_inputs",
            field=models.TextField(
                blank=True,
                help_text="What are the inputs to the algorithms submitted as solutions to your challenge going to be? Please describe in detail what the input(s) reflect(s), for example, MRI scan of the brain, or chest X-ray. Grand Challenge only supports .mha and .tiff image files and json files for algorithms.",
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="algorithm_outputs",
            field=models.TextField(
                blank=True,
                help_text="What are the outputs to the algorithms submitted as solutions to your challenge going to be? Please describe in detail what the output(s) reflect(s), for example, probability of a positive PCR result, or stroke lesion segmentation. ",
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="budget_for_hosting_challenge",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="What is your budget for hosting this challenge? Please be reminded of our <a href='/challenge-policy-and-pricing/'>challenge pricing policy</a>.",
                null=True,
            ),
        ),
    ]
