# Generated by Django 3.2.16 on 2022-12-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0023_auto_20221212_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengerequest",
            name="average_algorithm_container_size_in_gb",
            field=models.IntegerField(
                default=6, help_text="Average algorithm container size in GB."
            ),
        ),
    ]
