# Generated by Django 3.2.16 on 2023-01-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0023_auto_20221212_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="accumulated_compute_cost_in_cents",
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="challenge",
            name="accumulated_docker_storage_cost_in_cents",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
