# Generated by Django 3.0.6 on 2020-06-11 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0023_auto_20200123_1102"),
    ]

    operations = [
        migrations.RemoveField(model_name="challenge", name="hide_footer",),
        migrations.RemoveField(model_name="challenge", name="hide_signin",),
        migrations.RemoveField(model_name="challenge", name="skin",),
    ]
