# Generated by Django 3.0.6 on 2020-06-11 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0023_auto_20200123_1102"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={
                "ordering": ("pk",),
                "verbose_name": "challenge",
                "verbose_name_plural": "challenges",
            },
        ),
        migrations.AlterModelOptions(
            name="externalchallenge", options={"ordering": ("pk",)},
        ),
        migrations.RemoveField(model_name="challenge", name="hide_footer",),
        migrations.RemoveField(model_name="challenge", name="hide_signin",),
        migrations.RemoveField(model_name="challenge", name="skin",),
    ]
