# Generated by Django 3.2.16 on 2022-12-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0023_auto_20221212_1051"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="accumulated_compute_cost",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="challenge",
            name="accumulated_docker_storage_cost",
            field=models.FloatField(blank=True, default=0),
        ),
    ]
