# Generated by Django 3.0.9 on 2020-08-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0024_auto_20200611_1053"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="use_teams",
            field=models.BooleanField(
                default=False,
                help_text="If true, users are able to form teams to participate in this challenge together.",
            ),
        ),
    ]
