# Generated by Django 3.0.9 on 2020-09-08 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("forum", "0011_auto_20190627_2132"),
        ("challenges", "0025_challenge_use_teams"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="forum",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="forum.Forum",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="admins_group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins_of_challenge",
                to="auth.Group",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="participants_group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants_of_challenge",
                to="auth.Group",
            ),
        ),
    ]
