# Generated by Django 3.2.18 on 2023-03-10 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0026_auto_20230123_1406"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ExternalChallenge",
        ),
    ]
