# Generated by Django 4.0.10 on 2023-03-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0005_organizationgroupobjectpermission_organizationuserobjectpermission",
        ),
        ("challenges", "0027_delete_externalchallenge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                help_text="The organizations associated with this challenge",
                related_name="%(class)ss",
                to="organizations.organization",
            ),
        ),
    ]
