# Generated by Django 4.1.8 on 2023-05-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0028_alter_challenge_organizations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="educational",
            field=models.BooleanField(
                default=False, help_text="It is an educational challenge"
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="hidden",
            field=models.BooleanField(
                default=True,
                help_text="Do not display this Challenge in any public overview",
            ),
        ),
    ]
