# Generated by Django 3.1.1 on 2020-11-24 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anatomy", "0001_initial"),
        ("challenges", "0029_auto_20200918_1413"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="bodystructure",
                    name="region",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="anatomy.bodyregion",
                    ),
                ),
            ],
            # Reusing an existing table
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name="BodyRegion")],
            database_operations=[
                migrations.AlterModelTable(
                    name="BodyRegion", table="anatomy_bodyregion"
                )
            ],
        ),
    ]
