# Generated by Django 4.1.11 on 2023-10-03 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("challenges", "0030_challenge_compute_cost_euro_millicents_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="accumulated_compute_cost_in_cents",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="accumulated_docker_storage_cost_in_cents",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
