# Generated by Django 4.1.13 on 2023-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentives", "0001_initial"),
        (
            "challenges",
            "0031_alter_challenge_accumulated_compute_cost_in_cents_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="incentives",
            field=models.ManyToManyField(
                blank=True,
                help_text="What incentives are there for users to participate in this challenge?",
                to="incentives.incentive",
            ),
        ),
        migrations.AddField(
            model_name="challengerequest",
            name="incentives",
            field=models.ManyToManyField(
                blank=True,
                help_text="What incentives are there for users to participate in this challenge?",
                to="incentives.incentive",
            ),
        ),
    ]
