# Generated by Django 3.1.1 on 2020-11-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_categories", "0001_initial"),
        ("challenges", "0031_move_bodystructure"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="challenge",
                    name="task_types",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="What type of task is this challenge?",
                        to="task_categories.TaskType",
                    ),
                ),
                migrations.AlterField(
                    model_name="externalchallenge",
                    name="task_types",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="What type of task is this challenge?",
                        to="task_categories.TaskType",
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name="TaskType",)],
            database_operations=[
                migrations.AlterModelTable(
                    name="TaskType", table="task_categories_tasktype"
                )
            ],
        ),
    ]
