# Generated by Django 3.1.1 on 2020-11-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modalities", "0001_initial"),
        ("cases", "0027_auto_20201124_1316"),
        ("challenges", "0032_move_task_type"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="challenge",
                    name="modalities",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="What imaging modalities are used in this challenge?",
                        to="modalities.ImagingModality",
                    ),
                ),
                migrations.AlterField(
                    model_name="externalchallenge",
                    name="modalities",
                    field=models.ManyToManyField(
                        blank=True,
                        help_text="What imaging modalities are used in this challenge?",
                        to="modalities.ImagingModality",
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[migrations.DeleteModel(name="ImagingModality")],
            database_operations=[
                migrations.AlterModelTable(
                    name="ImagingModality", table="modalities_imagingmodality"
                )
            ],
        ),
    ]
