# Generated by Django 4.2.7 on 2023-11-30 16:02

import re

import django.core.validators
from django.db import migrations, models

import grandchallenge.challenges.models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0033_challengerequestuserobjectpermission_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="filter_classes",
        ),
        migrations.AlterField(
            model_name="challenge",
            name="short_name",
            field=models.CharField(
                help_text="short name used in url, specific css, files etc. No spaces allowed",
                max_length=50,
                unique=True,
                validators=[
                    grandchallenge.challenges.models.validate_nounderscores,
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    ),
                    grandchallenge.challenges.models.validate_short_name,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="short_name",
            field=models.CharField(
                help_text="short name used in url, specific css, files etc. No spaces allowed",
                max_length=50,
                unique=True,
                validators=[
                    grandchallenge.challenges.models.validate_nounderscores,
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    ),
                    grandchallenge.challenges.models.validate_short_name,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="challengeseries",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
