# Generated by Django 4.2.9 on 2024-01-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0034_remove_challenge_filter_classes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="use_workspaces",
        ),
    ]
