# Generated by Django 4.2.11 on 2024-04-26 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0035_remove_challenge_use_workspaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_suspended",
            field=models.BooleanField(
                default=False,
                help_text="Challenge is suspended and not accepting submissions",
            ),
        ),
    ]
