# Generated by Django 4.2.15 on 2024-09-10 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0037_external_evaluators_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challenge",
            options={
                "ordering": ("pk",),
                "permissions": [
                    (
                        "add_registration_question",
                        "Can add registration questions",
                    )
                ],
                "verbose_name": "challenge",
                "verbose_name_plural": "challenges",
            },
        ),
    ]
