# Generated by Django 4.2.15 on 2024-09-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0039_alter_challenge_external_evaluators_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_active_until",
            field=models.DateField(
                help_text="The date at which the challenge becomes inactive",
                null=True,
            ),
        ),
    ]
