# Generated by Django 4.2.16 on 2024-10-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0042_alter_challenge_is_active_until"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="registration_page_markdown",
            field=models.TextField(
                blank=True,
                help_text="Markdown to include on the registration page to provide more context to users registering for the challenge.",
            ),
        ),
    ]
