# Generated by Django 4.2.17 on 2024-12-19 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "challenges",
            "0045_challengerequest_algorithm_maximum_settable_memory_gb_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengerequest",
            name="budget_for_hosting_challenge",
        ),
    ]
