# Generated by Django 4.2.17 on 2025-01-08 11:46

from django.db import migrations, models

import grandchallenge.challenges.models
import grandchallenge.core.validators


class Migration(migrations.Migration):
    dependencies = [
        (
            "challenges",
            "0046_remove_challengerequest_budget_for_hosting_challenge",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="percent_budget_consumed_warning_thresholds",
            field=models.JSONField(
                default=grandchallenge.challenges.models.get_default_percent_budget_consumed_warning_thresholds,
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema",
                            "items": {
                                "exclusiveMinimum": 0,
                                "maximum": 100,
                                "type": "integer",
                            },
                            "type": "array",
                            "uniqueItems": True,
                        }
                    )
                ],
            ),
        ),
    ]
