# Generated by Django 4.2.18 on 2025-02-06 15:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "challenges",
            "0048_onboardingtask_onboardingtaskgroupobjectpermission",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="onboardingtask",
            options={},
        ),
    ]
