# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0051_onboardingtaskuserobjectpermission"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="challengegroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="challenges__group_i_8a9dd3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="challengerequestgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="challenges__group_i_dae52c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="challengerequestuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="challenges__user_id_339a4e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="onboardingtaskgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="challenges__group_i_0e2b4b_idx",
            ),
        ),
    ]
