# Generated by Django 4.2.21 on 2025-05-14 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0011_auto_20190627_2132"),
        ("discussion_forums", "0001_initial"),
        (
            "challenges",
            "0052_challengegroupobjectpermission_challenges__group_i_8a9dd3_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="discussion_forum",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="linked_challenge",
                to="discussion_forums.forum",
            ),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="forum",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="forum.forum",
            ),
        ),
    ]
