# Generated by Django 4.2.21 on 2025-06-20 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussion_forums", "0001_initial"),
        (
            "challenges",
            "0054_alter_challengerequest_algorithm_maximum_settable_memory_gb",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="discussion_forum",
            field=models.OneToOneField(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="linked_challenge",
                to="discussion_forums.forum",
            ),
        ),
    ]
