# Generated by Django 4.2.23 on 2025-08-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0056_alter_challenge_forum"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="forum",
        ),
    ]
