# Generated by Django 4.2.25 on 2025-10-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0057_remove_challenge_forum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="educational",
            field=models.BooleanField(
                default=False,
                help_text="It is an educational challenge",
                null=True,
            ),
        ),
    ]
