# Generated by Django 4.2.26 on 2025-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0058_alter_challenge_educational"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="banner_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="banner_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="logo_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="logo_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="social_image_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="social_image_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
    ]
