# Generated by Django 4.2.24 on 2025-09-17 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0059_auto_20250820_1420"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengerequest",
            name="algorithm_maximum_settable_memory_gb",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="algorithm_selectable_gpu_type_choices",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="average_number_of_containers_per_team",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="average_size_of_test_image_in_mb",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="expected_number_of_teams",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="inference_time_limit_in_minutes",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="number_of_tasks",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="phase_1_number_of_submissions_per_team",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="phase_1_number_of_test_images",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="phase_2_number_of_submissions_per_team",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="phase_2_number_of_test_images",
        ),
    ]
