# Generated by Django 4.2.26 on 2025-11-14 13:45

import pictures.models
from django.db import migrations
from pictures.migrations import AlterPictureField

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0059_challenge_banner_height_challenge_banner_width_and_more",
        ),
    ]

    operations = [
        AlterPictureField(
            model_name="challenge",
            name="banner",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="banner_height",
                help_text="Image that gets displayed at the top of each page. Recommended resolution 2200x440 px.",
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_banner_path,
                width_field="banner_width",
            ),
        ),
        AlterPictureField(
            model_name="challenge",
            name="logo",
            field=pictures.models.PictureField(
                aspect_ratios=["1/1"],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="logo_height",
                help_text="A logo for this challenge. Should be square with a resolution of 640x640 px or higher.",
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
                width_field="logo_width",
            ),
        ),
        AlterPictureField(
            model_name="challenge",
            name="social_image",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="social_image_height",
                help_text="An image for this challenge which is displayed when you post the link on social media. Should have a resolution of 640x320 px (1280x640 px for best display).",
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_social_image_path,
                width_field="social_image_width",
            ),
        ),
    ]
