# Generated by Django 4.2.25 on 2025-10-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0061_alter_challengerequest_algorithm_maximum_settable_memory_gb_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="accumulated_compute_cost_in_cents",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="accumulated_docker_storage_cost_in_cents",
        ),
        migrations.RemoveField(
            model_name="challenge",
            name="educational",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="algorithm_maximum_settable_memory_gb",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="algorithm_selectable_gpu_type_choices",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="average_number_of_containers_per_team",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="average_size_of_test_image_in_mb",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="expected_number_of_teams",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="inference_time_limit_in_minutes",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="number_of_tasks",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="phase_1_number_of_submissions_per_team",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="phase_1_number_of_test_images",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="phase_2_number_of_submissions_per_team",
        ),
        migrations.RemoveField(
            model_name="challengerequest",
            name="phase_2_number_of_test_images",
        ),
    ]
