# Generated by Django 5.2.11 on 2026-02-26 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0065_remove_challenge_accumulated_compute_cost_in_cents_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challengerequest",
            options={
                "permissions": [
                    ("review_challengerequest", "Can review challenge request")
                ]
            },
        ),
        migrations.AddField(
            model_name="challengerequest",
            name="submitted",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACPT", "Accepted"),
                    ("RJCT", "Rejected"),
                    ("PEND", "Pending"),
                    ("DRFT", "Draft"),
                ],
                default="DRFT",
                max_length=4,
            ),
        ),
    ]
