# Generated by Django 5.2.11 on 2026-03-03 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anatomy", "0002_alter_bodyregion_region_and_more"),
        (
            "challenges",
            "0065_remove_challenge_accumulated_compute_cost_in_cents_and_more",
        ),
        ("incentives", "0002_alter_incentive_incentive"),
        ("modalities", "0002_alter_imagingmodality_modality"),
        ("task_categories", "0002_alter_tasktype_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="challengerequest",
            options={
                "permissions": [
                    ("review_challengerequest", "Can review challenge request")
                ]
            },
        ),
        migrations.AddField(
            model_name="challengerequest",
            name="submitted_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACPT", "Accepted"),
                    ("RJCT", "Rejected"),
                    ("PEND", "Pending"),
                    ("DRFT", "Draft"),
                ],
                default="DRFT",
                max_length=4,
            ),
        ),
    ]
