# Generated by Django 5.2.12 on 2026-03-10 08:47

from django.db import migrations, models

import grandchallenge.publications.fields


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0066_alter_challengerequest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengerequest",
            name="abstract",
            field=models.TextField(
                blank=True,
                help_text="Provide a summary of the challenge purpose.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="algorithm_inputs",
            field=models.TextField(
                blank=True,
                help_text="What are the inputs to the algorithms submitted as solutions to your challenge going to be? Please describe in detail what the input(s) reflect(s), for example, MRI scan of the brain, or chest X-ray. Grand Challenge only supports .mha and .tiff image files and json files for algorithms.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="algorithm_outputs",
            field=models.TextField(
                blank=True,
                help_text="What are the outputs to the algorithms submitted as solutions to your challenge going to be? Please describe in detail what the output(s) reflect(s), for example, probability of a positive PCR result, or stroke lesion segmentation. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="challenge_publication",
            field=models.TextField(
                blank=True,
                help_text="Please indicate if you plan to coordinate a publication of the challenge results.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="challenge_setup",
            field=models.TextField(
                blank=True,
                help_text="Describe the challenge set-up from a technical stand-point. How many tasks and <a href='https://www.grand-challenge.org/documentation/multiple-phases-multiple-leaderboards/' target='_blank'>phases</a> does the challenge have? Which <a href='https://grand-challenge.org/documentation/runtime-environment/' target='_blank'>runtime environment</a> do you envision for the challenge?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="code_availability",
            field=models.TextField(
                blank=True,
                help_text="Will the participants’ code be accessible after the challenge? <br>We strongly encourage open science. Algorithms submitted as challenge solutions will therefore be stored on Grand Challenge and we encourage organizers to incentivize an open source policy, for example by asking participants to publish their Github repo under an <a href='https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository' target='_blank'> open source license</a> (e.g., Apache 2.0, MIT) and <a href='https://grand-challenge.org/documentation/linking-a-github-repository-to-your-algorithm/'>link it to their algorithm</a> on Grand Challenge.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="contact_email",
            field=models.EmailField(
                help_text="The email address that potential participants can use to contact you with questions about the challenge. This email address will be visible on the challenge website, so please provide an address that you are comfortable sharing publicly.",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="data_license",
            field=models.BooleanField(
                default=False,
                help_text="In the spirit of open science, we ask that the <b>public training data</b> are released under a <a href='https://creativecommons.org/licenses/' target='_blank'>CC-BY license</a>. Note that this does not apply to the secret test data used to evaluate algorithm submissions. Read more about this <a href='https://grand-challenge.org/documentation/data-storage/'>here</a>.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="data_set",
            field=models.TextField(
                blank=True,
                help_text="Please describe the training and test datasets you are planning to use. <br>In order to evaluate the submitted algorithms, the test dataset will need to be uploaded to Grand Challenge (read more about that <a href='https://grand-challenge.org/documentation/data-storage/' target='_blank'>here</a>).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Estimated end date for this challenge. Please note that we aim to keep challenges open for submission for at least 3 years after the official end date if possible.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="organizers",
            field=models.TextField(
                blank=True,
                help_text="Provide information about the organizing team (names and affiliations)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Estimated start date for this challenge.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="structured_challenge_submission_doi",
            field=grandchallenge.publications.fields.IdentifierField(
                blank=True,
                help_text="The DOI, e.g., 10.5281/zenodo.6362337, or the arXiv id, e.g., 2006.12449 of your challenge submission PDF.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="submission_assessment",
            field=models.TextField(
                blank=True,
                help_text="Define the metrics you will use to assess and rank participants’ submissions.",
                null=True,
            ),
        ),
    ]
