# Generated by Django 5.2.12 on 2026-03-10 13:35

from django.db import migrations
from django.db.models import F


def set_submitted_on(apps, _schema_editor):
    ChallengeRequest = apps.get_model(  # noqa: N806
        "challenges", "ChallengeRequest"
    )

    ChallengeRequest.objects.exclude(status="DRFT").update(
        submitted_on=F("created")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0066_alter_challengerequest_options_and_more"),
    ]

    operations = [
        migrations.RunPython(set_submitted_on, elidable=True),
    ]
