# Generated by Django 5.2.12 on 2026-03-05 12:17

from django.db import migrations, models

import grandchallenge.publications.fields


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0066_alter_challengerequest_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengerequest",
            name="abstract",
            field=models.TextField(
                help_text="Provide a summary of the challenge purpose.",
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="algorithm_inputs",
            field=models.TextField(
                blank=True,
                help_text="What are the inputs to the algorithms submitted as solutions to your challenge going to be? Please describe in detail what the input(s) reflect(s), for example, MRI scan of the brain, or chest X-ray. Grand Challenge only supports .mha and .tiff image files and json files for algorithms.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="algorithm_outputs",
            field=models.TextField(
                blank=True,
                help_text="What are the outputs to the algorithms submitted as solutions to your challenge going to be? Please describe in detail what the output(s) reflect(s), for example, probability of a positive PCR result, or stroke lesion segmentation. ",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="challenge_publication",
            field=models.TextField(
                blank=True,
                help_text="Please indicate if you plan to coordinate a publication of the challenge results.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="challenge_setup",
            field=models.TextField(
                blank=True,
                help_text="Describe the challenge set up.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="code_availability",
            field=models.TextField(
                blank=True,
                help_text="Will the participants’ code be accessible after the challenge?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="data_license",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="data_set",
            field=models.TextField(
                blank=True,
                help_text="Describe the training and test datasets you are planning to use.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Estimated end date for this challenge. Please note that we aim to keep challenges open for submission for at least 3 years after the official end date if possible.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="organizers",
            field=models.TextField(
                blank=True,
                help_text="Provide information about the organizing team (names and affiliations)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Estimated start date for this challenge.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="structured_challenge_submission_doi",
            field=grandchallenge.publications.fields.IdentifierField(
                blank=True,
                help_text="The DOI, e.g., 10.5281/zenodo.6362337, or the arXiv id, e.g., 2006.12449 of your challenge submission PDF.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="submission_assessment",
            field=models.TextField(
                blank=True,
                help_text="Define the metrics you will use to assess and rank participants’ submissions.",
                null=True,
            ),
        ),
    ]
