# Generated by Django 5.2.12 on 2026-03-10 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anatomy", "0002_alter_bodyregion_region_and_more"),
        ("challenges", "0067_auto_20260310_1335"),
        ("incentives", "0002_alter_incentive_incentive"),
        ("modalities", "0002_alter_imagingmodality_modality"),
        ("task_categories", "0002_alter_tasktype_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="challengerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "DRFT"),
                    ("submitted_on__isnull", False),
                    _connector="OR",
                ),
                name="submitted_or_draft",
                violation_error_message="When setting the status to something other than a 'Draft', 'Submitted On' must also be set.",
            ),
        ),
    ]
