# Generated by Django 5.2.13 on 2026-04-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0070_assign_review_perm_to_reviewers_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACPT", "Accepted"),
                    ("RJCT", "Rejected"),
                    ("PEND", "Pending"),
                    ("DRFT", "Draft"),
                    ("CNCL", "Cancelled"),
                ],
                default="DRFT",
                max_length=4,
            ),
        ),
    ]
