# Generated by Django 5.2.13 on 2026-04-09 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anatomy", "0002_alter_bodyregion_region_and_more"),
        ("challenges", "0070_assign_review_perm_to_reviewers_group"),
        ("incentives", "0002_alter_incentive_incentive"),
        ("modalities", "0002_alter_imagingmodality_modality"),
        ("task_categories", "0002_alter_tasktype_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACPT", "Accepted"),
                    ("RJCT", "Rejected"),
                    ("PEND", "Pending"),
                    ("DRFT", "Draft"),
                    ("CNCL", "Cancelled"),
                ],
                default="DRFT",
                max_length=4,
            ),
        ),
        migrations.AddConstraint(
            model_name="challengerequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["ACPT", "RJCT", "PEND", "DRFT", "CNCL"])
                ),
                name="status_in_choices",
            ),
        ),
    ]
