# Generated by Django 5.2.14 on 2026-06-08 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0071_alter_challengerequest_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="compute_cost_euro_millicents",
            field=models.PositiveBigIntegerField(
                default=0,
                editable=False,
                help_text="The total compute cost for this challenge in Euro Cents, including Tax",
                null=True,
            ),
        ),
    ]
