# Generated by Django 5.2.14 on 2026-06-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0071_alter_challengerequest_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="compute_cost_euro_millicents",
        ),
    ]
