# Generated by Django 5.2.15 on 2026-06-24 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0072_alter_challenge_compute_cost_euro_millicents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="compute_cost_euro_millicents",
        ),
    ]
