# Generated by Django 5.2.14 on 2026-05-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0072_alter_challenge_compute_cost_euro_millicents"),
    ]

    operations = [
        migrations.AddField(
            model_name="challengerequest",
            name="draft_reminder_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Number of reminders sent to the challenge organizers to submit this draft for review.",
            ),
        ),
    ]
