# Generated by Django 5.2.15 on 2026-06-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0073_remove_challenge_compute_cost_euro_millicents"),
    ]

    operations = [
        migrations.RenameField(
            model_name="challengerequest",
            old_name="algorithm_selectable_gpu_type_choices_for_tasks",
            new_name="algorithm_selectable_gpu_type_choices",
        ),
        migrations.AddField(
            model_name="challengerequest",
            name="algorithm_maximum_settable_memory_gb",
            field=models.PositiveIntegerField(
                help_text="Maximum amount of main memory (DRAM) that participants will be allowed to assign to algorithm inference jobs for submission.",
                null=True,
            ),
        ),
    ]
