# Generated by Django 5.2.15 on 2026-06-25 08:08

from django.db import migrations


def migrate_challenge_request_fields(apps, schema_editor):
    ChallengeRequest = apps.get_model(  # noqa: N806
        "challenges", "ChallengeRequest"
    )

    objects_to_update = []
    for cr in ChallengeRequest.objects.all():
        if cr.algorithm_selectable_gpu_type_choices:
            cr.algorithm_selectable_gpu_type_choices = (
                cr.algorithm_selectable_gpu_type_choices[0]
            )
        else:
            cr.algorithm_selectable_gpu_type_choices = [""]

        if "A100" in cr.algorithm_selectable_gpu_type_choices:
            cr.algorithm_selectable_gpu_type_choices = [
                "",
                "T4",
                "A10G",
                "A100",
            ]
        elif "A10G" in cr.algorithm_selectable_gpu_type_choices:
            cr.algorithm_selectable_gpu_type_choices = ["", "T4", "A10G"]
        elif "T4" in cr.algorithm_selectable_gpu_type_choices:
            cr.algorithm_selectable_gpu_type_choices = ["", "T4"]

        if cr.algorithm_maximum_settable_memory_gb_for_tasks:
            cr.algorithm_maximum_settable_memory_gb = (
                cr.algorithm_maximum_settable_memory_gb_for_tasks[0]
            )
        else:
            cr.algorithm_maximum_settable_memory_gb = 32

        objects_to_update.append(cr)

    ChallengeRequest.objects.bulk_update(
        objects_to_update,
        fields=[
            "algorithm_selectable_gpu_type_choices",
            "algorithm_maximum_settable_memory_gb",
        ],
    )


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0074_rename_algorithm_selectable_gpu_type_choices_for_tasks_challengerequest_algorithm_selectable_gpu_typ",
        ),
    ]

    operations = [
        migrations.RunPython(migrate_challenge_request_fields, elidable=True),
    ]
