# Generated by Django 5.2.15 on 2026-06-25 09:02

from django.db import migrations, models

import grandchallenge.challenges.models
import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0075_auto_20260625_0808"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengerequest",
            name="algorithm_maximum_settable_memory_gb_for_tasks",
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="algorithm_maximum_settable_memory_gb",
            field=models.PositiveIntegerField(
                default=32,
                help_text="Maximum amount of main memory (DRAM) that participants will be allowed to assign to algorithm inference jobs for submission.",
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="algorithm_selectable_gpu_type_choices",
            field=models.JSONField(
                default=grandchallenge.challenges.models.default_selectable_gpu_types,
                help_text='The GPU type choices that participants will be able to select for their algorithm inference jobs. Options are ["", "A100", "A10G", "V100", "K80", "T4"].',
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema",
                            "items": {
                                "enum": [
                                    "",
                                    "A100",
                                    "A10G",
                                    "V100",
                                    "K80",
                                    "T4",
                                ],
                                "type": "string",
                            },
                            "title": "The Selectable GPU Types Schema",
                            "type": "array",
                            "uniqueItems": True,
                        }
                    )
                ],
            ),
        ),
    ]
