# Generated by Django 5.2.15 on 2026-06-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0075_auto_20260625_0808"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challengerequest",
            name="algorithm_maximum_settable_memory_gb_for_tasks",
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="algorithm_maximum_settable_memory_gb",
            field=models.PositiveIntegerField(
                default=32,
                help_text="Maximum amount of main memory (DRAM) that participants will be allowed to assign to algorithm inference jobs for submission.",
            ),
        ),
    ]
