# Generated by Django 5.2.13 on 2026-04-21 11:04

from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0076_remove_challengerequest_algorithm_maximum_settable_memory_gb_for_tasks_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challengerequest",
            name="average_size_job_output_mb_for_tasks",
            field=models.JSONField(
                default=list,
                help_text="Average size of the output per job in MB, for each task.",
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema",
                            "items": {
                                "maximum": 10000,
                                "minimum": 0,
                                "type": "integer",
                            },
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
    ]
