# Generated by Django 5.2.15 on 2026-07-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "challenges",
            "0076_remove_challengerequest_algorithm_maximum_settable_memory_gb_for_tasks_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="challengerequest",
            name="draft_reminder_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                editable=False,
                help_text="Number of reminders sent to the challenge organizers to submit this draft for review.",
            ),
        ),
    ]
