# Generated by Django 5.2.17 on 2026-08-28 10:18

from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0079_set_average_size_job_output_for_tasks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challengerequest",
            name="average_size_test_case_mb_for_tasks",
            field=models.JSONField(
                default=list,
                help_text="Average size of a test case in MB, for each task.",
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema",
                            "items": {
                                "maximum": 10000,
                                "minimum": 1,
                                "type": "integer",
                            },
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="challengerequest",
            name="number_of_test_cases_for_phases",
            field=models.JSONField(
                default=list,
                help_text="Number of test cases for each phase.",
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema",
                            "items": {"minimum": 1, "type": "integer"},
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
    ]
