# Generated by Django 3.0.10 on 2020-09-28 09:55

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "email_is_verified",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
