# Generated by Django 3.1.1 on 2020-12-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("verifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="verification",
            name="is_verified",
            field=models.BooleanField(default=None, editable=False, null=True),
        ),
    ]
