# Generated by Django 4.1.10 on 2023-07-22 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("verifications", "0003_alter_verification_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerificationUserSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VerificationUserSetUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="verifications.verificationuserset",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="verificationuserset",
            name="users",
            field=models.ManyToManyField(
                through="verifications.VerificationUserSetUser",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
