# Generated by Django 4.2.17 on 2025-01-08 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("verifications", "0006_verificationuserset_auto_deactivate_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="verificationusersetuser",
            unique_together={("user_set", "user")},
        ),
    ]
