# Generated by Django 5.2.16 on 2026-07-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "verifications",
            "0007_alter_verificationusersetuser_unique_together",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="verification",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
