# Generated by Django 5.2.11 on 2026-03-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CeleryTaskDailyStats",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("task_name", models.CharField(max_length=255)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                (
                    "avg_duration",
                    models.DurationField(
                        help_text="Average duration of successful jobs on date",
                        null=True,
                    ),
                ),
                (
                    "min_duration",
                    models.DurationField(
                        help_text="Minimum duration of successful jobs on date",
                        null=True,
                    ),
                ),
                (
                    "max_duration",
                    models.DurationField(
                        help_text="Maximum duration of successful jobs on date",
                        null=True,
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "task_name")},
            },
        ),
    ]
