# Generated by Django 5.2.14 on 2026-06-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("background_tasks", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CeleryTaskDailyStats",
        ),
    ]
