# Generated by Django 3.1.6 on 2021-02-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("retina_api", "0002_auto_20201001_0758"),
    ]

    operations = [
        migrations.DeleteModel(name="ArchiveDataModel",),
    ]
