# Generated by Django 5.2.14 on 2026-06-09 07:56

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IgnoredPattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "pattern",
                    models.CharField(
                        help_text="Regex pattern for paths to ignore.",
                        max_length=512,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BrokenLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("domain", models.CharField(max_length=255)),
                ("path", models.TextField()),
                ("referer", models.TextField()),
                ("user_agent", models.TextField()),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("is_internal", models.BooleanField()),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["-created"],
                        name="broken_link_created_4d8ee6_idx",
                    )
                ],
            },
        ),
    ]
