# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uploadmodel',
            table=None,
        ),
    ]
