# Generated by Django 2.1.7 on 2019-02-25 14:22

from django.db import migrations, models

import grandchallenge.core.storage
import grandchallenge.jqfileupload.models


class Migration(migrations.Migration):

    dependencies = [("jqfileupload", "0002_longer_filenames_and_upload_path")]

    operations = [
        migrations.AlterField(
            model_name="stagedfile",
            name="file",
            field=models.FileField(
                max_length=256,
                storage=grandchallenge.core.storage.PrivateS3Storage(),
                upload_to=grandchallenge.jqfileupload.models.generate_upload_filename,
            ),
        )
    ]
