# Generated by Django 2.0.6 on 2018-06-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqfileupload', '0002_auto_20180615_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagedfile',
            name='upload_path',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
