# Generated by Django 2.0.6 on 2018-06-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqfileupload', '0003_stagedfile_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagedfile',
            name='upload_path',
            field=models.CharField(max_length=256),
        ),
    ]
