# Generated by Django 3.1.13 on 2021-11-01 20:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jqfileupload", "0004_auto_20190911_1210"),
    ]

    operations = [
        migrations.DeleteModel(name="StagedFile"),
    ]
