# Generated by Django 2.0.6 on 2018-06-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jqfileupload', '0004_auto_20180628_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stagedfile',
            name='upload_path',
        ),
        migrations.AddField(
            model_name='stagedfile',
            name='upload_path_sha256',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
