# Generated by Django 2.1.7 on 2019-02-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
