# Generated by Django 2.1.7 on 2019-04-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_data', '0003_auto_20190415_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datafile',
            old_name='description',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='data_files',
            new_name='additional_data_files',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='image',
            new_name='banner_image_url',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='frozen',
        ),
        migrations.RemoveField(
            model_name='datafile',
            name='original_file_name',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='description',
        ),
        migrations.AddField(
            model_name='datafile',
            name='format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Short description of this file in plain text.', null=True),
        ),
        migrations.AddField(
            model_name='datafile',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='banner_image_alttext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='card_image_alttext',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='card_image_url',
            field=models.CharField(default='https://www.staging.eyrabenchmark.net/static/media/logo.3fc4ddae.png', help_text='DataSet image', max_length=255),
        ),
        migrations.AddField(
            model_name='dataset',
            name='long_description',
            field=models.TextField(blank=True, default='', help_text='Long description of this data set in markdown.', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='related_datasets',
            field=models.ManyToManyField(blank=True, related_name='related_data_sets', to='eyra_data.DataSet'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='short_description',
            field=models.TextField(blank=True, default='', help_text='Short description of this data set in plaintext.', null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='version',
            field=models.CharField(blank=True, help_text='The Dataset version', max_length=64, null=True),
        ),
    ]
