# Generated by Django 2.1.8 on 2019-06-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_data', '0004_auto_20190416_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='banner_image_url',
            field=models.CharField(default='https://www.staging.eyrabenchmark.net/static/media/logo.3fc4ddae.png', help_text='DataSet banner image', max_length=255),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='card_image_url',
            field=models.CharField(default='https://www.staging.eyrabenchmark.net/static/media/logo.3fc4ddae.png', help_text='DataSet card image', max_length=255),
        ),
    ]
