# Generated by Django 3.0.6 on 2020-06-15 14:57

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import grandchallenge.cases.models
import grandchallenge.core.storage


class Migration(migrations.Migration):
    replaces = [
        ("cases", "0001_initial"),
        ("cases", "0002_auto_20180814_1506"),
        ("cases", "0003_auto_20180821_1045"),
        ("cases", "0004_auto_20180822_1521"),
        ("cases", "0005_auto_20180825_1006"),
        ("cases", "0006_auto_20180830_1524"),
        ("cases", "0007_auto_20180909_0513"),
        ("cases", "0008_auto_20190201_1312"),
        ("cases", "0009_auto_20190204_1517"),
        ("cases", "0010_auto_20190219_1301"),
        ("cases", "0011_auto_20190314_1453"),
        ("cases", "0012_auto_20190710_1334"),
        ("cases", "0013_rawimageuploadsession_reader_study"),
        ("cases", "0014_auto_20190828_1655"),
        ("cases", "0015_auto_20191003_1323"),
        ("cases", "0016_image_timepoints"),
        ("cases", "0017_auto_20191205_0859"),
        ("cases", "0018_auto_20191218_0936"),
        ("cases", "0019_auto_20200120_0604"),
        ("cases", "0020_add_dicom_group"),
        ("cases", "0021_rawimageuploadsession_archive"),
        ("cases", "0022_auto_20200325_1151"),
        ("cases", "0023_auto_20200521_1052"),
        ("cases", "0024_auto_20200525_0634"),
    ]

    dependencies = [
        ("studies", "0001_initial"),
        ("reader_studies", "0001_initial"),
        ("algorithms", "0001_squashed_0004_auto_20180814_1508"),
        ("datasets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0017_auto_20181214_1256"),
        ("algorithms", "0002_auto_20180909_0513"),
        ("archives", "0003_auto_20200322_0921"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawImageUploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(default=None, null=True)),
                (
                    "annotationset",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datasets.AnnotationSet",
                    ),
                ),
                (
                    "imageset",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="datasets.ImageSet",
                    ),
                ),
                (
                    "algorithm_image",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithms.Algorithm",
                    ),
                ),
                (
                    "algorithm_result",
                    models.OneToOneField(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithms.Result",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reader_study",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reader_studies.ReaderStudy",
                    ),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Queued"),
                            (1, "Started"),
                            (2, "Re-Queued"),
                            (3, "Failed"),
                            (4, "Succeeded"),
                            (5, "Cancelled"),
                        ],
                        default=0,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="RawImageFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=128)),
                ("staged_file_id", models.UUIDField(blank=True, null=True)),
                ("error", models.TextField(default=None, null=True)),
                (
                    "upload_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.RawImageUploadSession",
                    ),
                ),
                ("consumed", models.BooleanField(default=False)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("depth", models.IntegerField(null=True)),
                (
                    "color_space",
                    models.CharField(
                        choices=[
                            ("GRAY", "GRAY"),
                            ("RGB", "RGB"),
                            ("RGBA", "RGBA"),
                            ("YCBCR", "YCBCR"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cases.RawImageUploadSession",
                    ),
                ),
                ("resolution_levels", models.IntegerField(null=True)),
                (
                    "eye_choice",
                    models.CharField(
                        choices=[
                            ("OD", "Oculus Dexter (right eye)"),
                            ("OS", "Oculus Sinister (left eye)"),
                            ("U", "Unknown"),
                            ("NA", "Not applicable"),
                        ],
                        default="NA",
                        help_text="Is this (retina) image from the right or left eye?",
                        max_length=2,
                    ),
                ),
                (
                    "modality",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="challenges.ImagingModality",
                    ),
                ),
                (
                    "study",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studies.Study",
                    ),
                ),
                (
                    "field_of_view",
                    models.CharField(
                        choices=[
                            ("F1M", "F1M"),
                            ("F2", "F2"),
                            ("F3M", "F3M"),
                            ("F4", "F4"),
                            ("F5", "F5"),
                            ("F6", "F6"),
                            ("F7", "F7"),
                            ("U", "Unknown"),
                            (None, "Not applicable"),
                        ],
                        default=None,
                        help_text="What is the field of view of this image?",
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "stereoscopic_choice",
                    models.CharField(
                        choices=[
                            ("L", "Left"),
                            ("R", "Right"),
                            ("U", "Unknown"),
                            (None, "Not applicable"),
                        ],
                        default=None,
                        help_text="Is this the left or right image of a stereoscopic pair?",
                        max_length=1,
                        null=True,
                    ),
                ),
                ("timepoints", models.IntegerField(null=True)),
                ("voxel_depth_mm", models.FloatField(null=True)),
                ("voxel_height_mm", models.FloatField(null=True)),
                ("voxel_width_mm", models.FloatField(null=True)),
            ],
            options={"abstract": False, "ordering": ("name",)},
        ),
        migrations.CreateModel(
            name="ImageFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        storage=grandchallenge.core.storage.ProtectedS3Storage(),
                        upload_to=grandchallenge.cases.models.image_file_path,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="cases.Image",
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("MHD", "MHD"),
                            ("TIFF", "TIFF"),
                            ("DZI", "DZI"),
                        ],
                        default="MHD",
                        max_length=4,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="rawimageuploadsession",
            name="archive",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archives.Archive",
            ),
        ),
        migrations.AlterField(
            model_name="rawimagefile",
            name="filename",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="image",
            name="name",
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name="rawimagefile",
            name="filename",
            field=models.CharField(max_length=4096),
        ),
        migrations.AddField(
            model_name="image",
            name="window_center",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="window_width",
            field=models.FloatField(null=True),
        ),
    ]
