# Generated by Django 3.1.6 on 2021-03-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modalities", "0001_initial"),
        ("studies", "0001_initial"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="depth",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="field_of_view",
            field=models.CharField(
                blank=True,
                choices=[
                    ("F1M", "F1M"),
                    ("F2", "F2"),
                    ("F3M", "F3M"),
                    ("F4", "F4"),
                    ("F5", "F5"),
                    ("F6", "F6"),
                    ("F7", "F7"),
                    ("U", "Unknown"),
                    (None, "Not applicable"),
                ],
                default=None,
                help_text="What is the field of view of this image?",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="modality",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="modalities.imagingmodality",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="cases.rawimageuploadsession",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="resolution_levels",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="stereoscopic_choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L", "Left"),
                    ("R", "Right"),
                    ("U", "Unknown"),
                    (None, "Not applicable"),
                ],
                default=None,
                help_text="Is this the left or right image of a stereoscopic pair?",
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="study",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="studies.study",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="timepoints",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="voxel_depth_mm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="voxel_height_mm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="voxel_width_mm",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="window_center",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="window_width",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
