# Generated by Django 2.0.8 on 2018-08-14 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0001_squashed_0004_auto_20180814_1508"),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="case", name="creator"),
        migrations.RemoveField(model_name="casefile", name="case"),
        migrations.DeleteModel(name="Case"),
        migrations.DeleteModel(name="CaseFile"),
    ]
