# Generated by Django 2.0.4 on 2018-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='stage',
            field=models.CharField(choices=[('TRAIN', 'Training'), ('TEST', 'Testing'), ('NONE', 'None')], default='NONE', max_length=5),
        ),
    ]
