# Generated by Django 2.0.8 on 2018-08-16 12:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20180814_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField()),
                ('annotation_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='cases.Image')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
