# Generated by Django 2.0.6 on 2018-06-11 12:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20180611_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawimagefile',
            name='created_on',
        ),
        migrations.AddField(
            model_name='rawimageuploadsession',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='rawimagefile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jqfileupload.StagedFile'),
        ),
    ]
