# Generated by Django 2.0.6 on 2018-06-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20180613_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawimagefile',
            name='error',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
    ]
