# Generated by Django 2.0.6 on 2018-06-11 12:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20180611_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawimageuploadsession',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
