# Generated by Django 2.0.6 on 2018-06-12 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20180611_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawimagefile',
            name='file',
        ),
    ]
