# Generated by Django 2.0.6 on 2018-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_auto_20180621_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawimageuploadsession',
            name='processing_task',
            field=models.UUIDField(default=None, null=True),
        ),
    ]
