# Generated by Django 3.1.13 on 2021-10-08 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_auto_20210929_1055"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="study",),
    ]
