# Generated by Django 2.0.8 on 2018-08-25 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cases", "0004_auto_20180822_1521")]

    operations = [
        migrations.RemoveField(model_name="annotation", name="base"),
        migrations.RemoveField(model_name="annotation", name="image"),
        migrations.DeleteModel(name="Annotation"),
    ]
