# Generated by Django 2.0.6 on 2018-06-25 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_rawimageuploadsession_processing_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_handle',
        ),
        migrations.AddField(
            model_name='image',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.RawImageUploadSession'),
        ),
    ]
