# Generated by Django 3.1.13 on 2021-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("uploads", "0004_auto_20211012_0957"),
        ("cases", "0005_rawimageuploadsession_import_result"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawimageuploadsession",
            name="user_uploads",
            field=models.ManyToManyField(
                blank=True,
                related_name="image_upload_sessions",
                to="uploads.UserUpload",
            ),
        ),
    ]
