# Generated by Django 2.0.6 on 2018-06-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_remove_rawimagefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawimagefile',
            name='staged_file_id',
            field=models.UUIDField(default=None),
            preserve_default=False,
        ),
    ]
