# Generated by Django 2.0.8 on 2018-08-30 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("cases", "0005_auto_20180825_1006")]

    operations = [
        migrations.AlterModelOptions(
            name="image", options={"ordering": ("name",)}
        )
    ]
