# Generated by Django 2.0.6 on 2018-06-25 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20180625_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
