# Generated by Django 3.1.13 on 2021-10-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0006_rawimageuploadsession_user_uploads"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="study",),
    ]
