# Generated by Django 2.1.4 on 2018-12-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
        ('challenges', '0015_remove_challenge_allow_unfiltered_page_html'),
        ('cases', '0007_auto_20180909_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='eye_choice',
            field=models.CharField(choices=[('OD', 'Oculus Dexter (right eye)'), ('OS', 'Oculus Sinister (left eye)'), ('U', 'Unknown'), ('NA', 'Not applicable')], default='NA', help_text='Is this (retina) image from the right or left eye?', max_length=2),
        ),
        migrations.AddField(
            model_name='image',
            name='modality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.ImagingModality'),
        ),
        migrations.AddField(
            model_name='image',
            name='study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='studies.Study'),
        ),
    ]
