# Generated by Django 2.0.6 on 2018-06-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_image_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='color_space',
            field=models.CharField(choices=[('GRAY', 'GRAY'), ('RGB', 'RGB'), ('RGB', 'RGBA')], default='GRAY', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='depth',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.IntegerField(null=True),
        ),
    ]
