# Generated by Django 2.1.5 on 2019-02-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
        ("challenges", "0017_auto_20181214_1256"),
        ("cases", "0008_auto_20190201_1312"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="eye_choice",
            field=models.CharField(
                choices=[
                    ("OD", "Oculus Dexter (right eye)"),
                    ("OS", "Oculus Sinister (left eye)"),
                    ("U", "Unknown"),
                    ("NA", "Not applicable"),
                ],
                default="NA",
                help_text="Is this (retina) image from the right or left eye?",
                max_length=2,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="modality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="challenges.ImagingModality",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="study",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="studies.Study",
            ),
        ),
    ]
