# Generated by Django 3.2.13 on 2022-06-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0008_delete_rawimagefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="post_processed",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
