# Generated by Django 3.2.13 on 2022-06-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0008_delete_rawimagefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagefile",
            name="post_processed",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
