# Generated by Django 2.0.6 on 2018-06-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0008_auto_20180625_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
