# Generated by Django 3.2.14 on 2022-07-07 17:50

from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0009_imagefile_post_processed"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="segments",
            field=models.JSONField(
                blank=True,
                null=True,
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema",
                            "items": {
                                "$id": "#/items",
                                "maxItems": 32,
                                "type": "integer",
                            },
                            "title": "The Segments Schema",
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
    ]
