# Generated by Django 2.1.7 on 2019-02-19 13:01

from django.db import migrations, models

import grandchallenge.cases.models
import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [("cases", "0009_auto_20190204_1517")]

    operations = [
        migrations.AlterField(
            model_name="imagefile",
            name="file",
            field=models.FileField(
                storage=grandchallenge.core.storage.ProtectedS3Storage(),
                upload_to=grandchallenge.cases.models.image_file_path,
            ),
        )
    ]
