# Generated by Django 2.1.5 on 2019-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0009_auto_20190124_1001")]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="color_space",
            field=models.CharField(
                choices=[
                    ("GRAY", "GRAY"),
                    ("RGB", "RGB"),
                    ("RGBA", "RGBA"),
                    ("YCBCR", "YCBCR"),
                ],
                max_length=5,
            ),
        )
    ]
