# Generated by Django 2.1.7 on 2019-03-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0010_auto_20190219_1301")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="field_of_view",
            field=models.CharField(
                choices=[
                    ("F1M", "F1M"),
                    ("F2", "F2"),
                    ("F3M", "F3M"),
                    ("F4", "F4"),
                    ("F5", "F5"),
                    ("F6", "F6"),
                    ("F7", "F7"),
                    ("U", "Unknown"),
                    (None, "Not applicable"),
                ],
                default=None,
                help_text="What is the field of view of this image?",
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="stereoscopic_choice",
            field=models.CharField(
                choices=[
                    ("L", "Left"),
                    ("R", "Right"),
                    ("U", "Unknown"),
                    (None, "Not applicable"),
                ],
                default=None,
                help_text="Is this the left or right image of a stereoscopic pair?",
                max_length=1,
                null=True,
            ),
        ),
    ]
