# Generated by Django 2.2.3 on 2019-07-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0011_auto_20190314_1453")]

    operations = [
        migrations.AlterField(
            model_name="imagefile",
            name="image_type",
            field=models.CharField(
                choices=[("MHD", "MHD"), ("TIFF", "TIFF"), ("DZI", "DZI")],
                default="MHD",
                max_length=4,
            ),
        )
    ]
