# Generated by Django 2.2.2 on 2019-06-11 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0001_initial"),
        ("cases", "0011_auto_20190314_1453"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawimageuploadsession",
            name="readerstudy",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reader_studies.ReaderStudy",
            ),
        )
    ]
