# Generated by Django 3.2.18 on 2023-03-07 14:38

from django.db import migrations, models

import grandchallenge.cases.models
import grandchallenge.core.storage


class Migration(migrations.Migration):
    dependencies = [
        (
            "cases",
            "0011_imagegroupobjectpermission_imageuserobjectpermission_rawimageuploadsessiongroupobjectpermission_rawi",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagefile",
            name="file",
            field=models.FileField(
                max_length=200,
                storage=grandchallenge.core.storage.ProtectedS3Storage(),
                upload_to=grandchallenge.cases.models.image_file_path,
            ),
        ),
    ]
