# Generated by Django 4.1.10 on 2023-07-17 14:52

from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0012_alter_imagefile_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="segments",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema",
                            "items": {
                                "$id": "#/items",
                                "maxItems": 64,
                                "type": "integer",
                            },
                            "title": "The Segments Schema",
                            "type": "array",
                            "uniqueItems": True,
                        }
                    )
                ],
            ),
        ),
    ]
