# Generated by Django 2.2.4 on 2019-08-14 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader_studies", "0001_initial"),
        ("cases", "0012_auto_20190710_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawimageuploadsession",
            name="reader_study",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reader_studies.ReaderStudy",
            ),
        )
    ]
