# Generated by Django 4.1.8 on 2023-05-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0012_alter_imagefile_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="max_voxel_value",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="min_voxel_value",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
