# Generated by Django 4.1.10 on 2023-08-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0013_alter_image_segments"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="storage_cost_per_month_usd_cents",
            field=models.PositiveSmallIntegerField(
                default=None,
                editable=False,
                help_text="The storage cost per month for this image in USD Cents, excluding Tax",
                null=True,
            ),
        ),
    ]
