# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0014_imagefile_size_in_storage"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="imagegroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="cases_image_group_i_04c912_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="imageuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="cases_image_user_id_62ed5d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawimageuploadsessionuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="cases_rawim_user_id_768683_idx",
            ),
        ),
    ]
