# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cases",
            "0015_imagegroupobjectpermission_cases_image_group_i_04c912_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rawimageuploadsessiongroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="cases_rawim_group_i_1ab41f_idx",
            ),
        ),
    ]
