# Generated by Django 2.2.7 on 2019-12-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0016_image_timepoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="voxel_depth_mm",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="voxel_height_mm",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="voxel_width_mm",
            field=models.FloatField(null=True),
        ),
    ]
