# Generated by Django 2.2.7 on 2019-11-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0016_image_timepoints")]

    operations = [
        migrations.AddField(
            model_name="image",
            name="pixel_height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="pixel_width",
            field=models.FloatField(null=True),
        ),
    ]
