# Generated by Django 4.2.23 on 2025-08-14 09:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cases",
            "0016_rawimageuploadsessiongroupobjectpermission_cases_rawim_group_i_1ab41f_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imagefile",
            name="post_processed",
        ),
        migrations.CreateModel(
            name="PostProcessImageTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZED", "Initialized"),
                            ("CANCELLED", "Cancelled"),
                            ("FAILED", "Failed"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="INITIALIZED",
                        max_length=12,
                    ),
                ),
                (
                    "image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cases.image",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-created"],
                        name="cases_postp_created_46388a_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="postprocessimagetask",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        ["INITIALIZED", "CANCELLED", "FAILED", "COMPLETED"],
                    )
                ),
                name="valid_post_process_image_task_status",
            ),
        ),
    ]
