# Generated by Django 4.2.23 on 2025-08-28 08:21

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "uploads",
            "0009_useruploadgroupobjectpermission_uploads_use_group_i_53998e_idx",
        ),
        (
            "cases",
            "0017_remove_imagefile_post_processed_postprocessimagetask_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DICOMImageSetUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZED", "Initialized"),
                            ("STARTED", "Started"),
                            ("FAILED", "Failed"),
                        ],
                        default="INITIALIZED",
                        max_length=11,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "creator",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_uploads",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dicom_import_jobs",
                        to="uploads.userupload",
                    ),
                ),
            ],
            options={
                "verbose_name": "DICOM image set upload",
                "indexes": [
                    models.Index(
                        fields=["status"], name="cases_dicom_status_957c53_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="dicomimagesetupload",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["INITIALIZED", "STARTED", "FAILED"])
                ),
                name="dicomuimagesetupload_status_valid",
            ),
        ),
    ]
