# Generated by Django 2.2.8 on 2019-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0017_auto_20191205_0859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawimagefile",
            name="error",
            field=models.TextField(default=None, null=True),
        ),
    ]
