# Generated by Django 4.2.23 on 2025-08-27 09:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "uploads",
            "0009_useruploadgroupobjectpermission_uploads_use_group_i_53998e_idx",
        ),
        (
            "cases",
            "0017_remove_imagefile_post_processed_postprocessimagetask_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DicomImageSetUpload",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIALIZED", "Initialized"),
                            ("PENDING", "Queued"),
                            ("DEIDENTIFYING", "De-Identifying"),
                            ("DEIDENTIFIED", "De-Identified"),
                            ("STARTED", "Importing"),
                            ("REQUEUED", "Re-Queued"),
                            ("FAILURE", "Failed"),
                            ("SUCCESS", "Succeeded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=13,
                    ),
                ),
                ("error_message", models.TextField(default=None, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_uploads",
                    models.ManyToManyField(
                        blank=True,
                        related_name="dicom_import_jobs",
                        to="uploads.userupload",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
