# Generated by Django 4.2.24 on 2025-10-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "uploads",
            "0009_useruploadgroupobjectpermission_uploads_use_group_i_53998e_idx",
        ),
        ("cases", "0018_alter_image_color_space_alter_image_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dicomimagesetupload",
            name="user_uploads",
            field=models.ManyToManyField(
                blank=True,
                related_name="dicom_image_set_uploads",
                to="uploads.userupload",
            ),
        ),
    ]
