# Generated by Django 4.2.23 on 2025-08-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_dicomimagesetupload_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dicomimagesetupload",
            name="dicomuimagesetupload_status_valid",
        ),
        migrations.AlterField(
            model_name="dicomimagesetupload",
            name="status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("STARTED", "Started"),
                    ("FAILED", "Failed"),
                    ("COMPLETED", "Completed"),
                ],
                default="INITIALIZED",
                max_length=11,
            ),
        ),
        migrations.AddConstraint(
            model_name="dicomimagesetupload",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        ["INITIALIZED", "STARTED", "FAILED", "COMPLETED"],
                    )
                ),
                name="dicomuimagesetupload_status_valid",
            ),
        ),
    ]
