# Generated by Django 2.2.9 on 2020-01-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0018_auto_20191218_0936")]

    operations = [
        migrations.AddField(
            model_name="rawimagefile",
            name="consumed",
            field=models.BooleanField(default=False),
        )
    ]
