# Generated by Django 4.2.25 on 2025-10-08 08:22

from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_alter_image_color_space_alter_image_height_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dicomimageset",
            name="image_frame_ids",
        ),
        migrations.AddField(
            model_name="dicomimageset",
            name="image_frame_metadata",
            field=models.JSONField(
                default=list,
                editable=False,
                help_text="The metadata of the image frames in AWS Health Imaging",
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema#",
                            "items": {
                                "additionalProperties": False,
                                "properties": {
                                    "frame_size_in_bytes": {
                                        "min_value": 0,
                                        "type": "integer",
                                    },
                                    "image_frame_id": {
                                        "maxLength": 32,
                                        "minLength": 32,
                                        "pattern": "^[0-9a-f]{32}$",
                                        "type": "string",
                                    },
                                    "series_instance_uid": {
                                        "maxLength": 64,
                                        "minLength": 60,
                                        "pattern": "^[0-9.]*$",
                                        "type": "string",
                                    },
                                    "sop_instance_uid": {
                                        "maxLength": 64,
                                        "minLength": 60,
                                        "pattern": "^[0-9.]*$",
                                        "type": "string",
                                    },
                                    "stored_transfer_syntax_uid": {
                                        "maxLength": 32,
                                        "minLength": 17,
                                        "pattern": "^1.2.840.10008.1.2[0-9.]*$",
                                        "type": "string",
                                    },
                                    "study_instance_uid": {
                                        "maxLength": 64,
                                        "minLength": 60,
                                        "pattern": "^[0-9.]*$",
                                        "type": "string",
                                    },
                                },
                                "required": [
                                    "image_frame_id",
                                    "frame_size_in_bytes",
                                    "study_instance_uid",
                                    "series_instance_uid",
                                    "sop_instance_uid",
                                    "stored_transfer_syntax_uid",
                                ],
                                "type": "object",
                            },
                            "minItems": 1,
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
    ]
