# Generated by Django 2.2.9 on 2020-01-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_auto_20191218_0936"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawimageuploadsession", name="processing_task",
        ),
        migrations.RemoveField(
            model_name="rawimageuploadsession", name="session_state",
        ),
        migrations.AddField(
            model_name="rawimagefile",
            name="consumed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rawimageuploadsession",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Started"),
                    (2, "Re-Queued"),
                    (3, "Failed"),
                    (4, "Succeeded"),
                    (5, "Cancelled"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="rawimageuploadsession",
            name="error_message",
            field=models.TextField(default=None, null=True),
        ),
    ]
