# Generated by Django 4.2.24 on 2025-09-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0018_dicomimagesetupload_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dicomimagesetupload",
            name="name",
            field=models.CharField(
                help_text="The name for the resulting Image instance",
                max_length=255,
            ),
        ),
    ]
