# Generated by Django 2.2.9 on 2020-01-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cases", "0019_rawimagefile_state")]

    operations = [
        migrations.AlterField(
            model_name="rawimagefile",
            name="state",
            field=models.BooleanField(default=False),
        )
    ]
