# Generated by Django 2.2.9 on 2020-01-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_rawimagefile_consumed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawimageuploadsession", name="session_state",
        ),
        migrations.AddField(
            model_name="rawimageuploadsession",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Started"),
                    (2, "Re-Queued"),
                    (3, "Failed"),
                    (4, "Succeeded"),
                    (5, "Cancelled"),
                ],
                default=0,
            ),
        ),
    ]
