# Generated by Django 4.2.25 on 2025-10-09 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0020_remove_dicomimageset_image_frame_ids_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dicomimagesetupload",
            name="task_on_success",
            field=models.JSONField(
                default=None,
                editable=False,
                help_text="Serialized task that is run on job success",
                null=True,
            ),
        ),
    ]
