# Generated by Django 3.0.2 on 2020-03-22 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archives", "0003_auto_20200322_0921"),
        ("cases", "0020_add_dicom_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="rawimageuploadsession",
            name="archive",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="archives.Archive",
            ),
        ),
    ]
