# Generated by Django 4.2.25 on 2025-10-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_dicomimagesetupload_task_on_success"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawimageuploadsession",
            name="error_message",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
