# Generated by Django 3.0.2 on 2020-03-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_rawimageuploadsession_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawimagefile",
            name="filename",
            field=models.CharField(max_length=255),
        ),
    ]
