# Generated by Django 4.2.25 on 2025-10-21 10:14

from django.db import migrations


def replace_error_message_none_values(apps, _schema_editor):
    RawImageUploadSession = apps.get_model(  # noqa: N806
        "cases", "RawImageUploadSession"
    )

    RawImageUploadSession.objects.filter(error_message__isnull=True).update(
        error_message=""
    )


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0021_dicomimagesetupload_task_on_success"),
    ]

    operations = [
        migrations.RunPython(replace_error_message_none_values, elidable=True),
    ]
