# Generated by Django 3.0.5 on 2020-05-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0022_auto_20200325_1151"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rawimagefile",
            name="filename",
            field=models.CharField(max_length=4095),
        ),
    ]
