# Generated by Django 3.0.5 on 2020-05-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0023_auto_20200521_1052"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="window_center",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="window_width",
            field=models.FloatField(null=True),
        ),
    ]
