# Generated by Django 3.0.9 on 2020-08-27 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0025_remove_rawimageuploadsession_algorithm_result"),
    ]

    operations = []
