# Generated by Django 5.2.11 on 2026-02-11 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "cases",
            "0027_alter_image_patient_age_alter_image_patient_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="patient_age",
        ),
        migrations.RemoveField(
            model_name="image",
            name="patient_birth_date",
        ),
        migrations.RemoveField(
            model_name="image",
            name="patient_id",
        ),
        migrations.RemoveField(
            model_name="image",
            name="patient_name",
        ),
        migrations.RemoveField(
            model_name="image",
            name="patient_sex",
        ),
        migrations.RemoveField(
            model_name="image",
            name="series_description",
        ),
        migrations.RemoveField(
            model_name="image",
            name="series_instance_uid",
        ),
        migrations.RemoveField(
            model_name="image",
            name="study_date",
        ),
        migrations.RemoveField(
            model_name="image",
            name="study_description",
        ),
        migrations.RemoveField(
            model_name="image",
            name="study_instance_uid",
        ),
    ]
