# Generated by Django 3.1.1 on 2020-11-30 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0027_auto_20201124_1316"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rawimageuploadsession", name="algorithm_image",
        ),
        migrations.RemoveField(
            model_name="rawimageuploadsession", name="archive",
        ),
        migrations.RemoveField(
            model_name="rawimageuploadsession", name="reader_study",
        ),
    ]
