# Generated by Django 5.2.12 on 2026-04-20 14:18

from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0028_remove_image_patient_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="segments",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-07/schema",
                            "items": {
                                "$id": "#/items",
                                "maxItems": 255,
                                "type": "integer",
                            },
                            "title": "The Segments Schema",
                            "type": "array",
                            "uniqueItems": True,
                        }
                    )
                ],
            ),
        ),
    ]
