# Generated by Django 2.2.8 on 2019-12-10 07:27
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models



class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("modified_date", models.DateField(auto_now=True)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("company_name", models.CharField(max_length=200)),
                ("website", models.URLField(max_length=50)),
                ("founded", models.IntegerField()),
                ("hq", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short summary of this project, max 500 characters.",
                        max_length=500,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductBasic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("modified_date", models.DateField(auto_now=True)),
                ("product_name", models.CharField(max_length=200)),
                (
                    "short_name",
                    models.CharField(
                        help_text="short name used in url, specific css, files etc. No spaces allowed",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short summary of this project, max 250 characters.",
                        max_length=250,
                    ),
                ),
                ("modality", models.CharField(max_length=10)),
                ("subspeciality", models.CharField(max_length=30)),
                ("input_data", models.CharField(max_length=150)),
                ("file_format_input", models.CharField(max_length=50)),
                ("output_data", models.CharField(max_length=150)),
                ("file_format_output", models.CharField(max_length=50)),
                ("key_features", models.CharField(max_length=150)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ai_website.CompanyEntry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductEntry",
            fields=[
                (
                    "productbasic_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="ai_website.ProductBasic",
                    ),
                ),
                (
                    "ce_status",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "ce_class",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "fda_status",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "fda_class",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "integration",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "hosting",
                    models.CharField(default="unknown", max_length=50),
                ),
                ("hardware", models.CharField(default=" ", max_length=150)),
                (
                    "market_since",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "countries",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "distribution",
                    models.CharField(default="unknown", max_length=100),
                ),
                (
                    "institutes_research",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "institutes_clinic",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "pricing_model",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "pricing_basis",
                    models.CharField(default="unknown", max_length=50),
                ),
                (
                    "tech_papers",
                    models.CharField(default="unknown", max_length=500),
                ),
                (
                    "clin_papers",
                    models.CharField(default="unknown", max_length=500),
                ),
            ],
            bases=("ai_website.productbasic",),
        ),
    ]
