# Generated by Django 2.2.8 on 2019-12-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyentry',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='companyentry',
            name='website',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productbasic',
            name='file_format_input',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productbasic',
            name='file_format_output',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='productbasic',
            name='modality',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='productbasic',
            name='short_name',
            field=models.CharField(help_text='short name used in url, specific css, files etc. No spaces allowed', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='productbasic',
            name='subspeciality',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='ce_class',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='ce_status',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='countries',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='fda_class',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='fda_status',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='hosting',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='institutes_clinic',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='institutes_research',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='integration',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='market_since',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='pricing_basis',
            field=models.CharField(default='unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='productentry',
            name='pricing_model',
            field=models.CharField(default='unknown', max_length=500),
        ),
    ]
