# Generated by Django 2.2.9 on 2020-01-28 12:30

from django.db import migrations, models

import grandchallenge.ai_website.models
import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("ai_website", "0005_auto_20200128_1220"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyentry",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.ai_website.models.get_logo_path,
            ),
        ),
    ]
