# Generated by Django 2.2.9 on 2020-01-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_website", "0007_auto_20200129_1051"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productentry",
            name="fda_status",
            field=models.CharField(
                choices=[
                    ("cle", "510(k) cleared"),
                    ("dnc", "De novo 510(k) cleared"),
                    ("pma", "PMA approved"),
                    ("no", "No or not yet"),
                    ("na", "Not applicable"),
                    ("unk", "Unknown"),
                ],
                default="unk",
                max_length=3,
            ),
        ),
    ]
