# Generated by Django 2.2.9 on 2020-01-29 16:04

from django.db import migrations, models

import grandchallenge.ai_website.models
import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("ai_website", "0008_auto_20200129_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyentry",
            name="logo",
            field=models.ImageField(
                null=True,
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.ai_website.models.get_logo_path,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="img",
            field=models.ImageField(
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.ai_website.models.get_images_path,
            ),
        ),
    ]
