# Generated by Django 3.1.6 on 2021-02-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstation_configs", "0001_squashed_0008_auto_20201001_0758"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="image_context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PATH", "Pathology"),
                    ("OPHTH", "Ophthalmology"),
                    ("MPMRI", "Multiparametric MRI"),
                ],
                max_length=6,
            ),
        ),
    ]
