# Generated by Django 3.1.6 on 2021-03-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstation_configs", "0001_squashed_0008_auto_20201001_0758"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="enable_contrast_enhancement",
            field=models.BooleanField(
                default=False,
                verbose_name="Enable contrast enhancement preprocessing (fundus)",
            ),
        ),
    ]
