# Generated by Django 3.1.6 on 2021-02-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstation_configs", "0001_squashed_0008_auto_20201001_0758"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="image_context",
            field=models.CharField(
                blank=True,
                max_length=6,
                choices=[
                    ("DEF", "Default"),
                    ("PATH", "Pathology"),
                    ("OPTHA", "Opthamology"),
                    ("MPMRI", "Multiparametric MRI"),
                ],
                default="DEF",
            ),
        ),
    ]
