# Generated by Django 2.2.6 on 2019-10-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("workstation_configs", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="workstationconfig",
            name="default_overlay_interpolation",
            field=models.CharField(
                blank=True,
                choices=[("NN", "NearestNeighbor"), ("TL", "Trilinear")],
                default="NN",
                max_length=2,
            ),
        )
    ]
