# Generated by Django 2.2.9 on 2020-01-10 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstation_configs", "0002_auto_20191025_0743"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="default_overlay_alpha",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(limit_value=0.0),
                    django.core.validators.MaxValueValidator(limit_value=1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="default_zoom_scale",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(limit_value=0.01)
                ],
            ),
        ),
    ]
