# Generated by Django 3.1.6 on 2021-03-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstation_configs", "0002_workstationconfig_image_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="enable_contrast_enhancement",
            field=models.BooleanField(
                default=False,
                verbose_name="Enable contrast enhancement preprocessing (fundus)",
            ),
        ),
    ]
