# Generated by Django 3.0.2 on 2020-04-03 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstation_configs", "0003_auto_20200110_1358"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="show_flip_tool",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="show_invert_tool",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="show_reset_tool",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="show_window_level_tool",
            field=models.BooleanField(default=True),
        ),
    ]
