# Generated by Django 3.0.9 on 2020-09-10 08:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import grandchallenge.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("workstation_configs", "0006_auto_20200430_1414"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="key_bindings",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                blank=True,
                default=list,
                validators=[
                    grandchallenge.core.validators.JSONSchemaValidator(
                        schema={
                            "$id": "http://example.com/example.json",
                            "$schema": "http://json-schema.org/draft-06/schema",
                            "description": "Define the key bindings for the workstation.",
                            "items": {
                                "$id": "#/items",
                                "additionalProperties": False,
                                "default": {},
                                "description": "Defines a key binding for a command.",
                                "examples": [
                                    {
                                        "command": "editor.action.deleteLines",
                                        "key": "ctrl+shift+k",
                                        "when": "editorTextFocus",
                                    }
                                ],
                                "properties": {
                                    "command": {
                                        "$id": "#/items/properties/command",
                                        "default": "",
                                        "description": "The command called by this binding.",
                                        "examples": [
                                            "editor.action.deleteLines"
                                        ],
                                        "title": "The Command Schema",
                                        "type": "string",
                                    },
                                    "key": {
                                        "$id": "#/items/properties/key",
                                        "default": "",
                                        "description": "The keys used for this binding.",
                                        "examples": ["ctrl+shift+k"],
                                        "title": "The Key Schema",
                                        "type": "string",
                                    },
                                    "when": {
                                        "$id": "#/items/properties/when",
                                        "default": "",
                                        "description": "The condition that must be met for this command to be called.",
                                        "examples": ["editorTextFocus"],
                                        "title": "The When Schema",
                                        "type": "string",
                                    },
                                },
                                "required": ["key", "command"],
                                "title": "The Key Binding Schema",
                                "type": "object",
                            },
                            "title": "The Key Bindings Schema",
                            "type": "array",
                        }
                    )
                ],
            ),
        ),
    ]
