# Generated by Django 3.1.11 on 2021-06-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstation_configs",
            "0006_workstationconfig_client_rendered_sidebar",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="auto_jump_center_of_gravity",
            field=models.BooleanField(
                default=True,
                help_text="Jump to center of gravity of first output when viewing algorithm results",
            ),
        )
    ]
