# Generated by Django 3.1.13 on 2021-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstation_configs",
            "0007_workstationconfig_auto_jump_center_of_gravity",
        )
    ]

    operations = [
        migrations.RemoveField(
            model_name="workstationconfig", name="client_rendered_sidebar"
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="show_algorithm_output_plugin",
            field=models.BooleanField(
                default=True,
                help_text="Show algorithm outputs with navigation controls",
            ),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="show_image_switcher_plugin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="show_lut_selection_tool",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="show_overlay_plugin",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="show_overlay_selection_tool",
            field=models.BooleanField(default=True),
        ),
    ]
