# Generated by Django 3.2.10 on 2021-12-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workstation_configs",
            "0010_workstationconfig_show_annotation_counter_tool",
        )
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="link_images",
            field=models.BooleanField(
                default=True,
                help_text="Linked images share tool interactions and display properties, it is possible to manually (un)link them during viewing",
            ),
        )
    ]
