# Generated by Django 3.2.10 on 2022-02-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("workstation_configs", "0012_auto_20220211_1301")]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="default_image_interpolation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NN", "NearestNeighbor"),
                    ("TL", "Trilinear"),
                    ("CU", "Cubic"),
                ],
                default="CU",
                help_text="The method used to interpolate multiple voxels of the image and project them to screen pixels",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="workstationconfig",
            name="default_overlay_interpolation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NN", "NearestNeighbor"),
                    ("TL", "Trilinear"),
                    ("CU", "Cubic"),
                ],
                default="NN",
                help_text="The method used to interpolate multiple voxels of overlay images and project them to screen pixels",
                max_length=2,
            ),
        ),
    ]
