# Generated by Django 3.2.13 on 2022-06-01 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workstation_configs", "0013_auto_20220221_0943"),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="show_annotation_statistics_plugin",
            field=models.BooleanField(
                default=False,
                help_text="A plugin that allows analysis of segmentations. It shows voxel value statistics of annotated areas.",
            ),
        ),
    ]
