# Generated by Django 3.2.13 on 2022-06-07 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workstation_configs",
            "0014_workstationconfig_show_annotation_statistics_plugin",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workstationconfig",
            name="default_overlay_lut",
            field=models.ForeignKey(
                blank=True,
                help_text="The look-up table that is applied when an overlay image is first shown",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="workstation_configs.lookuptable",
            ),
        ),
        migrations.AlterField(
            model_name="workstationconfig",
            name="default_window_preset",
            field=models.ForeignKey(
                blank=True,
                help_text="The preset that is applied when an image is first shown",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workstation_default_window_presets",
                to="workstation_configs.windowpreset",
            ),
        ),
    ]
