# Generated by Django 3.2.14 on 2022-07-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workstation_configs",
            "0016_alter_workstationconfig_overlay_segments",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="link_flipping",
            field=models.BooleanField(
                default=True,
                help_text="When flipping images and the images are linked, they share any new flip state",
            ),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="link_inverting",
            field=models.BooleanField(
                default=True,
                help_text="When inverting images and the images are linked, they share any new invert state",
            ),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="link_orienting",
            field=models.BooleanField(
                default=True,
                help_text="When orienting and the images are linked, they share any new orientation",
            ),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="link_panning",
            field=models.BooleanField(
                default=True,
                help_text="When panning and the images are linked, they share any new position",
            ),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="link_slicing",
            field=models.BooleanField(
                default=True,
                help_text="When scrolling and the images are linked, they share any slice changes",
            ),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="link_windowing",
            field=models.BooleanField(
                default=True,
                help_text="When changing window setting and the images are linked, they share any new window width/center",
            ),
        ),
        migrations.AddField(
            model_name="workstationconfig",
            name="link_zooming",
            field=models.BooleanField(
                default=True,
                help_text="When zooming and the images are linked, they share any new zoom level",
            ),
        ),
        migrations.AlterField(
            model_name="workstationconfig",
            name="link_images",
            field=models.BooleanField(
                default=True, help_text="Start with the images linked"
            ),
        ),
    ]
