# Generated by Django 4.1.11 on 2023-09-19 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workstation_configs",
            "0022_alter_workstationconfig_overlay_segments",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="ghosting_slice_depth",
            field=models.IntegerField(
                default=3,
                help_text="The number of slices a polygon annotation should remain visible for on slices surrounding the annotation slice.",
                validators=[
                    django.core.validators.MinValueValidator(limit_value=0)
                ],
            ),
        ),
    ]
