# Generated by Django 4.2.8 on 2024-01-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "workstation_configs",
            "0024_workstationconfig_default_annotation_line_width",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="workstationconfig",
            name="default_limit_view_area_to_image_volume",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, the view area is limited to the image volume, ensuring that changes in orientation and panning do not obscure parts of the image",
            ),
        ),
    ]
