# Generated by Django 4.2.9 on 2024-03-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstation_configs",
            "0025_workstationconfig_default_limit_view_area_to_image_volume",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="workstationconfig",
            name="image_context",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PATH", "Pathology"),
                    ("MPMRI", "Multiparametric MRI"),
                ],
                help_text="Sets several heuristics used for automatically selecting tools, hanging protocols, et cetera",
                max_length=6,
            ),
        ),
    ]
