# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstation_configs",
            "0030_workstationconfiguserobjectpermission_workstation_user_id_f51513_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="workstationconfiggroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="workstation_group_i_8f1efe_idx",
            ),
        ),
    ]
