# Generated by Django 5.2.16 on 2026-08-06 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "workstation_configs",
            "0032_alter_workstationconfig_overlay_segments",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lookuptable",
            constraint=models.UniqueConstraint(
                fields=("slug",),
                name="workstation_configs_lookuptable_unique_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="windowpreset",
            constraint=models.UniqueConstraint(
                fields=("slug",),
                name="workstation_configs_windowpreset_unique_slug",
            ),
        ),
        migrations.AddConstraint(
            model_name="workstationconfig",
            constraint=models.UniqueConstraint(
                fields=("slug",),
                name="workstation_configs_workstationconfig_unique_slug",
            ),
        ),
    ]
