# Generated by Django 4.2.19 on 2025-02-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_type",
            field=models.CharField(
                choices=[("COMPLIMENTARY", "Complimentary"), ("PAID", "Paid")],
                default="PAID",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("ISSUED", "Issued"),
                    ("PAID", "Paid"),
                ],
                default="INITIALIZED",
                max_length=13,
            ),
        ),
    ]
