# Generated by Django 4.2.19 on 2025-02-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="budget_preapproved",
            field=models.BooleanField(
                default=False,
                help_text="Preapproval will make the budget immediately available, regardless of the payment status, but only if there is another invoice in the paid state.",
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("REQUESTED", "Invoice Requested"),
                    ("ISSUED", "Issued"),
                    ("COMPLIMENTARY", "Complimentary"),
                    ("PAID", "Paid"),
                ],
                default="INITIALIZED",
                max_length=13,
            ),
        ),
    ]
