# Generated by Django 4.2.19 on 2025-02-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("ISSUED", "Issued"),
                    ("COMPLIMENTARY", "Complimentary"),
                    ("PAID", "Paid"),
                    ("POSTPAID", "Postpaid"),
                ],
                default="INITIALIZED",
                max_length=13,
            ),
        ),
    ]
