# Generated by Django 4.2.19 on 2025-02-26 21:22

from django.db import migrations, models

import grandchallenge.invoices.models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("COMPLIMENTARY", "Complimentary"),
                    ("PREPAID", "Prepaid"),
                    ("POSTPAID", "Postpaid"),
                ],
                default="PREPAID",
                max_length=13,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("REQUESTED", "Invoice Requested"),
                    ("ISSUED", "Invoice Issued"),
                    ("COMPLIMENTARY", "Complimentary"),
                    ("PAID", "Paid"),
                ],
                default="INITIALIZED",
                max_length=13,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "payment_type__in",
                        grandchallenge.invoices.models.PaymentTypeChoices,
                    )
                ),
                name="payment_type_in_choices",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "payment_status__in",
                        grandchallenge.invoices.models.PaymentStatusChoices,
                    )
                ),
                name="payment_status_in_choices",
            ),
        ),
    ]
