# Generated by Django 4.2.19 on 2025-02-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_data_payment_status_and_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("REQUESTED", "Invoice Requested"),
                    ("ISSUED", "Invoice Issued"),
                    ("PAID", "Paid"),
                ],
                default="INITIALIZED",
                max_length=11,
            ),
        ),
    ]
