# Generated by Django 4.2.19 on 2025-03-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0003_data_payment_status_and_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("REQUESTED", "Invoice Requested"),
                    ("ISSUED", "Invoice Issued"),
                    ("PAID", "Paid"),
                ],
                default="INITIALIZED",
                max_length=11,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "payment_type__in",
                        ["COMPLIMENTARY", "PREPAID", "POSTPAID"],
                    )
                ),
                name="payment_type_in_choices",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "payment_status__in",
                        ["INITIALIZED", "REQUESTED", "ISSUED", "PAID"],
                    )
                ),
                name="payment_status_in_choices",
            ),
        ),
    ]
