# Generated by Django 4.2.19 on 2025-02-26 12:41

from django.db import migrations, models

import grandchallenge.invoices.models


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0004_alter_invoice_payment_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "payment_type__in",
                        grandchallenge.invoices.models.PaymentTypeChoices,
                    )
                ),
                name="payment_type_in_choices",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "payment_status__in",
                        grandchallenge.invoices.models.PaymentStatusChoices,
                    )
                ),
                name="payment_status_in_choices",
            ),
        ),
    ]
