# Generated by Django 4.2.19 on 2025-03-19 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("invoices", "0006_assign_perms_challenge_admins"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["created"]},
        ),
    ]
