# Generated by Django 4.2.21 on 2025-05-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0008_invoicegroupobjectpermission_invoices_in_group_i_3c5e79_idx",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invoice",
            name="payment_status_in_choices",
        ),
        migrations.AlterField(
            model_name="invoice",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("INITIALIZED", "Initialized"),
                    ("REQUESTED", "Invoice Requested"),
                    ("ISSUED", "Invoice Issued"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="INITIALIZED",
                max_length=11,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "payment_status__in",
                        [
                            "INITIALIZED",
                            "REQUESTED",
                            "ISSUED",
                            "PAID",
                            "CANCELLED",
                        ],
                    )
                ),
                name="payment_status_in_choices",
            ),
        ),
    ]
