# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0009_remove_invoice_payment_status_in_choices_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="invoiceuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="invoices_in_user_id_66e98c_idx",
            ),
        ),
    ]
