# Generated by Django 5.2.13 on 2026-05-05 12:10

from django.db import migrations, models

import grandchallenge.invoices.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0010_invoiceuserobjectpermission_invoices_in_user_id_66e98c_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="expires_on",
            field=models.DateField(
                default=grandchallenge.invoices.models.default_invoice_expiry,
                help_text="The date when the invoice expires",
            ),
        ),
    ]
