# Generated by Django 5.2.13 on 2026-05-08 08:18

import datetime

import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0071_alter_challengerequest_status_and_more"),
        ("invoices", "0012_migrate_invoice_expires_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="follow_up_on",
            field=models.DateField(
                blank=True,
                help_text="The date when a post-paid invoice will be issued if necessary (required for post-paid invoices).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="last_checked_on",
            field=models.DateField(
                blank=True,
                help_text="The date when the status of issued invoices was last checked",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("follow_up_on__isnull", True),
                    ("follow_up_on__lt", models.F("expires_on")),
                    _connector="OR",
                ),
                name="follow_up_on_before_expires_on",
                violation_error_message="Follow-up date must be before the expiry date.",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("follow_up_on__isnull", True),
                    (
                        "follow_up_on__lte",
                        django.db.models.expressions.CombinedExpression(
                            django.db.models.functions.datetime.Now(),
                            "+",
                            models.Value(datetime.timedelta(days=365)),
                        ),
                    ),
                    _connector="OR",
                ),
                name="follow_up_on_not_more_than_a_year_in_future",
                violation_error_message="Follow-up date cannot be more than a year into the future.",
            ),
        ),
    ]
