# Generated by Django 5.2.13 on 2026-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0012_migrate_invoice_expires_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="utilized_compute_cost_euro_millicents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The utilized compute costs in Euro millicents (cached from utilizations)",
            ),
        ),
    ]
