# Generated by Django 5.2.13 on 2026-05-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0013_invoice_follow_up_on_alter_invoice_last_checked_on_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="compute_costs_utilized_euros_millicents",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The utilized compute costs in Euro millicents (cached from utilizations)",
            ),
        ),
    ]
