# Generated by Django 5.2.14 on 2026-05-29 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0015_invoice_follow_up_on_required_for_initialized_post_paid",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="compute_costs_utilized_euros_millicents",
            new_name="compute_cost_euro_millicents",
        ),
    ]
