# Generated by Django 5.2.14 on 2026-06-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invoices",
            "0016_rename_compute_costs_utilized_euros_millicents_invoice_compute_cost_euro_millicents",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="compute_cost_euro_millicents",
            field=models.PositiveBigIntegerField(
                default=0,
                help_text="The utilized compute costs in Euro millicents (cached from utilizations)",
            ),
        ),
    ]
