# Generated by Django 5.2.14 on 2026-06-09 08:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0072_alter_challenge_compute_cost_euro_millicents"),
        (
            "invoices",
            "0018_invoice_paid_or_cancelled_status_required_for_complimentary_payment_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="external_pk",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["external_pk"], name="invoices_in_externa_456e01_idx"
            ),
        ),
    ]
