# Generated by Django 5.2.14 on 2026-06-09 08:49

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    Invoice = apps.get_model("invoices", "Invoice")  # noqa: N806
    for row in Invoice.objects.all():
        row.external_pk = uuid.uuid4()
        row.save(update_fields=["external_pk"])


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0019_invoice_external_pk_and_more"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, elidable=True),
    ]
