# Generated by Django 5.2.14 on 2026-06-09 08:49

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0020_auto_20260609_0849"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="external_pk",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
