# Generated by Django 2.0.9 on 2018-11-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='The identifier code for this study.')),
                ('region_of_interest', models.CharField(max_length=255, verbose_name='Region or location where the study was performed.')),
            ],
        ),
    ]
