# Generated by Django 2.1.2 on 2018-11-28 15:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=100, verbose_name='Identifier code')),
                ('region_of_interest', models.CharField(max_length=255, verbose_name='Region of study')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
