# Generated by Django 3.1.13 on 2021-10-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Study",),
    ]
