# Generated by Django 3.1.13 on 2021-10-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="study",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="patients.patient",
            ),
        ),
        migrations.AlterUniqueTogether(name="study", unique_together=set(),),
    ]
