# Generated by Django 3.1.13 on 2021-10-14 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0007_remove_image_study"),
        ("studies", "0002_auto_20211012_0942"),
    ]

    operations = [
        migrations.DeleteModel(name="Study",),
    ]
