# Generated by Django 3.1.13 on 2021-09-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0003_githubusertoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubwebhookmessage",
            name="error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="githubwebhookmessage",
            name="has_open_source_license",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="githubwebhookmessage",
            name="license_check_result",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
