# Generated by Django 3.2.10 on 2021-12-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("github", "0005_githubusertoken_github_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubwebhookmessage",
            name="zip_file_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NOT_STARTED", "Not started"),
                    ("STARTED", "Started"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                default="NOT_STARTED",
                max_length=12,
                null=True,
            ),
        ),
    ]
