# Generated by Django 3.2.10 on 2022-01-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("github", "0005_githubusertoken_github_user_id")]

    operations = [
        migrations.AddField(
            model_name="githubwebhookmessage",
            name="clone_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("STARTED", "Started"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                ],
                default="PENDING",
                max_length=12,
            ),
        )
    ]
