# Generated by Django 3.2.10 on 2022-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0006_githubwebhookmessage_clone_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="githubwebhookmessage",
            old_name="error",
            new_name="stderr",
        ),
        migrations.AddField(
            model_name="githubwebhookmessage",
            name="stdout",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="githubwebhookmessage",
            name="clone_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("STARTED", "Started"),
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("INVALID", "Invalid"),
                ],
                default="PENDING",
                max_length=12,
            ),
        ),
    ]
