# Generated by Django 2.1.3 on 2018-12-10 15:04

import django.contrib.postgres.fields
import django.contrib.postgres.fields.citext
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
        ('cases', '0007_auto_20180909_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetinaImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('modality', django.contrib.postgres.fields.citext.CICharField(blank=True, choices=[('CF', 'Color fundus'), ('OCT', 'Optical coherence tomography'), ('FA', 'Fluorescein angiography'), ('HRA', 'Heidelberg retinal angiography'), ('FUN', 'Color fundus'), ('OBS', 'OBS'), ('TRC', 'TRC')], max_length=3, null=True)),
                ('eye_choice', django.contrib.postgres.fields.citext.CICharField(choices=[('OD', 'Oculus Dexter (right eye)'), ('OS', 'Oculus Sinister (left eye)'), ('U', 'Unknown')], default='U', help_text='The eye of which this image is from', max_length=2)),
                ('voxel_size', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), blank=True, null=True, size=3)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Image')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.Study')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='retinaimage',
            unique_together={('study', 'name', 'modality')},
        ),
    ]
