# Generated by Django 2.1.4 on 2018-12-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retina_images', '0002_remove_retinaimage_voxel_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retinaimage',
            name='eye_choice',
        ),
    ]
