# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_teamgroupobjectpermission_teamuserobjectpermission"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="teamuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="teams_teamu_user_id_03fef1_idx",
            ),
        ),
    ]
