# Generated by Django 4.2.21 on 2025-05-14 10:42

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "permissions": (
                    ("create_forum_topic", "Can create a topic in this forum"),
                    (
                        "create_sticky_and_announcement_topic",
                        "Can create sticky and announcement topics in this forum",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        populate_from="subject",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default topic"),
                            ("STICKY", "Sticky topic"),
                            ("ANNOUNCE", "Announcement topic"),
                        ],
                        default="DEFAULT",
                        max_length=8,
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False,
                        help_text="Lock a topic to close it and prevent posts from being added to it.",
                    ),
                ),
                ("last_post_on", models.DateTimeField(blank=True, null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_forum_topics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="discussion_forums.forum",
                    ),
                ),
            ],
            options={
                "ordering": ["-kind", "-last_post_on"],
                "permissions": (
                    ("create_topic_post", "Create a post for this topic"),
                ),
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True,
                        editable=False,
                        max_length=64,
                        populate_from="subject",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_forum_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="discussion_forums.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("kind__in", ["DEFAULT", "STICKY", "ANNOUNCE"])
                ),
                name="valid_topic_kind",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("slug", "forum")},
        ),
    ]
