# Generated by Django 2.2.10 on 2020-04-23 15:49
import machina.core.validators
import machina.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("forum_member", "0004_auto_20181103_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumprofile",
            name="signature",
            field=machina.models.fields.MarkupTextField(
                blank=True,
                no_rendered_field=True,
                null=True,
                validators=[
                    machina.core.validators.MarkupMaxLengthValidator(255)
                ],
                verbose_name="Signature",
            ),
        ),
    ]
