# Generated by Django 2.1.7 on 2019-04-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='implementation',
            name='command',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
