# Generated by Django 2.2.4 on 2019-08-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_algorithms', '0004_auto_20190617_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implementation',
            name='algorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='eyra_algorithms.Algorithm'),
        ),
    ]
