# Generated by Django 2.2.4 on 2019-08-02 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('eyra_algorithms', '0006_auto_20190801_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='admin_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algorithm', to='auth.Group'),
        ),
    ]
