# Generated by Django 2.2.2 on 2019-09-03 13:03

import comic.eyra_algorithms.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_algorithms', '0007_algorithm_admin_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='admin_group',
            field=models.OneToOneField(blank=True, help_text='The admin group associated with this algorithm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='algorithm', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment of creation'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='creator',
            field=models.ForeignKey(help_text='Created by user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='algorithms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of this solution in markdown'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='interface',
            field=models.ForeignKey(help_text='Description of this solution in markdown', on_delete=django.db.models.deletion.CASCADE, related_name='algorithms', to='eyra_algorithms.Interface'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Moment of last modification'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(help_text='Name of algorithm', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='algorithm',
            field=models.ForeignKey(help_text='Implemented algorithm', on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='eyra_algorithms.Algorithm'),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='command',
            field=models.CharField(blank=True, help_text='If specified, overrides default command as defined in Dockerfile', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment of creation'),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='creator',
            field=models.ForeignKey(help_text='Created by user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implementations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of this implementation in markdown'),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='image',
            field=models.CharField(help_text='Docker image (e.g. eyra/frb-eval:3)', max_length=64, unique=True, validators=[comic.eyra_algorithms.validators.IdExistsInDockerRegistryValidator]),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Moment of last modification'),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='name',
            field=models.CharField(help_text='Name of the implementation (e.g. FRB Evaluator v3)', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='implementation',
            name='version',
            field=models.CharField(blank=True, help_text='Version', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='input',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment of creation'),
        ),
        migrations.AlterField(
            model_name='input',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='input',
            name='interface',
            field=models.ForeignKey(help_text='Implementation', on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='eyra_algorithms.Interface'),
        ),
        migrations.AlterField(
            model_name='input',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Moment of last modification'),
        ),
        migrations.AlterField(
            model_name='input',
            name='name',
            field=models.CharField(help_text='Input name', max_length=64),
        ),
        migrations.AlterField(
            model_name='input',
            name='type',
            field=models.ForeignKey(help_text='Data type', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eyra_data.DataType'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='interface',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Moment of last modification'),
        ),
        migrations.AlterField(
            model_name='interface',
            name='name',
            field=models.CharField(help_text='Name of the interface', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='output_type',
            field=models.ForeignKey(help_text='Output DataType', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eyra_data.DataType'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment of creation'),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='implementation',
            field=models.ForeignKey(help_text='Implementation being run', on_delete=django.db.models.deletion.CASCADE, to='eyra_algorithms.Implementation'),
        ),
        migrations.AlterField(
            model_name='job',
            name='log',
            field=models.TextField(blank=True, help_text='Combined stderr/stdout of the job', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Moment of last modification'),
        ),
        migrations.AlterField(
            model_name='job',
            name='output',
            field=models.ForeignKey(help_text='Output of the job', on_delete=django.db.models.deletion.CASCADE, related_name='output_of_job', to='eyra_data.DataFile'),
        ),
        migrations.AlterField(
            model_name='job',
            name='started',
            field=models.DateTimeField(blank=True, help_text='Moment job was started', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Queued'), (1, 'Started'), (2, 'Re-Queued'), (3, 'Failed'), (4, 'Succeeded'), (5, 'Cancelled')], default=0, help_text='Status of the job'),
        ),
        migrations.AlterField(
            model_name='job',
            name='stopped',
            field=models.DateTimeField(blank=True, help_text='Moment job completed (success or fail)', null=True),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Moment of creation'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='data_file',
            field=models.ForeignKey(help_text='Input DataFile', on_delete=django.db.models.deletion.CASCADE, related_name='job_inputs', to='eyra_data.DataFile'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID (primary key)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='input',
            field=models.ForeignKey(help_text='Input of implementation', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='eyra_algorithms.Input'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='job',
            field=models.ForeignKey(help_text='Job that this input is for', on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='eyra_algorithms.Job'),
        ),
        migrations.AlterField(
            model_name='jobinput',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Moment of last modification'),
        ),
    ]
