# Generated by Django 2.2.2 on 2019-09-12 13:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_algorithms', '0008_auto_20190903_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='paper_link',
            field=models.URLField(blank=True, help_text='Link to a paper or blog post', null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='source_code_link',
            field=models.URLField(blank=True, help_text='Link to the source code', null=True),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=[], help_text='Tags associated with this algorithm', size=None),
            preserve_default=False,
        ),
    ]
