# Generated by Django 3.1.1 on 2021-01-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinterface",
            name="store_in_database",
            field=models.BooleanField(
                default=True,
                editable=False,
                help_text="Should the value be saved in a database field, only valid for outputs.",
            ),
        ),
    ]
