# Generated by Django 3.0.6 on 2020-06-15 14:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

import grandchallenge.components.validators


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentinterface",
            name="default_value",
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=None,
                help_text="Default value for this field, only valid for inputs.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="componentinterface",
            name="relative_path",
            field=models.CharField(
                help_text="The path to the entity that implements this interface relative to the input or output directory.",
                max_length=255,
                unique=True,
                validators=[
                    grandchallenge.components.validators.validate_safe_path
                ],
            ),
        ),
    ]
