# Generated by Django 3.1.1 on 2020-10-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentinterface",
            name="default_value",
            field=models.JSONField(
                default=None,
                help_text="Default value for this field, only valid for inputs.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="componentinterfacevalue",
            name="value",
            field=models.JSONField(default=None, null=True),
        ),
    ]
