# Generated by Django 3.1.11 on 2021-07-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0004_auto_20210601_0802"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinterface",
            name="schema",
            field=models.JSONField(
                default=dict,
                blank=True,
                help_text="Additional JSON schema that the values for this interface must satisfy. See https://json-schema.org/. Only Draft 7, 6, 4 or 3 are supported.",
            ),
        ),
    ]
