# Generated by Django 3.1.13 on 2021-11-16 09:06

from django.db import migrations, models

import grandchallenge.components.models
import grandchallenge.core.storage
import grandchallenge.core.validators


class Migration(migrations.Migration):
    dependencies = [("components", "0006_auto_20211027_0537")]

    operations = [
        migrations.AlterField(
            model_name="componentinterfacevalue",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=grandchallenge.core.storage.ProtectedS3Storage(),
                upload_to=grandchallenge.components.models.component_interface_value_path,
                validators=[
                    grandchallenge.core.validators.ExtensionValidator(
                        allowed_extensions=(
                            ".json",
                            ".zip",
                            ".csv",
                            ".png",
                            ".jpg",
                            ".jpeg",
                            ".pdf",
                            ".sqreg",
                        )
                    ),
                    grandchallenge.core.validators.MimeTypeValidator(
                        allowed_types=(
                            "application/json",
                            "application/zip",
                            "text/plain",
                            "application/csv",
                            "application/pdf",
                            "image/png",
                            "image/jpeg",
                            "application/octet-stream",
                        )
                    ),
                ],
            ),
        )
    ]
