# Generated by Django 4.1.10 on 2023-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0015_alter_componentinterface_overlay_segments"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinterfacevalue",
            name="storage_cost_per_year_usd_cents",
            field=models.PositiveSmallIntegerField(
                default=None,
                editable=False,
                help_text="The storage cost per year for this image in USD Cents, excluding Tax",
                null=True,
            ),
        ),
    ]
