# Generated by Django 4.2.15 on 2024-09-12 09:36

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0020_alter_componentinterface_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentinterface",
            name="kind",
            field=models.CharField(
                choices=[
                    ("STR", "String"),
                    ("INT", "Integer"),
                    ("FLT", "Float"),
                    ("BOOL", "Bool"),
                    ("JSON", "Anything"),
                    ("CHART", "Chart"),
                    ("2DBB", "2D bounding box"),
                    ("M2DB", "Multiple 2D bounding boxes"),
                    ("DIST", "Distance measurement"),
                    ("MDIS", "Multiple distance measurements"),
                    ("POIN", "Point"),
                    ("MPOI", "Multiple points"),
                    ("POLY", "Polygon"),
                    ("MPOL", "Multiple polygons"),
                    ("LINE", "Line"),
                    ("MLIN", "Multiple lines"),
                    ("ANGL", "Angle"),
                    ("MANG", "Multiple angles"),
                    ("ELLI", "Ellipse"),
                    ("MELL", "Multiple ellipses"),
                    ("3ANG", "Three-point angle"),
                    ("M3AN", "Multiple three-point angles"),
                    ("ATRG", "Affine transform registration"),
                    ("CHOI", "Choice"),
                    ("MCHO", "Multiple choice"),
                    ("IMG", "Image"),
                    ("SEG", "Segmentation"),
                    ("HMAP", "Heat Map"),
                    ("DSPF", "Displacement field"),
                    ("PDF", "PDF file"),
                    ("SQREG", "SQREG file"),
                    ("JPEG", "Thumbnail jpg"),
                    ("PNG", "Thumbnail png"),
                    ("OBJ", "OBJ file"),
                    ("MP4", "MP4 file"),
                    ("CSV", "CSV file"),
                    ("ZIP", "ZIP file"),
                ],
                help_text="What is the type of this interface? Used to validate interface values and connections between components.",
                max_length=5,
            ),
        ),
        migrations.CreateModel(
            name="ComponentInterfaceExampleValue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Example value for an interface",
                        null=True,
                    ),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True,
                        help_text="Extra information about the example value",
                    ),
                ),
                (
                    "interface",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="example_value",
                        to="components.componentinterface",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
