# Generated by Django 4.2.14 on 2024-08-02 11:12

from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0020_alter_componentinterface_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentinterface",
            name="example_value",
            field=models.JSONField(
                blank=True,
                default=None,
                help_text="Example JSON that complies with the additional JSON schema",
                null=True,
                validators=[
                    grandchallenge.core.validators.JSONSchemaValidator()
                ],
            ),
        ),
    ]
