# Generated by Django 4.2.24 on 2025-09-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0025_alter_componentinterface_overlay_segments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentinterface",
            name="kind",
            field=models.CharField(
                choices=[
                    ("STR", "String"),
                    ("INT", "Integer"),
                    ("FLT", "Float"),
                    ("BOOL", "Bool"),
                    ("JSON", "Anything"),
                    ("CHART", "Chart"),
                    ("2DBB", "2D bounding box"),
                    ("M2DB", "Multiple 2D bounding boxes"),
                    ("DIST", "Distance measurement"),
                    ("MDIS", "Multiple distance measurements"),
                    ("POIN", "Point"),
                    ("MPOI", "Multiple points"),
                    ("POLY", "Polygon"),
                    ("MPOL", "Multiple polygons"),
                    ("LINE", "Line"),
                    ("MLIN", "Multiple lines"),
                    ("ANGL", "Angle"),
                    ("MANG", "Multiple angles"),
                    ("ELLI", "Ellipse"),
                    ("MELL", "Multiple ellipses"),
                    ("3ANG", "Three-point angle"),
                    ("M3AN", "Multiple three-point angles"),
                    ("ATRG", "Affine transform registration"),
                    ("CHOI", "Choice"),
                    ("MCHO", "Multiple choice"),
                    ("IMG", "MHA or TIFF Image"),
                    ("SEG", "Segmentation"),
                    ("HMAP", "Heat Map"),
                    ("DSPF", "Displacement field"),
                    ("PDF", "PDF file"),
                    ("SQREG", "SQREG file"),
                    ("JPEG", "Thumbnail jpg"),
                    ("PNG", "Thumbnail png"),
                    ("OBJ", "OBJ file"),
                    ("MP4", "MP4 file"),
                    ("NEWCK", "Newick tree-format file"),
                    ("BIOM", "BIOM format"),
                    ("CSV", "CSV file"),
                    ("ZIP", "ZIP file"),
                ],
                help_text="What is the type of this interface? Used to validate interface values and connections between components.",
                max_length=5,
            ),
        ),
    ]
