# Generated by Django 4.2.25 on 2025-10-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0026_alter_componentinterface_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="componentinterfacevalue",
            name="storage_cost_per_year_usd_millicents",
        ),
    ]
