# Generated by Django 3.1.1 on 2020-12-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modalities", "0001_initial"),
        ("anatomy", "0001_initial"),
        ("publications", "0003_auto_20201001_0758"),
        ("algorithms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="modalities",
            field=models.ManyToManyField(
                blank=True,
                help_text="The imaging modalities supported by this algorithm",
                to="modalities.ImagingModality",
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="publications",
            field=models.ManyToManyField(
                blank=True,
                help_text="The publications associated with this algorithm",
                to="publications.Publication",
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="structures",
            field=models.ManyToManyField(
                blank=True,
                help_text="The structures supported by this algorithm",
                to="anatomy.BodyStructure",
            ),
        ),
    ]
