# Generated by Django 2.0.8 on 2018-08-14 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_auto_20180814_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='case',
            new_name='image',
        ),
    ]
