# Generated by Django 3.1.6 on 2021-03-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0005_algorithm_average_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="use_flexible_inputs",
            field=models.BooleanField(default=True),
        ),
    ]
