# Generated by Django 3.1.6 on 2021-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0006_algorithm_use_flexible_inputs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Started"),
                    (2, "Re-Queued"),
                    (3, "Failed"),
                    (4, "Succeeded"),
                    (5, "Cancelled"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
