# Generated by Django 2.1.7 on 2019-02-15 13:28

from django.db import migrations, models

import grandchallenge.container_exec.models
import grandchallenge.core.storage
import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [("algorithms", "0006_auto_20181205_2226")]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="image",
            field=models.FileField(
                blank=True,
                help_text=".tar.gz archive of the container image produced from the command 'docker save IMAGE | gzip -c > IMAGE.tar.gz'. See https://docs.docker.com/engine/reference/commandline/save/",
                storage=grandchallenge.core.storage.PrivateS3Storage(),
                upload_to=grandchallenge.container_exec.models.docker_image_path,
                validators=[
                    grandchallenge.core.validators.ExtensionValidator(
                        allowed_extensions=(".tar", ".tar.gz")
                    )
                ],
            ),
        )
    ]
