# Generated by Django 2.1.7 on 2019-02-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("algorithms", "0007_auto_20190215_1328")]

    operations = [
        migrations.RemoveField(model_name="algorithm", name="creator"),
        migrations.RemoveField(model_name="job", name="algorithm"),
        migrations.RemoveField(model_name="job", name="image"),
        migrations.RemoveField(model_name="result", name="images"),
        migrations.RemoveField(model_name="result", name="job"),
    ]
