# Generated by Django 2.1.8 on 2019-05-08 13:25

import django_extensions.db.fields
from django.db import migrations, models

import grandchallenge.challenges.models


class Migration(migrations.Migration):

    dependencies = [("algorithms", "0007_auto_20190215_1328")]

    operations = [
        migrations.RemoveField(
            model_name="algorithm", name="description_html"
        ),
        migrations.AddField(
            model_name="algorithm",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="description"
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="logo",
            field=models.ImageField(
                null=True,
                upload_to=grandchallenge.challenges.models.get_logo_path,
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from="title",
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="title",
            field=models.CharField(max_length=255, verbose_name="title"),
        ),
    ]
