# Generated by Django 3.1.11 on 2021-06-01 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstations", "0004_auto_20210512_1437"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("algorithms", "0008_auto_20210512_1437"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="editors_group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="editors_of_algorithm",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="users_group",
            field=models.OneToOneField(
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users_of_algorithm",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="workstation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="workstations.workstation",
            ),
        ),
        migrations.AlterField(
            model_name="algorithmimage",
            name="algorithm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="algorithm_container_images",
                to="algorithms.algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="algorithm_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="algorithms.algorithmimage",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="viewers",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="viewers_of_algorithm_job",
                to="auth.group",
            ),
        ),
    ]
