# Generated by Django 2.1.7 on 2019-02-27 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0008_auto_20190227_1500"),
        ("cases", "0011_auto_20190227_1500"),
    ]

    operations = [
        migrations.DeleteModel(name="Algorithm"),
        migrations.DeleteModel(name="Job"),
        migrations.DeleteModel(name="Result"),
    ]
