# Generated by Django 2.1.7 on 2019-02-27 15:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mlmodels", "0001_initial"),
        ("algorithms", "0009_auto_20190227_1500"),
    ]

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(max_length=32, null=True, unique=True),
                ),
                (
                    "slug",
                    models.SlugField(
                        editable=False, max_length=32, null=True, unique=True
                    ),
                ),
                (
                    "mlmodel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mlmodels.MLModel",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
