# Generated by Django 2.2.4 on 2019-08-27 12:36
from django.db import migrations


def algorithm_images_to_algorithms_reverse(apps, schema_editor):
    # Reverse, create AlgorithmImage from Algorithm
    pass


def algorithm_images_to_algorithms_forward(apps, schema_editor):
    # Forward, create Algorithm from AlgorithmImage
    from grandchallenge.algorithms.models import Algorithm

    AlgorithmImage = apps.get_model("algorithms", "AlgorithmImage")

    for ai in AlgorithmImage.objects.all():
        Algorithm.objects.create(title=ai.title, slug=ai.slug, logo=ai.logo)


class Migration(migrations.Migration):

    dependencies = [("algorithms", "0010_auto_20190827_1159")]

    operations = [
        migrations.RunPython(
            algorithm_images_to_algorithms_forward,
            algorithm_images_to_algorithms_reverse,
        )
    ]
