# Generated by Django 2.2.6 on 2019-10-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("algorithms", "0011_algorithm_image_data_20190827_1236")]

    operations = [
        migrations.RemoveField(
            model_name="algorithmimage", name="description"
        ),
        migrations.RemoveField(model_name="algorithmimage", name="logo"),
        migrations.RemoveField(model_name="algorithmimage", name="slug"),
        migrations.RemoveField(model_name="algorithmimage", name="title"),
        migrations.AlterField(
            model_name="algorithmimage",
            name="algorithm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="algorithms.Algorithm",
            ),
        ),
    ]
