# Generated by Django 2.2.6 on 2019-10-07 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("algorithms", "0011_algorithm_image_data_20190827_1236"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithmimage", name="description"
        ),
        migrations.RemoveField(model_name="algorithmimage", name="logo"),
        migrations.RemoveField(model_name="algorithmimage", name="slug"),
        migrations.RemoveField(model_name="algorithmimage", name="title"),
        migrations.AddField(
            model_name="job",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="algorithmimage",
            name="algorithm",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="algorithm_container_images",
                to="algorithms.Algorithm",
            ),
        ),
    ]
