# Generated by Django 2.2.6 on 2019-10-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("algorithms", "0012_auto_20191007_1222")]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="visible_to_public",
            field=models.BooleanField(
                default=False,
                help_text="Should this algorithm be visible to all users on the algorithm overview page? This does not grant all users permission to use this algorithm. Users will still need to be added to the algorithm users group in order to do that.",
            ),
        )
    ]
