# Generated by Django 3.1.13 on 2021-08-30 11:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0012_auto_20210728_1019"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ("created",),
                "permissions": [("view_logs", "Can view the jobs logs")],
            },
        ),
    ]
