# Generated by Django 3.1.13 on 2021-09-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0013_auto_20210830_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="image_requires_gpu",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="image_requires_memory_gb",
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="recurse_submodules",
            field=models.BooleanField(
                default=False,
                help_text="Do a recursive git pull when a GitHub repo is linked to this algorithm.",
            ),
        ),
        migrations.AddConstraint(
            model_name="algorithm",
            constraint=models.UniqueConstraint(
                condition=models.Q(_negated=True, repo_name=""),
                fields=("repo_name",),
                name="unique_repo_name",
            ),
        ),
    ]
