# Generated by Django 3.1.11 on 2021-07-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0013_auto_20210830_1128'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='algorithm',
            constraint=models.UniqueConstraint(fields=('repo_name',), name='unique_repo_name'),
        ),
    ]
