# Generated by Django 3.1.13 on 2021-09-10 09:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0014_auto_20210707_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='image_requires_cpu_cores',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='image_requires_gpu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='image_requires_gpu_memory_gb',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='image_requires_memory_gb',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
