# Generated by Django 3.1.13 on 2021-09-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0014_auto_20210917_0646"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="task_on_failure",
            field=models.JSONField(
                default=None,
                editable=False,
                help_text="Serialized task that is run on job failure",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="task_on_success",
            field=models.JSONField(
                default=None,
                editable=False,
                help_text="Serialized task that is run on job success",
                null=True,
            ),
        ),
    ]
