# Generated by Django 2.2.7 on 2019-12-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0015_algorithmpermissionrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="additional_information",
            field=models.TextField(
                blank=True,
                help_text="Any additional information that might be relevant to users for this algorithm. This is only displayed on the algorithm's detail page.",
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="contact_information",
            field=models.TextField(
                blank=True,
                help_text="Who should users contact with any questions regarding this algorithm? This information is only displayed on the algorithm's detail page.",
            ),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="info_url",
            field=models.URLField(
                blank=True,
                help_text="A URL to a page containing more information about the algorithm.",
            ),
        ),
    ]
