# Generated by Django 3.1.13 on 2021-09-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0015_auto_20210910_0941"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="algorithm", name="unique_repo_name",
        ),
        migrations.AddConstraint(
            model_name="algorithm",
            constraint=models.UniqueConstraint(
                condition=models.Q(_negated=True, repo_name=""),
                fields=("repo_name",),
                name="unique_repo_name",
            ),
        ),
    ]
