# Generated by Django 3.1.13 on 2021-10-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0016_auto_20211001_1128"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="highlight",
            field=models.BooleanField(
                default=False,
                help_text="Should this algorithm be advertised on the home page?",
            ),
        ),
    ]
