# Generated by Django 2.2.9 on 2020-01-21 15:54

from django.db import migrations, models

import grandchallenge.challenges.models
import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0017_algorithm_additional_terms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="logo",
            field=models.ImageField(
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.challenges.models.get_logo_path,
            ),
        ),
    ]
