# Generated by Django 3.1.13 on 2021-10-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0018_algorithmimage_user_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithmimage", name="queue_override",
        ),
        migrations.RemoveField(
            model_name="algorithmimage", name="staged_image_uuid",
        ),
    ]
