# Generated by Django 3.0.2 on 2020-02-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0019_auto_20200210_0523"),
    ]

    operations = [
        migrations.RenameField(
            model_name="algorithm",
            old_name="visible_to_public",
            new_name="public",
        ),
        migrations.AddField(
            model_name="result",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="If True, allow all logged in users to view this result along with the input image. Otherwise, only the job creator and algorithm editor will have permission to view this.",
            ),
        ),
    ]
