# Generated by Django 3.2.9 on 2021-11-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0020_auto_20211118_1249"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="image_on_information_page",
            field=models.CharField(
                choices=[
                    ("NO_IMG", "Do not show an image"),
                    ("LOGO", "Use logo"),
                    ("SOCIAL_IMG", "Use social image"),
                ],
                default="NO_IMG",
                help_text="Which image would you like to display on the information page, if any?",
                max_length=20,
            ),
        ),
    ]
