# Generated by Django 3.2.9 on 2021-11-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("algorithms", "0020_auto_20211118_1249")]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="additional_terms_markdown",
            field=models.TextField(
                blank=True,
                help_text="By using this algorithm, users agree to the site wide terms of service. If your algorithm has any additional terms of usage, define them here.",
            ),
        )
    ]
