# Generated by Django 3.2.10 on 2022-01-11 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("algorithms", "0022_alter_algorithm_use_flexible_inputs")]

    operations = [
        migrations.AddField(
            model_name="job",
            name="time_limit",
            field=models.PositiveSmallIntegerField(
                default=7200,
                help_text="Time limit for the job in seconds",
                validators=[
                    django.core.validators.MinValueValidator(limit_value=60),
                    django.core.validators.MaxValueValidator(
                        limit_value=14400
                    ),
                ],
            ),
        )
    ]
