# Generated by Django 3.0.2 on 2020-02-21 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0022_auto_20200221_1035"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithm", name="additional_information",
        ),
        migrations.RemoveField(
            model_name="algorithm", name="contact_information",
        ),
        migrations.RemoveField(model_name="algorithm", name="info_url",),
    ]
