# Generated by Django 3.2.10 on 2021-12-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0022_alter_algorithm_use_flexible_inputs"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="require_user_review",
            field=models.BooleanField(
                default=True,
                help_text="If ticked, new users need to be approved by an editor before they can try out the algorithm. If not ticked, new users are allowed access immediately.",
            ),
        ),
    ]
