# Generated by Django 3.2.10 on 2022-02-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("algorithms", "0023_job_time_limit")]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="access_request_handling",
            field=models.CharField(
                choices=[
                    ("MANUAL_REVIEW", "Manually review all requests"),
                    (
                        "ACCEPT_VERIFIED_USERS",
                        "Automatically accept requests from verified users only",
                    ),
                    (
                        "ACCEPT_ALL",
                        "Automatically accept requests from all users",
                    ),
                ],
                default="MANUAL_REVIEW",
                help_text="How would you like to handle access requests?",
                max_length=25,
            ),
        )
    ]
