# Generated by Django 3.0.2 on 2020-02-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0023_auto_20200221_1045"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="completed_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="started_at",
            field=models.DateTimeField(null=True),
        ),
    ]
