# Generated by Django 3.2.12 on 2022-03-16 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hanging_protocols", "0001_initial"),
        ("algorithms", "0024_algorithm_access_request_handling"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="hanging_protocol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hanging_protocols.hangingprotocol",
            ),
        ),
    ]
