# Generated by Django 3.0.5 on 2020-04-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0024_auto_20200227_1744"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmimage",
            name="queue_override",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
