# Generated by Django 3.2.12 on 2022-03-18 10:44

from django.db import migrations, models

import grandchallenge.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0025_algorithm_hanging_protocol"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="view_content",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[
                    grandchallenge.core.validators.JSONValidator(
                        schema={
                            "$schema": "http://json-schema.org/draft-06/schema#",
                            "additionalProperties": False,
                            "definitions": {},
                            "properties": {
                                "denary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "main": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "nonary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "octonary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "quaternary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "quinary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "secondary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "senary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "septenary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                                "tertiary": {
                                    "contains": {"type": "string"},
                                    "minItems": 1,
                                    "type": "array",
                                    "uniqueItems": True,
                                },
                            },
                            "title": "The Display Port Mapping Schema",
                            "type": "object",
                        }
                    )
                ],
            ),
        ),
    ]
