# Generated by Django 3.2.13 on 2022-06-02 06:40

from django.db import migrations, models

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0027_auto_20220503_1334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="logo",
            field=models.ImageField(
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="social_image",
            field=models.ImageField(
                blank=True,
                help_text="An image for this algorithm which is displayed when you post the link for this algorithm on social media. Should have a resolution of 640x320 px (1280x640 px for best display).",
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_social_image_path,
            ),
        ),
    ]
