# Generated by Django 3.2.13 on 2022-05-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0027_auto_20220503_1334"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmimage",
            name="latest_shimmed_version",
            field=models.CharField(default="", editable=False, max_length=8),
        ),
    ]
