# Generated by Django 3.2.13 on 2022-06-02 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0028_auto_20220602_0640"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmimage",
            name="latest_shimmed_version",
            field=models.CharField(default="", editable=False, max_length=8),
        ),
    ]
