# Generated by Django 3.1.1 on 2020-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0029_remove_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="job_limit",
            field=models.PositiveIntegerField(
                default=10,
                help_text="The limit on the number of times that a user can start a job for an algorithm.",
            ),
        ),
    ]
