# Generated by Django 3.1.1 on 2020-11-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0031_auto_20201117_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='job_weight',
            field=models.PositiveIntegerField(default=1, help_text='The weight factor that determines how much each job for this algorithm contributes to the total number of jobs a user has run.'),
        ),
    ]
