# Generated by Django 3.1.1 on 2020-11-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0031_auto_20201117_0746"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="job_credit",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The credits that it will require an algorithm user to run this algorithm.",
            ),
        ),
    ]
