# Generated by Django 3.2.16 on 2022-12-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "algorithms",
            "0036_algorithmgroupobjectpermission_algorithmimagegroupobjectpermission_algorithmimageuserobjectpermissio",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="credits_per_job",
            field=models.PositiveIntegerField(
                default=100,
                editable=False,
                help_text="The number of credits that are required for each execution of this algorithm.",
            ),
        ),
    ]
