# Generated by Django 3.2.17 on 2023-02-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0037_alter_algorithm_credits_per_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="If True, allow anyone to download this result along with the input image. Otherwise, only the job creator and users explicitly added as viewers of this job will have permission to download and view this result.",
            ),
        ),
    ]
