# Generated by Django 3.2.18 on 2023-02-21 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0037_alter_algorithm_credits_per_job"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="job",
            managers=[],
        ),
    ]
