# Generated by Django 3.2.18 on 2023-03-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0038_alter_job_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmimage",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="Add any information (e.g. version ID) about this image here.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="algorithmimage",
            name="is_desired_version",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
