# Generated by Django 4.0.10 on 2023-04-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0014_alter_componentinterface_kind"),
        ("algorithms", "0039_auto_20230404_1208"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="inputs",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)ss_as_input",
                to="components.componentinterfacevalue",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="outputs",
            field=models.ManyToManyField(
                related_name="%(app_label)s_%(class)ss_as_output",
                to="components.componentinterfacevalue",
            ),
        ),
    ]
