# Generated by Django 4.1.9 on 2023-06-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0041_remove_algorithmimage_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="interfaces_editable",
            field=models.BooleanField(
                default=True,
                help_text="If true, the input and output interfaces to this algorithm are editable",
            ),
        ),
    ]
