# Generated by Django 4.1.10 on 2023-07-05 07:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0041_remove_algorithmimage_ready"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="time_limit",
            field=models.PositiveSmallIntegerField(
                default=3600,
                help_text="Time limit for inference jobs in seconds",
                validators=[
                    django.core.validators.MinValueValidator(limit_value=300),
                    django.core.validators.MaxValueValidator(limit_value=3600),
                ],
            ),
        ),
    ]
