# Generated by Django 4.1.10 on 2023-08-15 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanging_protocols', '0010_alter_hangingprotocol_json'),
        ('algorithms', '0042_algorithm_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithm',
            name='hanging_protocol',
        ),
        migrations.AddField(
            model_name='algorithm',
            name='default_hanging_protocol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_hanging_protocol', to='hanging_protocols.hangingprotocol'),
        ),
        migrations.AddField(
            model_name='algorithm',
            name='optional_hanging_protocols',
            field=models.ManyToManyField(related_name='optional_hanging_protocol', to='hanging_protocols.hangingprotocol'),
        ),
    ]
