# Generated by Django 4.1.10 on 2023-08-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanging_protocols', '0010_alter_hangingprotocol_json'),
        ('algorithms', '0042_algorithm_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='optional_hanging_protocols',
            field=models.ManyToManyField(blank=True, related_name='optional_hanging_protocols_of_algorithm', to='hanging_protocols.hangingprotocol'),
        ),
    ]
