# Generated by Django 4.1.10 on 2023-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0042_algorithm_time_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmimage",
            name="storage_cost_per_month_usd_cents",
            field=models.PositiveSmallIntegerField(
                default=None,
                editable=False,
                help_text="The storage cost per month for this image in USD Cents, excluding Tax",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="compute_cost_euro_cents",
            field=models.PositiveSmallIntegerField(
                default=None,
                editable=False,
                help_text="The total compute cost for this job in Euro Cents, excluding Tax",
                null=True,
            ),
        ),
    ]
