# Generated by Django 4.1.10 on 2023-08-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanging_protocols', '0010_alter_hangingprotocol_json'),
        ('algorithms', '0043_remove_algorithm_hanging_protocol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='optional_hanging_protocols',
            field=models.ManyToManyField(blank=True, related_name='optional_hanging_protocol', to='hanging_protocols.hangingprotocol'),
        ),
    ]
