# Generated by Django 4.1.10 on 2023-08-24 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hanging_protocols', '0010_alter_hangingprotocol_json'),
        ('algorithms', '0043_algorithmimage_storage_cost_per_year_usd_millicents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionalProtocolsAlgorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.algorithm')),
                ('hanging_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanging_protocols.hangingprotocol')),
            ],
        ),
        migrations.AddField(
            model_name='algorithm',
            name='optional_hanging_protocols',
            field=models.ManyToManyField(blank=True, help_text='Optional alternative hanging protocols for this algorithm', related_name='optional_of_algorithm', through='algorithms.OptionalProtocolsAlgorithm', to='hanging_protocols.hangingprotocol'),
        ),
    ]
