# Generated by Django 4.1.11 on 2023-10-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0045_optionalhangingprotocolalgorithm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="public",
            field=models.BooleanField(
                default=False,
                help_text="If True, allow anyone to download this result along with the input image. Otherwise, only the job creator will have permission to download and view this result.",
            ),
        ),
    ]
