# Generated by Django 4.2.9 on 2024-02-07 13:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import grandchallenge.algorithms.models
import grandchallenge.core.storage
import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "uploads",
            "0005_useruploadgroupobjectpermission_useruploaduserobjectpermission",
        ),
        ("algorithms", "0047_remove_algorithmimage_is_on_sagemaker"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "model",
                    models.FileField(
                        blank=True,
                        help_text="a .tar.gz file that is extracted to /opt/ml/model/ during inference",
                        storage=grandchallenge.core.storage.PrivateS3Storage(),
                        upload_to=grandchallenge.algorithms.models.models_path,
                        validators=[
                            grandchallenge.core.validators.ExtensionValidator(
                                allowed_extensions=(".tar.gz",)
                            )
                        ],
                    ),
                ),
                ("sha256", models.CharField(editable=False, max_length=71)),
                (
                    "size_in_storage",
                    models.PositiveBigIntegerField(
                        default=0,
                        editable=False,
                        help_text="The number of bytes stored in the storage backend",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Add any information about this model (e.g. version ID)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="algorithm_models",
                        to="algorithms.algorithm",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uploads.userupload",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
