# Generated by Django 4.2.11 on 2024-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0047_remove_algorithmimage_is_on_sagemaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="detailed_error_message",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
