# Generated by Django 4.2.13 on 2024-05-31 14:20

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import grandchallenge.algorithms.models
import grandchallenge.core.storage
import grandchallenge.core.validators
import grandchallenge.uploads.validators


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("uploads", "0006_userupload_mimetype"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("algorithms", "0048_job_detailed_error_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "import_status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Initialized"),
                            (1, "Queued"),
                            (2, "Re-Queued"),
                            (3, "Started"),
                            (4, "Cancelled"),
                            (5, "Failed"),
                            (6, "Completed"),
                        ],
                        db_index=True,
                        default=0,
                    ),
                ),
                ("status", models.TextField(editable=False)),
                (
                    "model",
                    models.FileField(
                        blank=True,
                        help_text=".tar.gz file of the algorithm model that will be extracted to /opt/ml/model/ during inference",
                        storage=grandchallenge.core.storage.ProtectedS3Storage(),
                        upload_to=grandchallenge.algorithms.models.algorithm_models_path,
                        validators=[
                            grandchallenge.core.validators.ExtensionValidator(
                                allowed_extensions=(".tar.gz",)
                            )
                        ],
                    ),
                ),
                ("sha256", models.CharField(editable=False, max_length=71)),
                (
                    "size_in_storage",
                    models.PositiveBigIntegerField(
                        default=0,
                        editable=False,
                        help_text="The number of bytes stored in the storage backend",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Add any information (e.g. version ID) about this image here.",
                    ),
                ),
                (
                    "is_desired_version",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="algorithm_models",
                        to="algorithms.algorithm",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="uploads.userupload",
                        validators=[
                            grandchallenge.uploads.validators.validate_gzip_mimetype
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="job",
            name="algorithm_model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="algorithms.algorithmmodel",
            ),
        ),
        migrations.CreateModel(
            name="AlgorithmModelUserObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithms.algorithmmodel",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="AlgorithmModelGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithms.algorithmmodel",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
    ]
