# Generated by Django 4.2.13 on 2024-06-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0050_alter_algorithmmodel_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algorithmimage",
            options={
                "ordering": ("created", "creator"),
                "permissions": [
                    ("download_algorithmimage", "Can download algorithm image")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="algorithmmodel",
            options={
                "permissions": [
                    ("download_algorithmmodel", "Can download algorithm model")
                ]
            },
        ),
    ]
