# Generated by Django 4.2.13 on 2024-07-03 10:43

from django.db import migrations, models

import grandchallenge.components.models
import grandchallenge.core.storage
import grandchallenge.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0050_alter_algorithmmodel_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithmimage",
            name="image",
            field=models.FileField(
                blank=True,
                help_text=".tar.gz archive of the container image produced from the command 'docker save IMAGE | gzip -c > IMAGE.tar.gz'. See https://docs.docker.com/engine/reference/commandline/save/",
                storage=grandchallenge.core.storage.ProtectedS3Storage(),
                upload_to=grandchallenge.components.models.docker_image_path,
                validators=[
                    grandchallenge.core.validators.ExtensionValidator(
                        allowed_extensions=(".tar", ".tar.gz", ".tar.xz")
                    )
                ],
            ),
        ),
    ]
