# Generated by Django 4.2.14 on 2024-08-05 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0051_alter_algorithmimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="time_limit",
            field=models.PositiveIntegerField(
                default=3600,
                help_text="Time limit for inference jobs in seconds",
                validators=[
                    django.core.validators.MinValueValidator(limit_value=300),
                    django.core.validators.MaxValueValidator(
                        limit_value=43200
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="time_limit",
            field=models.PositiveIntegerField(
                help_text="Time limit for the job in seconds",
                validators=[
                    django.core.validators.MinValueValidator(limit_value=300),
                    django.core.validators.MaxValueValidator(
                        limit_value=43200
                    ),
                ],
            ),
        ),
    ]
