# Generated by Django 4.2.15 on 2024-09-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0053_job_is_complimentary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Started"),
                    (2, "Re-Queued"),
                    (3, "Failed"),
                    (4, "Succeeded"),
                    (5, "Cancelled"),
                    (6, "Provisioning"),
                    (7, "Provisioned"),
                    (8, "Executing"),
                    (9, "Executed"),
                    (10, "Parsing Outputs"),
                    (11, "Executing Algorithm"),
                    (13, "Finished validating inputs"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
