# Generated by Django 4.2.15 on 2024-09-12 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0053_job_is_complimentary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithm",
            name="average_duration",
        ),
        migrations.AddField(
            model_name="algorithm",
            name="minimum_credits_per_job",
            field=models.PositiveIntegerField(
                default=100,
                help_text="The minimum number of credits that are required for each execution of this algorithm. The actual number of credits required may be higher than this depending on the algorithms configuration.",
                validators=[
                    django.core.validators.MinValueValidator(limit_value=20),
                    django.core.validators.MaxValueValidator(limit_value=1000),
                ],
            ),
        ),
    ]
