# Generated by Django 4.2.14 on 2024-08-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0053_job_is_complimentary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algorithmimage",
            options={
                "ordering": ("created", "creator"),
                "permissions": [
                    ("download_algorithmimage", "Can download algorithm image")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="algorithmmodel",
            options={
                "permissions": [
                    ("download_algorithmmodel", "Can download algorithm model")
                ]
            },
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Started"),
                    (2, "Re-Queued"),
                    (3, "Failed"),
                    (4, "Succeeded"),
                    (5, "Cancelled"),
                    (6, "Provisioning"),
                    (7, "Provisioned"),
                    (8, "Executing"),
                    (9, "Executed"),
                    (10, "Parsing Outputs"),
                    (11, "Executing Algorithm"),
                    (12, "External Execution In Progress"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
