# Generated by Django 4.2.16 on 2024-10-07 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0055_alter_job_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="credits_consumed",
            field=models.PositiveSmallIntegerField(
                default=0,
                editable=False,
                help_text="The total credits consumed for this job",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="requires_gpu_type",
            field=models.CharField(
                choices=[
                    ("A100", "A100"),
                    ("A10G", "A10G"),
                    ("V100", "V100"),
                    ("K80", "K80"),
                    ("T4", "T4"),
                ],
                default="T4",
                editable=False,
                help_text="What GPU is required by this job?",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="job",
            name="requires_memory_gb",
            field=models.PositiveSmallIntegerField(
                default=32,
                editable=False,
                help_text="How much memory is required by this job?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="algorithm",
            name="minimum_credits_per_job",
            field=models.PositiveIntegerField(
                default=20,
                help_text="The minimum number of credits that are required for each execution of this algorithm. The actual number of credits required may be higher than this depending on the algorithms configuration.",
                validators=[
                    django.core.validators.MinValueValidator(limit_value=20),
                    django.core.validators.MaxValueValidator(limit_value=1000),
                ],
            ),
        ),
    ]
