# Generated by Django 4.2.16 on 2024-10-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0057_remove_algorithm_credits_per_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="detailed_error_message",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
