# Generated by Django 4.2.16 on 2024-10-10 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0058_algorithm_job_requires_gpu_type_and_more"),
    ]

    operations = [
        # TODO migrate deleted fields
    ]
