# Generated by Django 4.2.16 on 2024-10-10 11:59

from django.db import migrations


def set_requirements_from_active_image(apps, schema_editor):
    AlgorithmImage = apps.get_model(  # noqa: N806
        "algorithms", "AlgorithmImage"
    )

    for algorithm_image in AlgorithmImage.objects.filter(
        is_desired_version=True
    ):
        algorithm = algorithm_image.algorithm

        algorithm.job_requires_memory_gb = algorithm_image.requires_memory_gb

        if algorithm_image.requires_gpu:
            algorithm.job_requires_gpu_type = algorithm_image.desired_gpu_type
        else:
            algorithm.job_requires_gpu_type = ""

        algorithm.save()


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0058_algorithm_job_requires_gpu_type_and_more"),
    ]

    operations = [
        migrations.RunPython(
            set_requirements_from_active_image, elidable=True
        ),
    ]
