# Generated by Django 4.2.16 on 2024-10-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0059_auto_20241010_1159"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithm",
            name="image_requires_gpu",
        ),
        migrations.RemoveField(
            model_name="algorithm",
            name="image_requires_memory_gb",
        ),
        migrations.RemoveField(
            model_name="algorithmimage",
            name="desired_gpu_type",
        ),
        migrations.RemoveField(
            model_name="algorithmimage",
            name="requires_gpu",
        ),
        migrations.RemoveField(
            model_name="algorithmimage",
            name="requires_memory_gb",
        ),
    ]
