# Generated by Django 4.2.16 on 2024-10-23 11:18

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("algorithms", "0060_remove_algorithm_image_requires_gpu_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmUserCredit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "credits",
                    models.PositiveIntegerField(
                        help_text="The credits that a user can spend during the validity period on running this algorithm"
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(
                        help_text="Inclusive date from which these credits are valid"
                    ),
                ),
                (
                    "valid_until",
                    models.DateField(
                        help_text="Inclusive date until these credits are valid"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        help_text="Who agreed to these credits have been assigned and where the costs are coming from"
                    ),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        help_text="The algorithm that these credits can be used with",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithms.algorithm",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who these credits are applied to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "algorithm")},
            },
        ),
    ]
