# Generated by Django 4.2.16 on 2024-10-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0060_remove_algorithm_image_requires_gpu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="detailed_error_message",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
