# Generated by Django 4.2.17 on 2025-01-08 14:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hanging_protocols", "0012_alter_hangingprotocol_json"),
        ("algorithms", "0062_algorithmusercredit"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="optionalhangingprotocolalgorithm",
            unique_together={("algorithm", "hanging_protocol")},
        ),
    ]
