# Generated by Django 4.2.16 on 2024-11-25 14:40
import django.db.models.deletion
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models
from django.db.models import Count


def create_algorithm_interfaces(apps, _schema_editor):
    Algorithm = apps.get_model("algorithms", "Algorithm")  # noqa: N806
    AlgorithmInterface = apps.get_model(  # noqa: N806
        "algorithms", "AlgorithmInterface"
    )
    AlgorithmInterfaceThroughTable = apps.get_model(  # noqa: N806
        "algorithms", "AlgorithmInterfaceThroughTable"
    )
    ComponentInterface = apps.get_model(  # noqa: N806
        "components", "ComponentInterface"
    )

    for algorithm in Algorithm.objects.all():
        inputs = ComponentInterface.objects.filter(
            pk__in=algorithm.inputs.values_list("pk", flat=True)
        ).all()
        outputs = ComponentInterface.objects.filter(
            pk__in=algorithm.outputs.values_list("pk", flat=True)
        ).all()

        try:
            io = AlgorithmInterface.objects.annotate(
                input_count=Count("inputs", distinct=True),
                output_count=Count("outputs", distinct=True),
            ).get(
                inputs__in=inputs,
                outputs__in=outputs,
                input_count=len(inputs),
                output_count=len(outputs),
            )
        except ObjectDoesNotExist:
            io = AlgorithmInterface.objects.create()
            io.inputs.set(inputs)
            io.outputs.set(outputs)

        AlgorithmInterfaceThroughTable.objects.create(
            algorithm=algorithm, interface=io, is_default=True
        )


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0022_alter_componentinterface_kind_and_more"),
        ("algorithms", "0062_algorithmusercredit"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmInterface",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inputs",
                    models.ManyToManyField(
                        related_name="inputs",
                        to="components.componentinterface",
                    ),
                ),
                (
                    "outputs",
                    models.ManyToManyField(
                        related_name="outputs",
                        to="components.componentinterface",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlgorithmInterfaceThroughTable",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithms.algorithm",
                    ),
                ),
                (
                    "interface",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithms.algorithminterface",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="algorithm",
            name="interfaces",
            field=models.ManyToManyField(
                related_name="algorithm_interfaces",
                through="algorithms.AlgorithmInterfaceThroughTable",
                to="algorithms.algorithminterface",
            ),
        ),
        migrations.AddConstraint(
            model_name="algorithminterfacethroughtable",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("algorithm",),
                name="unique_default_interface_per_algorithm",
            ),
        ),
        migrations.AddConstraint(
            model_name="algorithminterfacethroughtable",
            constraint=models.UniqueConstraint(
                fields=("algorithm", "interface"),
                name="unique_algorithm_interface_combination",
            ),
        ),
        migrations.RunPython(create_algorithm_interfaces, elidable=True),
    ]
