# Generated by Django 4.2.19 on 2025-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0024_alter_componentinterface_kind_and_more"),
        ("algorithms", "0066_create_interfaces_for_jobs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="inputs",
            field=models.ManyToManyField(
                null=True,
                related_name="algorithm_inputs",
                to="components.componentinterface",
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="outputs",
            field=models.ManyToManyField(
                null=True,
                related_name="algorithm_outputs",
                to="components.componentinterface",
            ),
        ),
    ]
