# Generated by Django 4.2.18 on 2025-02-13 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0066_create_interfaces_for_jobs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithm",
            name="inputs",
        ),
        migrations.RemoveField(
            model_name="algorithm",
            name="outputs",
        ),
    ]
