# Generated by Django 4.2.20 on 2025-04-16 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("algorithms", "0068_remove_algorithm_result_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithm",
            name="inputs",
        ),
        migrations.RemoveField(
            model_name="algorithm",
            name="outputs",
        ),
    ]
