# Generated by Django 4.2.20 on 2025-04-22 15:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "algorithms",
            "0069_remove_algorithm_inputs_remove_algorithm_outputs",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algorithminterface",
            options={"ordering": ("created",)},
        ),
    ]
