# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0072_job_algorithms__status_4143fb_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="algorithmgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="algorithms__group_i_b2d807_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="algorithmimagegroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="algorithms__group_i_3516b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="algorithmmodelgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="algorithms__group_i_6ce20b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="algorithms__group_i_c97470_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="jobuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="algorithms__user_id_50c879_idx",
            ),
        ),
    ]
