# Generated by Django 4.2.21 on 2025-05-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0072_job_algorithms__status_4143fb_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="claimed_at",
            field=models.DateTimeField(null=True),
        ),
    ]
