# Generated by Django 4.2.21 on 2025-06-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "algorithms",
            "0074_algorithmimageuserobjectpermission_algorithms__user_id_ba5ee9_idx_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="job",
            name="completed_at",
        ),
        migrations.RemoveField(
            model_name="job",
            name="compute_cost_euro_millicents",
        ),
        migrations.RemoveField(
            model_name="job",
            name="started_at",
        ),
    ]
