# Generated by Django 4.2.21 on 2025-06-06 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("algorithms", "0075_remove_job_completed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="viewers",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="viewers_of_algorithm_job",
                to="auth.group",
            ),
        ),
    ]
