# Generated by Django 4.2.21 on 2025-06-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0076_alter_job_viewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="use_warm_pool",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Whether to use warm pools",
            ),
        ),
    ]
