# Generated by Django 4.2.21 on 2025-06-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0077_job_use_warm_pool"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="job_requires_gpu_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No GPU"),
                    ("A100", "NVIDIA A100 Tensor Core GPU (40-80 GiB VRAM)"),
                    ("A10G", "NVIDIA A10G Tensor Core GPU (24 GiB VRAM)"),
                    ("V100", "NVIDIA V100 Tensor Core GPU (16 GiB VRAM)"),
                    ("K80", "NVIDIA K80 GPU (12 GiB VRAM)"),
                    ("T4", "NVIDIA T4 Tensor Core GPU (16 GiB VRAM)"),
                ],
                default="",
                help_text="What GPU to attach to this algorithms inference jobs",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="job_requires_memory_gb",
            field=models.PositiveSmallIntegerField(
                default=8,
                help_text="How much memory (DRAM) to assign to this algorithms inference jobs",
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="requires_gpu_type",
            field=models.CharField(
                choices=[
                    ("", "No GPU"),
                    ("A100", "NVIDIA A100 Tensor Core GPU (40-80 GiB VRAM)"),
                    ("A10G", "NVIDIA A10G Tensor Core GPU (24 GiB VRAM)"),
                    ("V100", "NVIDIA V100 Tensor Core GPU (16 GiB VRAM)"),
                    ("K80", "NVIDIA K80 GPU (12 GiB VRAM)"),
                    ("T4", "NVIDIA T4 Tensor Core GPU (16 GiB VRAM)"),
                ],
                editable=False,
                help_text="What GPU is required by this job?",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="requires_memory_gb",
            field=models.PositiveSmallIntegerField(
                editable=False,
                help_text="How much memory (DRAM) is required by this job?",
            ),
        ),
    ]
