# Generated by Django 4.2.24 on 2025-10-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0079_alter_algorithm_time_limit_alter_job_time_limit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algorithmmodel",
            options={
                "ordering": ("created", "creator"),
                "permissions": [
                    ("download_algorithmmodel", "Can download algorithm model")
                ],
            },
        ),
    ]
