# Generated by Django 4.2.25 on 2025-10-20 13:18

import secrets

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0080_alter_algorithmimage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="signing_key",
            field=models.BinaryField(
                default=secrets.token_bytes,
                help_text="The key used to sign the inference result file",
                max_length=32,
            ),
        ),
    ]
