# Generated by Django 4.2.25 on 2025-10-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0081_job_signing_key"),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS pgcrypto;",
            reverse_sql="",
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE algorithms_job SET signing_key = gen_random_bytes(32) WHERE signing_key IS NULL;"
            ),
            reverse_sql="UPDATE algorithms_job SET signing_key = NULL;",
        ),
    ]
