# Generated by Django 4.2.25 on 2025-10-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0083_alter_job_signing_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="exec_duration",
            field=models.DurationField(
                default=None,
                editable=False,
                help_text="The duration of the execution, if measured. Excludes data validation, container pulling, model downloading, data downloading and data uploading times. Includes model loading time, input data loading time, processing time, output data writing time and any delays from shared hardware issues.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="invoke_duration",
            field=models.DurationField(
                default=None,
                editable=False,
                help_text="The duration of the invocation, if measured. Excludes data validation, container pulling, model downloading, data downloading and data uploading times. Potentially excludes model loading time, depending on the users implementation. Includes input data loading time, processing time, output data writing time and any delays from shared hardware issues.",
                null=True,
            ),
        ),
    ]
