# Generated by Django 4.2.25 on 2025-10-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0084_job_exec_duration_job_invoke_duration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algorithmimage",
            name="storage_cost_per_year_usd_millicents",
        ),
    ]
