# Generated by Django 4.2.26 on 2025-11-14 13:45

import pictures.models
from django.db import migrations
from pictures.migrations import AlterPictureField

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        (
            "algorithms",
            "0085_algorithm_logo_height_algorithm_logo_width_and_more",
        ),
    ]

    operations = [
        AlterPictureField(
            model_name="algorithm",
            name="logo",
            field=pictures.models.PictureField(
                aspect_ratios=["1/1"],
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="logo_height",
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_logo_path,
                width_field="logo_width",
            ),
        ),
        AlterPictureField(
            model_name="algorithm",
            name="social_image",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="social_image_height",
                help_text="An image for this algorithm which is displayed when you post the link for this algorithm on social media. Should have a resolution of 640x320 px (1280x640 px for best display).",
                pixel_densities=[1, 2],
                storage=grandchallenge.core.storage.PublicS3Storage(),
                upload_to=grandchallenge.core.storage.get_social_image_path,
                width_field="social_image_width",
            ),
        ),
    ]
