# Generated by Django 5.2.10 on 2026-01-27 13:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0089_job_algorithms__created_679c29_idx"),
        (
            "uploads",
            "0009_useruploadgroupobjectpermission_uploads_use_group_i_53998e_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithmimage",
            name="api_method",
            field=models.CharField(
                choices=[("exec", "Exec"), ("invoke", "Invoke")],
                default="exec",
                editable=False,
                max_length=6,
            ),
        ),
        migrations.AddConstraint(
            model_name="algorithmimage",
            constraint=models.CheckConstraint(
                condition=models.Q(("api_method__in", ["exec", "invoke"])),
                name="algorithms_algorithmimage_api_method_in_choices",
            ),
        ),
    ]
