# Generated by Django 5.2.12 on 2026-03-25 13:28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "algorithms",
            "0091_remove_algorithmimage_storage_cost_per_year_usd_millicents",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InteractiveAlgorithm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "interactive_algorithm_choice",
                    models.CharField(
                        choices=[("temp", "Temporary choice for development")],
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "algorithm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interactive_algorithms",
                        to="algorithms.algorithm",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("interactive_algorithm_choice__in", ["temp"])
                        ),
                        name="interactive_algorithm_choice_valid",
                    )
                ],
            },
        ),
    ]
