# Generated by Django 5.2.12 on 2026-03-31 11:06

import datetime
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "algorithms",
            "0091_remove_algorithmimage_storage_cost_per_year_usd_millicents",
        ),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "maximum_duration",
                    models.DurationField(
                        default=datetime.timedelta(seconds=600)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Queued"),
                            ("PROVISIONING", "Provisioning"),
                            ("PROVISIONED", "Provisioned"),
                            ("STARTING", "Starting"),
                            ("RUNNING", "Running"),
                            ("STOPPED", "Stopped"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=17,
                    ),
                ),
                (
                    "requires_gpu_type",
                    models.CharField(
                        choices=[
                            ("", "No GPU"),
                            (
                                "A100",
                                "NVIDIA A100 Tensor Core GPU (40 GiB VRAM)",
                            ),
                            (
                                "A10G",
                                "NVIDIA A10G Tensor Core GPU (24 GiB VRAM)",
                            ),
                            (
                                "V100",
                                "NVIDIA V100 Tensor Core GPU (16 GiB VRAM)",
                            ),
                            ("K80", "NVIDIA K80 GPU (12 GiB VRAM)"),
                            ("T4", "NVIDIA T4 Tensor Core GPU (16 GiB VRAM)"),
                        ],
                        editable=False,
                        max_length=4,
                    ),
                ),
                (
                    "requires_memory_gb",
                    models.PositiveSmallIntegerField(editable=False),
                ),
                (
                    "algorithm_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="algorithms.algorithmimage",
                    ),
                ),
                (
                    "algorithm_interface",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="algorithms.algorithminterface",
                    ),
                ),
                (
                    "algorithm_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="algorithms.algorithmmodel",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "viewers_group",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="viewers_of_endpoint",
                        to="auth.group",
                    ),
                ),
            ],
            options={
                "ordering": ("-created",),
                "permissions": [
                    ("invoke_endpoint", "Can invoke the endpoint")
                ],
            },
        ),
        migrations.CreateModel(
            name="EndpointGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithms.endpoint",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EndpointUserObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="algorithms.endpoint",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="endpoint",
            index=models.Index(
                fields=["status", "created"],
                name="algorithms__status_1fd66f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="endpoint",
            index=models.Index(
                fields=["created"], name="algorithms__created_0f3b9a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="endpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "PENDING",
                            "PROVISIONING",
                            "PROVISIONED",
                            "STARTING",
                            "RUNNING",
                            "STOPPED",
                            "FAILED",
                        ],
                    )
                ),
                name="endpoint_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="endpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "requires_gpu_type__in",
                        ["", "A100", "A10G", "V100", "K80", "T4"],
                    )
                ),
                name="endpoint_gpu_type_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="endpointgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="algorithms__group_i_0a1abd_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="endpointgroupobjectpermission",
            unique_together={("group", "permission", "content_object")},
        ),
        migrations.AddIndex(
            model_name="endpointuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="algorithms__user_id_9de315_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="endpointuserobjectpermission",
            unique_together={("user", "permission", "content_object")},
        ),
    ]
