# Generated by Django 5.2.12 on 2026-04-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0092_endpoint_endpointgroupobjectpermission_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="endpoint",
            old_name="max_duration",
            new_name="maximum_duration",
        ),
    ]
