# Generated by Django 5.2.12 on 2026-04-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0093_remove_endpoint_endpoint_status_valid_and_more"),
        (
            "components",
            "0028_remove_componentinterfacevalue_storage_cost_per_year_usd_millicents",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="algorithm_interface",
        ),
        migrations.AlterUniqueTogether(
            name="algorithminterfaceinput",
            unique_together={("input", "interface")},
        ),
        migrations.AlterUniqueTogether(
            name="algorithminterfaceoutput",
            unique_together={("output", "interface")},
        ),
    ]
