# Generated by Django 5.2.13 on 2026-04-29 16:23

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0095_rename_sha256_algorithmmodel_checksum"),
        ("components", "0029_alter_componentinterface_overlay_segments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PROVISIONED", "Provisioned"),
                            ("EXECUTING", "Executing"),
                            ("EXECUTED", "Executed"),
                            ("FAILURE", "Failure"),
                            ("SUCCESS", "Success"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="QUEUED",
                        max_length=11,
                    ),
                ),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        help_text="Time limit for the invocation in seconds",
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=86400
                            )
                        ],
                    ),
                ),
                (
                    "invoke_duration",
                    models.DurationField(
                        blank=True,
                        default=None,
                        help_text="The duration of the invocation, if measured. Excludes data validation, container pulling, model downloading, data downloading and data uploading times. Potentially excludes model loading time, depending on the users implementation. Includes input data loading time, processing time, output data writing time and any delays from shared hardware issues.",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="algorithms.endpoint",
                    ),
                ),
                (
                    "inputs",
                    models.ManyToManyField(
                        related_name="algorithms_endpoints_as_input",
                        to="components.componentinterfacevalue",
                    ),
                ),
                (
                    "outputs",
                    models.ManyToManyField(
                        related_name="algorithms_endpoints_as_output",
                        to="components.componentinterfacevalue",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
