# Generated by Django 5.2.13 on 2026-05-05 09:30

import secrets

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0096_invocation"),
        ("components", "0029_alter_componentinterface_overlay_segments"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="invocation",
            name="invocation_status_valid",
        ),
        migrations.AddField(
            model_name="endpoint",
            name="signing_key",
            field=models.BinaryField(
                default=secrets.token_bytes,
                help_text="The key used to sign the inference result file",
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="invocation",
            name="algorithm_interface",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.PROTECT,
                to="algorithms.algorithminterface",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invocation",
            name="status",
            field=models.CharField(
                choices=[
                    ("VALIDATING_INPUTS", "Validating inputs"),
                    ("QUEUED", "Queued"),
                    ("PROVISIONED", "Provisioned"),
                    ("EXECUTING", "Executing"),
                    ("EXECUTED", "Executed"),
                    ("FAILURE", "Failed"),
                    ("SUCCESS", "Succeeded"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="QUEUED",
                max_length=17,
            ),
        ),
        migrations.AddConstraint(
            model_name="invocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "VALIDATING_INPUTS",
                            "QUEUED",
                            "PROVISIONED",
                            "EXECUTING",
                            "EXECUTED",
                            "FAILURE",
                            "SUCCESS",
                            "CANCELLED",
                        ],
                    )
                ),
                name="invocation_status_valid",
            ),
        ),
    ]
