# Generated by Django 5.2.13 on 2026-05-09 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "algorithms",
            "0097_remove_invocation_invocation_status_valid_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="endpoint",
            name="runtime_metrics",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="endpoint",
            name="stderr",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="endpoint",
            name="stdout",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invocation",
            name="detailed_error_message",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="invocation",
            name="runtime_metrics",
            field=models.JSONField(default=dict, editable=False),
        ),
        migrations.AddField(
            model_name="invocation",
            name="stderr",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="invocation",
            name="stdout",
            field=models.TextField(default="", editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="invocation",
            name="error_message",
            field=models.CharField(editable=False, max_length=1024),
        ),
        migrations.AlterField(
            model_name="invocation",
            name="invoke_duration",
            field=models.DurationField(
                default=None,
                editable=False,
                help_text="The duration of the invocation. Excludes data validation, container pulling, model downloading, data downloading and data uploading times. Potentially excludes model loading time, depending on the users implementation. Includes input data loading time, processing time, output data writing time and any delays from shared hardware issues.",
                null=True,
            ),
        ),
    ]
