# Generated by Django 5.2.14 on 2026-05-29 15:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "algorithms",
            "0098_endpoint_runtime_metrics_endpoint_stderr_and_more",
        ),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="endpoint",
            name="endpoint_status_valid",
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="status",
            field=models.CharField(
                choices=[
                    ("QUEUED", "Queued"),
                    ("STARTED", "Started"),
                    ("RUNNING", "Running"),
                    ("FAILED", "Failed"),
                    ("STOPPED", "Stopped"),
                ],
                default="QUEUED",
                max_length=17,
            ),
        ),
        migrations.AddConstraint(
            model_name="endpoint",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["QUEUED", "STARTED", "RUNNING", "FAILED", "STOPPED"],
                    )
                ),
                name="endpoint_status_valid",
            ),
        ),
    ]
