# Generated by Django 5.2.15 on 2026-06-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0099_remove_endpoint_endpoint_status_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="runtime_metrics",
            field=models.JSONField(default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="stderr",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="endpoint",
            name="stdout",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="invocation",
            name="runtime_metrics",
            field=models.JSONField(default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="invocation",
            name="stderr",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="invocation",
            name="stdout",
            field=models.TextField(default="", editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="runtime_metrics",
            field=models.JSONField(default=dict, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="stderr",
            field=models.TextField(default="", null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="stdout",
            field=models.TextField(default="", null=True),
        ),
    ]
