# Generated by Django 5.2.15 on 2026-06-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "algorithms",
            "0100_alter_endpoint_runtime_metrics_alter_endpoint_stderr_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="endpoint",
            name="runtime_metrics",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="stderr",
        ),
        migrations.RemoveField(
            model_name="endpoint",
            name="stdout",
        ),
        migrations.RemoveField(
            model_name="invocation",
            name="runtime_metrics",
        ),
        migrations.RemoveField(
            model_name="invocation",
            name="stderr",
        ),
        migrations.RemoveField(
            model_name="invocation",
            name="stdout",
        ),
        migrations.RemoveField(
            model_name="job",
            name="runtime_metrics",
        ),
        migrations.RemoveField(
            model_name="job",
            name="stderr",
        ),
        migrations.RemoveField(
            model_name="job",
            name="stdout",
        ),
    ]
