# Generated by Django 5.2.15 on 2026-06-25 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0101_remove_endpoint_runtime_metrics_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="endpoint",
            options={
                "ordering": ("-created",),
                "permissions": [
                    ("invoke_endpoint", "Can invoke the endpoint"),
                    (
                        "view_logs",
                        "Can view the endpoints logs if they also have view_endpoint permission",
                    ),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="job",
            options={
                "ordering": ("created",),
                "permissions": [
                    (
                        "view_logs",
                        "Can view the jobs logs if they also have view_job permission",
                    )
                ],
            },
        ),
    ]
