# Generated by Django 5.2.15 on 2026-07-07 14:36

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0102_alter_endpoint_options_alter_job_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="endpoint",
            name="maximum_duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=600), editable=False
            ),
        ),
    ]
