# Generated by Django 5.2.16 on 2026-08-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithms", "0102_alter_endpoint_options_alter_job_options"),
        ("anatomy", "0002_alter_bodyregion_region_and_more"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("hanging_protocols", "0016_alter_hangingprotocol_json"),
        ("modalities", "0002_alter_imagingmodality_modality"),
        ("organizations", "0013_alter_organization_logo"),
        ("publications", "0005_alter_publication_identifier"),
        (
            "workstation_configs",
            "0032_alter_workstationconfig_overlay_segments",
        ),
        ("workstations", "0044_remove_session_user_finished"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="algorithm",
            constraint=models.UniqueConstraint(
                fields=("slug",), name="unique_algorithm_slug"
            ),
        ),
    ]
