# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registrationrequest',
            table=None,
        ),
    ]
