# Generated by Django 2.0.9 on 2018-10-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("submission_conversion", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="submissiontoannotationsetjob",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "Queued"),
                    (1, "Started"),
                    (2, "Re-Queued"),
                    (3, "Failed"),
                    (4, "Succeeded"),
                    (5, "Cancelled"),
                ],
                default=0,
            ),
        )
    ]
