# Generated by Django 3.0.5 on 2020-05-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("components", "0001_initial"),
        ("submission_conversion", "0003_auto_20200227_1744"),
    ]

    operations = [
        migrations.AddField(
            model_name="submissiontoannotationsetjob",
            name="inputs",
            field=models.ManyToManyField(
                related_name="submission_conversion_submissiontoannotationsetjob_inputs",
                to="components.ComponentInterfaceValue",
            ),
        ),
        migrations.AddField(
            model_name="submissiontoannotationsetjob",
            name="outputs",
            field=models.ManyToManyField(
                related_name="submission_conversion_submissiontoannotationsetjob_outputs",
                to="components.ComponentInterfaceValue",
            ),
        ),
    ]
