# Generated by Django 3.0.9 on 2020-08-27 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("submission_conversion", "0004_auto_20200622_1306"),
    ]

    operations = [
        migrations.DeleteModel(name="SubmissionToAnnotationSetJob",),
    ]
