# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hanging_protocols", "0013_alter_hangingprotocol_json"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hangingprotocoluserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="hanging_pro_user_id_802c8d_idx",
            ),
        ),
    ]
