# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "hanging_protocols",
            "0014_hangingprotocoluserobjectpermission_hanging_pro_user_id_802c8d_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="hangingprotocolgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="hanging_pro_group_i_67be21_idx",
            ),
        ),
    ]
