# Generated by Django 3.1.1 on 2020-11-24 13:16

import django.contrib.postgres.fields.citext
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ImagingModality",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        (
                            "modality",
                            django.contrib.postgres.fields.citext.CICharField(
                                max_length=16, unique=True
                            ),
                        ),
                    ],
                    options={"ordering": ("modality",)},
                ),
            ],
            # Table already created in challenge/0033_mode_imagingmodality
            database_operations=[],
        ),
    ]
