# Generated by Django 4.2.23 on 2025-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum_polls", "0003_topicpoll_hide_results"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topicpolloption",
            name="poll",
        ),
        migrations.RemoveField(
            model_name="topicpollvote",
            name="poll_option",
        ),
        migrations.RemoveField(
            model_name="topicpollvote",
            name="voter",
        ),
        migrations.DeleteModel(
            name="TopicPoll",
        ),
        migrations.DeleteModel(
            name="TopicPollOption",
        ),
        migrations.DeleteModel(
            name="TopicPollVote",
        ),
    ]
