# Generated by Django 3.0.2 on 2020-03-09 13:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20200218_1033"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="modified",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="distribution",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="product",
            name="fda_status",
            field=models.CharField(
                choices=[
                    ("cle", "510(k) cleared"),
                    ("dnc", "De novo 510(k) cleared"),
                    ("pma", "PMA approved"),
                    ("no", "No or not yet"),
                    ("na", "Not applicable"),
                    ("unk", "Unknown"),
                ],
                default="unk",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="input_data",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="modified",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="product",
            name="output_data",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="trigger",
            field=models.CharField(max_length=200),
        ),
    ]
