# Generated by Django 3.0.6 on 2020-06-11 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_auto_20200309_1329"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ("pk",), "verbose_name_plural": "companies"},
        ),
        migrations.AlterModelOptions(
            name="product", options={"ordering": ("pk",)},
        ),
    ]
