# Generated by Django 3.0.8 on 2020-07-09 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_auto_20200611_0746"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="short_name", new_name="slug",
        ),
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="short name used in url, specific css, files etc. No spaces allowed",
                max_length=500,
            ),
            preserve_default=False,
        ),
    ]
