# Generated by Django 3.0.8 on 2020-07-09 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_auto_20200611_0746"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="short_name",),
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
