# Generated by Django 3.1.8 on 2021-04-28 12:18

from django.db import migrations, models

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_auto_20200709_1129"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectAirFiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "study_file",
                    models.FileField(
                        upload_to=grandchallenge.core.storage.get_pdf_path
                    ),
                ),
            ],
        ),
    ]
