# Generated by Django 3.1.11 on 2021-07-01 20:18

from django.db import migrations, models
from django.utils.text import get_valid_filename


def get_pdf_path(instance, filename):
    return f"pdfs/{instance.__class__.__name__.lower()}/{instance.pk}/{get_valid_filename(filename)}"


class Migration(migrations.Migration):

    dependencies = [("products", "0006_product_ce_under")]

    operations = [
        migrations.CreateModel(
            name="ProjectAirFiles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "study_file",
                    models.FileField(upload_to=get_pdf_path),
                ),
            ],
        )
    ]
