# Generated by Django 3.1.13 on 2021-08-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_projectairfiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectairfiles",
            name="archive",
            field=models.BooleanField(default=False),
        ),
    ]
