# Generated by Django 3.1.13 on 2021-08-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_projectairfiles_archive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectairfiles",
            name="archive",
            field=models.BooleanField(
                default=False,
                help_text="Set to True if the file is no longer the most recent version. It will remain available on the page for download under archived protocols.",
            ),
        ),
    ]
