# Generated by Django 4.2.9 on 2024-01-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20220419_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='software_usage',
        ),
        migrations.AddField(
            model_name='product',
            name='intended_use_ce',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='intended_use_fda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
