# Generated by Django 4.2.9 on 2024-02-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0010_remove_post_companies"),
        ("products", "0011_remove_product_software_usage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="company",
        ),
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
        migrations.DeleteModel(
            name="ProjectAirFiles",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
