# Generated by Django 4.2.9 on 2024-01-20 13:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_remove_product_software_usage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="intended_use_ce_public",
            field=models.TextField(blank=True, null=True),
        ),
    ]
