from rest_framework.routers import DefaultRouter

from grandchallenge.api.permissions import IsAuthenticated


class APIRouter(DefaultRouter):
    """
    Custom router that overrides the root view's permission classes.

    The default DRF router root view inherits DEFAULT_PERMISSION_CLASSES
    (IsAdminUser), which blocks authenticated non-admin users from
    discovering the API. This router allows any authenticated user to
    access the root endpoint while keeping the global default strict.
    """

    def get_urls(self):
        urls = super().get_urls()

        # The root view is generated by get_urls; override its permission
        root_view = self.get_api_root_view()
        root_view.cls.permission_classes = [IsAuthenticated]

        return urls
