# Generated by Django 4.1.13 on 2023-11-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Incentive",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incentive", models.CharField(max_length=16, unique=True)),
            ],
            options={
                "ordering": ("incentive",),
            },
        ),
    ]
