# Generated by Django 4.1.13 on 2023-11-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incentives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incentive",
            name="incentive",
            field=models.CharField(max_length=24, unique=True),
        ),
    ]
