# Generated by Django 2.0.9 on 2018-10-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("profiles", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "default_permissions": ("add", "change", "delete"),
                "permissions": (("view_profile", "Can view profile"),),
            },
        )
    ]
