# Generated by Django 3.0.10 on 2020-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_auto_20181030_1605"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_verified",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
