# Generated by Django 3.0.10 on 2020-09-28 11:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("profiles", "0003_userprofile_is_verified")]

    operations = [
        migrations.RemoveField(model_name="userprofile", name="is_verified")
    ]
