# Generated by Django 3.1.1 on 2021-02-13 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0004_remove_userprofile_is_verified"),
    ]

    operations = [
        migrations.AlterModelOptions(name="userprofile", options={},),
        migrations.RemoveField(model_name="userprofile", name="privacy",),
    ]
