# Generated by Django 3.1.6 on 2021-03-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_auto_20210213_1330"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="organization_display",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
