# Generated by Django 3.1.9 on 2021-05-12 15:16

import stdimage.models
from django.db import migrations

import grandchallenge.core.storage


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0008_auto_20210406_0757"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mugshot",
            field=stdimage.models.JPEGField(
                blank=True,
                help_text="A personal image displayed in your profile.",
                upload_to=grandchallenge.core.storage.get_mugshot_path,
                verbose_name="mugshot",
            ),
        ),
    ]
