# Generated by Django 3.1.11 on 2021-06-17 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0009_auto_20210512_1516"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile", name="notifications_last_read_at",
        ),
    ]
