# Generated by Django 3.1.13 on 2021-11-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_remove_userprofile_notifications_last_read_at")
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="receive_newsletter",
            field=models.BooleanField(
                blank=True,
                help_text="Would you like to be put on our mailing list and receive newsletters about Grand Challenge updates?",
                null=True,
            ),
        )
    ]
