# Generated by Django 3.2.13 on 2022-06-02 06:40

from django.db import migrations, models

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0011_userprofile_receive_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mugshot",
            field=models.ImageField(
                blank=True,
                help_text="A personal image displayed in your profile.",
                upload_to=grandchallenge.core.storage.get_mugshot_path,
                verbose_name="mugshot",
            ),
        ),
    ]
