# Generated by Django 3.2.13 on 2022-06-02 06:40

import stdimage.models
from django.db import migrations

import grandchallenge.core.storage


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0011_userprofile_receive_newsletter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mugshot",
            field=stdimage.models.JPEGField(
                blank=True,
                force_min_size=False,
                help_text="A personal image displayed in your profile.",
                upload_to=grandchallenge.core.storage.get_mugshot_path,
                variations={
                    "full": (None, None, False),
                    "x02": (64, 64, True),
                    "x10": (320, 320, True),
                    "x15": (480, 480, True),
                    "x20": (640, 640, True),
                },
                verbose_name="mugshot",
            ),
        ),
    ]
