# Generated by Django 4.2.11 on 2024-03-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0014_userprofile_unread_messages_email_last_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="notification_email_choice",
            field=models.CharField(
                choices=[
                    ("DAILY_SUMMARY", "Send me an email with a daily summary"),
                    ("DISABLED", "Do not send me notification emails"),
                    ("INSTANT", "Send me an email immediately"),
                ],
                default="DAILY_SUMMARY",
                help_text="Whether to receive emails about unread notifications and direct messages, and how often (immediately vs. once a day if necessary).",
                max_length=13,
            ),
        ),
    ]
