# Generated by Django 4.2.11 on 2024-03-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_migrate_notification_email_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="receive_notification_emails",
            field=models.BooleanField(
                default=True,
                help_text="Whether to receive notification emails",
                null=True,
            ),
        ),
    ]
