# Generated by Django 4.2.11 on 2024-03-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_alter_userprofile_receive_notification_emails"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="receive_notification_emails",
        ),
    ]
