# Generated by Django 4.2.14 on 2024-08-06 11:37

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_migrate_mfa"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedEmailAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "email",
                    models.EmailField(
                        help_text="Email addresses that are banned from registering.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="The reason why this email address is banned."
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
