# Generated by Django 4.2.14 on 2024-08-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_migrate_mfa"),
    ]

    operations = [
        migrations.CreateModel(
            name="BannedEmailAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email addresses that are banned from registering.",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        help_text="The reason why this email address is banned."
                    ),
                ),
            ],
        ),
    ]
