# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0020_bannedemailaddress"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofileuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="profiles_us_user_id_b2d437_idx",
            ),
        ),
    ]
