# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0021_userprofileuserobjectpermission_profiles_us_user_id_b2d437_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofilegroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="profiles_us_group_i_4e7a22_idx",
            ),
        ),
    ]
