# Generated by Django 4.2.26 on 2025-11-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0022_userprofilegroupobjectpermission_profiles_us_group_i_4e7a22_idx",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mugshot_height",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mugshot_width",
            field=models.PositiveSmallIntegerField(editable=False, null=True),
        ),
    ]
