# Generated by Django 4.2.26 on 2025-11-14 13:45

import pictures.models
from django.db import migrations
from pictures.migrations import AlterPictureField

import grandchallenge.core.storage


class FilteredAlterPictureField(AlterPictureField):
    def to_picture_field(self, from_model, to_model):
        from_field = from_model._meta.get_field(self.name)

        if hasattr(from_field.attr_class, "delete_variations"):
            # remove obsolete django-stdimage variations
            for obj in from_model._default_manager.exclude(
                **{self.name: ""}
            ).iterator():
                field_file = getattr(obj, self.name)
                field_file.delete_variations()

        for obj in to_model._default_manager.exclude(
            **{self.name: ""}
        ).iterator():
            field_file = getattr(obj, self.name)
            field_file.save_all()


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0023_userprofile_mugshot_height_userprofile_mugshot_width",
        ),
    ]

    operations = [
        FilteredAlterPictureField(
            model_name="userprofile",
            name="mugshot",
            field=pictures.models.PictureField(
                aspect_ratios=["1/1"],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="mugshot_height",
                help_text="A personal image displayed in your profile.",
                pixel_densities=[1, 2],
                upload_to=grandchallenge.core.storage.get_mugshot_path,
                verbose_name="mugshot",
                width_field="mugshot_width",
            ),
        ),
    ]
