# Generated by Django 4.2.26 on 2025-11-14 13:45

import pictures.models
from django.db import migrations
from pictures.migrations import AlterPictureField

import grandchallenge.core.storage


class Migration(migrations.Migration):

    dependencies = [
        (
            "profiles",
            "0023_userprofile_mugshot_height_userprofile_mugshot_width",
        ),
    ]

    operations = [
        AlterPictureField(
            model_name="userprofile",
            name="mugshot",
            field=pictures.models.PictureField(
                aspect_ratios=["1/1"],
                blank=True,
                breakpoints={
                    "l": 1200,
                    "m": 992,
                    "s": 768,
                    "xl": 1400,
                    "xs": 576,
                },
                container_width=1200,
                file_types=["AVIF"],
                grid_columns=12,
                height_field="mugshot_height",
                help_text="A personal image displayed in your profile.",
                pixel_densities=[1, 2],
                upload_to=grandchallenge.core.storage.get_mugshot_path,
                verbose_name="mugshot",
                width_field="mugshot_width",
            ),
        ),
    ]
