# Generated by Django 5.2.15 on 2026-07-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0025_alter_userprofile_mugshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="receive_newsletter",
            field=models.BooleanField(
                default=False,
                help_text="Would you like to be put on our mailing list and receive newsletters about Grand Challenge updates?",
            ),
            preserve_default=False,
        ),
    ]
