# Generated by Django 3.1.11 on 2021-06-01 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_auto_20210601_0802"),
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="challenge",
            field=models.ForeignKey(
                help_text="Which challenge does this page belong to?",
                on_delete=django.db.models.deletion.PROTECT,
                to="challenges.challenge",
            ),
        ),
    ]
