# Generated by Django 3.2.13 on 2022-05-02 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_auto_20220413_0945"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpage",
            name="slug",
        ),
    ]
