# Generated by Django 4.2.19 on 2025-02-20 15:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0010_remove_historicalpage_html_remove_page_html"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpage",
            name="uses_markdown",
        ),
        migrations.RemoveField(
            model_name="page",
            name="uses_markdown",
        ),
    ]
