# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0011_remove_historicalpage_uses_markdown_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pagegroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="pages_pageg_group_i_804aca_idx",
            ),
        ),
    ]
