# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pages",
            "0012_pagegroupobjectpermission_pages_pageg_group_i_804aca_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pageuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="pages_pageu_user_id_a27d82_idx",
            ),
        ),
    ]
