# Generated by Django 4.2.21 on 2025-06-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pages",
            "0013_pageuserobjectpermission_pages_pageu_user_id_a27d82_idx",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalPage",
        ),
    ]
