# Generated by Django 4.2.23 on 2025-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum_permission", "0005_userforumpermission_authenticated_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="groupforumpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="groupforumpermission",
            name="forum",
        ),
        migrations.RemoveField(
            model_name="groupforumpermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="groupforumpermission",
            name="permission",
        ),
        migrations.AlterUniqueTogether(
            name="userforumpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="userforumpermission",
            name="forum",
        ),
        migrations.RemoveField(
            model_name="userforumpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="userforumpermission",
            name="user",
        ),
        migrations.DeleteModel(
            name="ForumPermission",
        ),
        migrations.DeleteModel(
            name="GroupForumPermission",
        ),
        migrations.DeleteModel(
            name="UserForumPermission",
        ),
    ]
