# Generated by Django 3.1.11 on 2021-06-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubWebhookMessage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        help_text="When we received the event."
                    ),
                ),
                ("payload", models.JSONField(default=None, null=True)),
                ("tarball", models.FileField(null=True, upload_to="")),
            ],
        ),
        migrations.AddIndex(
            model_name="githubwebhookmessage",
            index=models.Index(
                fields=["received_at"], name="webhooks_gi_receive_f2eef9_idx"
            ),
        ),
    ]
