# Generated by Django 2.1.7 on 2019-04-12 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='output',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_of_job', to='eyra_data.DataFile'),
        ),
    ]
