# Generated by Django 2.2.2 on 2019-06-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eyra_algorithms', '0003_auto_20190426_0909'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='implementation',
            constraint=models.UniqueConstraint(fields=('algorithm', 'version'), name='unique_version'),
        ),
    ]
