# Generated by Django 2.0.9 on 2018-11-06 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklists.Worklist')),
            ],
        ),
        migrations.CreateModel(
            name='WorklistSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorklistTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklists.WorklistSet')),
            ],
        ),
        migrations.AddField(
            model_name='worklist',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklists.WorklistTree'),
        ),
    ]
