# Generated by Django 2.0.9 on 2018-11-05 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title of Work list')),
            ],
        ),
        migrations.CreateModel(
            name='WorklistGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title of group')),
            ],
        ),
        migrations.AddField(
            model_name='worklist',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worklists.WorklistGroup'),
        ),
        migrations.AddField(
            model_name='worklist',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worklists.Worklist'),
        ),
    ]
