# Generated by Django 1.9.2 on 2016-02-25 04:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_member", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumprofile",
            name="signature",
            field=models.TextField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxLengthValidator(255)],
                verbose_name="Signature",
            ),
        ),
    ]
