# Generated by Django 1.9.2 on 2016-02-27 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_member", "0002_auto_20160225_0515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumprofile",
            name="signature",
            field=models.TextField(
                blank=True, null=True, verbose_name="Signature"
            ),
        ),
    ]
