# Generated by Django 2.1.2 on 2018-11-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_member", "0003_auto_20160227_2122"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Avatar"
            ),
        ),
    ]
