# Generated by Django 2.2.10 on 2020-04-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum_member", "0004_auto_20181103_1406"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forumprofile",
            name="signature",
            field=models.TextField(
                blank=True, null=True, verbose_name="Signature"
            ),
        ),
    ]
