# Generated by Django 4.2.23 on 2025-08-08 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forum_member", "0005_auto_20200423_1049"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ForumProfile",
        ),
    ]
