# Generated by Django 3.1.11 on 2021-07-02 20:27
import uuid

import django.db.models.deletion
from django.db import migrations, models

import grandchallenge.codebuild.models
import grandchallenge.core.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("algorithms", "0010_algorithm_repo_name"),
        ("github", "0002_auto_20210630_1807"),
    ]

    operations = [
        migrations.CreateModel(
            name="Build",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("build_id", models.CharField(max_length=1024)),
                ("project_name", models.CharField(max_length=1024)),
                ("status", models.CharField(blank=True, max_length=256)),
                (
                    "build_log",
                    models.FileField(
                        null=True,
                        storage=grandchallenge.core.storage.PrivateS3Storage(),
                        upload_to=grandchallenge.codebuild.models.log_path,
                    ),
                ),
                ("build_config", models.JSONField()),
                (
                    "algorithm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="algorithms.algorithm",
                    ),
                ),
                (
                    "webhook_message",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="github.githubwebhookmessage",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="build",
            index=models.Index(
                fields=["build_id"], name="codebuild_b_build_i_c5a93f_idx"
            ),
        ),
    ]
