# Generated by Django 4.2.7 on 2023-11-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_categories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasktype",
            name="type",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
