# Generated by Django 4.2.16 on 2024-10-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0002_auto_20201120_0807"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Credit",
        ),
    ]
