from django.urls import path

from grandchallenge.reader_studies.views import (
    AddDisplaySetsToReaderStudy,
    AddGroundTruthViaCSVToReaderStudy,
    AddQuestionToReaderStudy,
    AnswersRemoveForUser,
    DisplaySetBulkDelete,
    DisplaySetCreate,
    DisplaySetDelete,
    DisplaySetDetailView,
    DisplaySetInterfacesCreate,
    DisplaySetUpdateView,
    EditorsUpdate,
    QuestionDelete,
    QuestionInteractiveAlgorithmsView,
    QuestionInterfacesView,
    QuestionUpdate,
    QuestionWidgetsView,
    ReaderStudyCopy,
    ReaderStudyCreate,
    ReaderStudyDelete,
    ReaderStudyDetail,
    ReaderStudyDisplaySetList,
    ReaderStudyExampleGroundTruthCSV,
    ReaderStudyGroundTruth,
    ReaderStudyGroundTruthDelete,
    ReaderStudyGroundTruthFromAnswers,
    ReaderStudyLeaderBoard,
    ReaderStudyList,
    ReaderStudyPermissionRequestCreate,
    ReaderStudyPermissionRequestList,
    ReaderStudyPermissionRequestUpdate,
    ReaderStudyStatistics,
    ReaderStudyUpdate,
    ReadersUpdate,
    UsersProgress,
)

app_name = "reader-studies"

urlpatterns = [
    path("", ReaderStudyList.as_view(), name="list"),
    path("create/", ReaderStudyCreate.as_view(), name="create"),
    path("<slug:slug>/", ReaderStudyDetail.as_view(), name="detail"),
    path("<slug:slug>/update/", ReaderStudyUpdate.as_view(), name="update"),
    path("<slug:slug>/delete/", ReaderStudyDelete.as_view(), name="delete"),
    path(
        "<slug:slug>/leaderboard/",
        ReaderStudyLeaderBoard.as_view(),
        name="leaderboard",
    ),
    path(
        "<slug:slug>/display-sets/",
        ReaderStudyDisplaySetList.as_view(),
        name="display_sets",
    ),
    path(
        "<slug:slug>/statistics/",
        ReaderStudyStatistics.as_view(),
        name="statistics",
    ),
    path("<slug:slug>/copy/", ReaderStudyCopy.as_view(), name="copy"),
    path(
        "<slug:slug>/remove-answers/<username>/",
        AnswersRemoveForUser.as_view(),
        name="answers-remove",
    ),
    path(
        "<slug:slug>/ground-truth/",
        ReaderStudyGroundTruth.as_view(),
        name="ground-truth",
    ),
    path(
        "<slug:slug>/ground-truth/delete/",
        ReaderStudyGroundTruthDelete.as_view(),
        name="ground-truth-delete",
    ),
    path(
        "<slug:slug>/ground-truth/csv/create/",
        AddGroundTruthViaCSVToReaderStudy.as_view(),
        name="add-ground-truth-csv",
    ),
    path(
        "<slug:slug>/ground-truth/csv/example/",
        ReaderStudyExampleGroundTruthCSV.as_view(),
        name="example-ground-truth-csv",
    ),
    path(
        "<slug:slug>/ground-truth/answers/create/",
        ReaderStudyGroundTruthFromAnswers.as_view(),
        name="add-ground-truth-answers",
    ),
    path(
        "<slug:slug>/display-sets/create/",
        AddDisplaySetsToReaderStudy.as_view(),
        name="display-sets-create",
    ),
    path(
        "<slug:slug>/display-sets/delete/",
        DisplaySetBulkDelete.as_view(),
        name="display-sets-bulk-delete",
    ),
    path(
        "<slug:slug>/display-sets/create-single/",
        DisplaySetCreate.as_view(),
        name="display-set-create",
    ),
    path(
        "<slug:slug>/display-sets/<uuid:pk>/",
        DisplaySetDetailView.as_view(),
        name="display-set-detail",
    ),
    path(
        "<slug:slug>/display-sets/<uuid:pk>/update/",
        DisplaySetUpdateView.as_view(),
        name="display-set-update",
    ),
    path(
        "<slug>/display-sets/<uuid:pk>/delete/",
        DisplaySetDelete.as_view(),
        name="display-set-delete",
    ),
    path(
        "<slug:slug>/display-sets/new/interfaces/create/",
        DisplaySetInterfacesCreate.as_view(),
        name="display-set-new-interfaces-create",
    ),
    path(
        "<slug:slug>/display-sets/<uuid:pk>/interface/create/",
        DisplaySetInterfacesCreate.as_view(),
        name="display-set-interfaces-create",
    ),
    path(
        "<slug:slug>/questions/add/",
        AddQuestionToReaderStudy.as_view(),
        name="add-question",
    ),
    path(
        "<slug:slug>/questions/<uuid:pk>/update/",
        QuestionUpdate.as_view(),
        name="question-update",
    ),
    path(
        "<slug:slug>/questions/<uuid:pk>/delete/",
        QuestionDelete.as_view(),
        name="question-delete",
    ),
    path(
        "<slug:slug>/questions/interfaces/",
        QuestionInterfacesView.as_view(),
        name="question-interfaces",
    ),
    path(
        "<slug:slug>/questions/widgets/",
        QuestionWidgetsView.as_view(),
        name="question-widgets",
    ),
    path(
        "<slug:slug>/questions/interactive-algorithms/",
        QuestionInteractiveAlgorithmsView.as_view(),
        name="question-interactive-algorithms",
    ),
    path(
        "<slug:slug>/editors/update/",
        EditorsUpdate.as_view(),
        name="editors-update",
    ),
    path(
        "<slug:slug>/readers/update/",
        ReadersUpdate.as_view(),
        name="readers-update",
    ),
    path(
        "<slug:slug>/progress/", UsersProgress.as_view(), name="users-progress"
    ),
    path(
        "<slug:slug>/permission-requests/",
        ReaderStudyPermissionRequestList.as_view(),
        name="permission-request-list",
    ),
    path(
        "<slug:slug>/permission-requests/create/",
        ReaderStudyPermissionRequestCreate.as_view(),
        name="permission-request-create",
    ),
    path(
        "<slug:slug>/permission-requests/<int:pk>/update/",
        ReaderStudyPermissionRequestUpdate.as_view(),
        name="permission-request-update",
    ),
]
