# Generated by Django 4.2.15 on 2024-09-11 09:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import grandchallenge.core.validators
import grandchallenge.participants.models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("challenges", "0038_alter_challenge_options"),
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "question_text",
                    models.TextField(
                        help_text="Text that will be displayed as a label during registration."
                    ),
                ),
                (
                    "question_help_text",
                    models.TextField(
                        blank=True,
                        help_text="Text that will be displayed as a helpful note during registration.",
                    ),
                ),
                (
                    "schema",
                    models.JSONField(
                        default=grandchallenge.participants.models.string_type_schema,
                        help_text="A JSON schema definition against which an answer is validated. See https://json-schema.org/.Only Draft 7, 6, 4 or 3 are supported.",
                        validators=[
                            grandchallenge.core.validators.JSONSchemaValidator()
                        ],
                    ),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the question requires an answer or not.",
                    ),
                ),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_questions",
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "unique_together": {("question_text", "challenge")},
            },
        ),
        migrations.CreateModel(
            name="RegistrationQuestionUserObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participants.registrationquestion",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="RegistrationQuestionGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participants.registrationquestion",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.group",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
    ]
