# Generated by Django 4.2.15 on 2024-09-02 12:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0037_external_evaluators_group"),
        ("participants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("question_text", models.TextField()),
                ("question_help_text", models.TextField(blank=True)),
                (
                    "schema",
                    models.JSONField(
                        blank=True,
                        help_text="A JSON schema definition against which an answer is validated",
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="challenges.challenge",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RegistrationQuestionAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.JSONField(blank=True, editable=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participants.registrationquestion",
                    ),
                ),
                (
                    "registration_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="participants.registrationrequest",
                    ),
                ),
            ],
        ),
    ]
