# Generated by Django 4.2.15 on 2024-09-12 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0002_registrationquestion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrationQuestionAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.JSONField(blank=True, default=str)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="participants.registrationquestion",
                    ),
                ),
                (
                    "registration_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_question_answers",
                        to="participants.registrationrequest",
                    ),
                ),
            ],
            options={
                "unique_together": {("registration_request", "question")},
            },
        ),
    ]
