# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_alter_registrationquestion_options_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="registrationquestiongroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="participant_group_i_eaa954_idx",
            ),
        ),
    ]
