# Generated by Django 4.2.15 on 2024-09-13 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("participants", "0003_registrationquestionanswer_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="registrationquestion",
            options={"ordering": ("created",)},
        ),
    ]
