# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "participants",
            "0004_registrationquestiongroupobjectpermission_participant_group_i_eaa954_idx",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="registrationquestionuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="participant_user_id_6d431f_idx",
            ),
        ),
    ]
