# Generated by Django 3.1.8 on 2021-04-13 09:13

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evaluation", "0004_auto_20210402_1508"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhaseConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("product_id", models.CharField(max_length=32)),
                ("provisioning_artefact_id", models.CharField(max_length=32)),
                (
                    "kind",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "SageMaker Notebook"), (1, "EC2 Linux")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceTypeConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instance_type", models.CharField(max_length=16)),
                (
                    "auto_stop_time",
                    models.PositiveSmallIntegerField(default=10),
                ),
                (
                    "kind",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "SageMaker Notebook"), (1, "EC2 Linux")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("PENDING", "Pending"),
                            ("TAINTED", "Tainted"),
                            ("FAILED", "Failed"),
                            ("COMPLETED", "Available"),
                            ("STARTING", "Starting"),
                            ("STARTING_FAILED", "Starting Failed"),
                            ("STOPPED", "Stopped"),
                            ("STOPPING", "Stopping"),
                            ("STOPPING_FAILED", "Stopping Failed"),
                            ("TERMINATING", "Terminating"),
                            ("TERMINATED", "Terminated"),
                            ("TERMINATING_FAILED", "Terminating Failed"),
                        ],
                        default="QUEUED",
                        max_length=18,
                    ),
                ),
                (
                    "phase_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.phaseconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField()),
                ("_token", models.TextField(db_column="token")),
                (
                    "provider",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "internal")], default=0
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="phaseconfiguration",
            name="allowed_configurations",
            field=models.ManyToManyField(
                blank=True,
                related_name="phase_configurations",
                to="workspaces.WorkspaceTypeConfiguration",
            ),
        ),
        migrations.AddField(
            model_name="phaseconfiguration",
            name="phase",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluation.phase",
            ),
        ),
    ]
