# Generated by Django 3.1.8 on 2021-04-12 13:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("evaluation", "0004_auto_20210402_1508"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhaseConfiguration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("product_id", models.CharField(max_length=32)),
                ("provisioning_artefact_id", models.CharField(max_length=32)),
                (
                    "kind",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "SageMaker Notebook"), (1, "EC2 Linux")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceTypeConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("instance_type", models.CharField(max_length=16)),
                (
                    "auto_stop_time",
                    models.PositiveSmallIntegerField(default=10),
                ),
                (
                    "kind",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "SageMaker Notebook"), (1, "EC2 Linux")]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "phase_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="workspaces.phaseconfiguration",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                (
                    "provider",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "internal")]
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="phaseconfiguration",
            name="allowed_configurations",
            field=models.ManyToManyField(
                blank=True,
                related_name="phase_configurations",
                to="workspaces.WorkspaceTypeConfiguration",
            ),
        ),
        migrations.AddField(
            model_name="phaseconfiguration",
            name="phase",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="evaluation.phase",
            ),
        ),
    ]
