# Generated by Django 4.2.9 on 2024-01-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "workspaces",
            "0002_workspacegroupobjectpermission_workspaceuserobjectpermission",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="configuration",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="phase",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="workspacegroupobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="workspacegroupobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="workspacegroupobjectpermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="workspacegroupobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="workspacetypeconfiguration",
            name="enabled_phases",
        ),
        migrations.AlterUniqueTogether(
            name="workspaceuserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="workspaceuserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="workspaceuserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="workspaceuserobjectpermission",
            name="user",
        ),
        migrations.DeleteModel(
            name="WorkbenchToken",
        ),
        migrations.DeleteModel(
            name="Workspace",
        ),
        migrations.DeleteModel(
            name="WorkspaceGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="WorkspaceTypeConfiguration",
        ),
        migrations.DeleteModel(
            name="WorkspaceUserObjectPermission",
        ),
    ]
