# Generated by Django 4.2.17 on 2025-01-08 14:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("direct_messages", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="conversationparticipant",
            unique_together={("conversation", "participant")},
        ),
        migrations.AlterUniqueTogether(
            name="directmessageunreadby",
            unique_together={("direct_message", "unread_by")},
        ),
    ]
