# Generated by Django 4.2.20 on 2025-05-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "direct_messages",
            "0002_alter_conversationparticipant_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversationuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="direct_mess_user_id_3dc03c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="directmessageuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="direct_mess_user_id_a9aec4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="muteuserobjectpermission",
            index=models.Index(
                fields=["user", "permission"],
                name="direct_mess_user_id_8ac5ae_idx",
            ),
        ),
    ]
