# Generated by Django 4.2.21 on 2025-05-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "direct_messages",
            "0003_conversationuserobjectpermission_direct_mess_user_id_3dc03c_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddIndex(
            model_name="conversationgroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="direct_mess_group_i_b2581a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="directmessagegroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="direct_mess_group_i_0cdb44_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="mutegroupobjectpermission",
            index=models.Index(
                fields=["group", "permission"],
                name="direct_mess_group_i_a14c94_idx",
            ),
        ),
    ]
